### ISSUE TITLE
Using back button after form submit

### ISSUE THREAD

**Issue by smackie604** [jquery/jquery-mobile#2452]
Using the back button on the page which a form is submitted to causes the form page to be reloaded and the form data to be cleared.  This only happens when data-dom-cache is not enabled on the form page.

Someone posted the fix here which seems to work:
http://forum.jquery.com/topic/transition-back-to-previous-page-on-form-submit

In the proposed change, need to pass the direction option into this $mobile.changePage call which currently resides at line 1161 of  jquery.mobile.navigation.js

```
$.mobile.changePage(
	url,
	{
		type:    type && type.length && type.toLowerCase() || "get",
		data:    $this.serialize(),
		transition:  $this.jqmData( "transition" ),
		direction:  $this.jqmData( "direction" ),
		reloadPage:  true
	}
);
```
To:

```
var direction = $this.jqmData( "direction" );
reverse = direction && direction == 'reverse';
$.mobile.changePage(
	url,
	{
		type:    type && type.length && type.toLowerCase() || "get",
		data:    $this.serialize(),
		transition:  $this.jqmData( "transition" ),
		direction:  direction,
		reverse:  reverse,
		reloadPage:  true
	}
);
```

**Comment by apsdehal** [comment]
It would be good to have a fiddle explaining the whole scenario, closing for now due to inactivity for a long time. @smackie604 If you still find the issue feel free to reopen with a fiddle.
