### ISSUE TITLE
Framework needs a mobileready event.

### ISSUE THREAD

**Issue by jblas** [jquery/jquery-mobile#2661]
Historically folks have been waiting for the first pageshow or pagechange event to figure out when they can run their code to initialize their application. This is fine for some folks, but some developers need to know is when the framework is actually done initializing itself. Since set up of the first page, resulting in the first pageshow and pagechange, is just part of the framwork initialization, it would be nice to know definitively when it is done initializing itself.

What we really need is a mobileinitcomplete or mobileready event to tell folks the framework is initialized and ready to go.

**Comment by apsdehal** [comment]
@arschmitz Any updates on this? We have a "mobileinit" event.

**Comment by arschmitz** [comment]
yes lets close it there has not been any one asking if they do we can reconsidder
