### ISSUE TITLE
preventDefault does not prevent history change during pagebeforechange event

### ISSUE THREAD

**Issue by kirk911** [jquery/jquery-mobile#3136]
We intercept the pagebeforechange event and sometimes cancel the event using preventDefault. When pagebeforechange is fired from a back button with data-rel="back", even though the pagebeforechange event is cancelled using preventDefault, the url has already decremented one page in history. I don't know how to setup a multipage environment with history within jsfiddle, or I'd setup an example.  Removing data-rel="back" and setting an href in the back button does not cause this behavior.  This is happening in version 1.0.

**Comment by gabrielschulhof** [comment]
@arschmitz I propose we close this, unless we want to implement forcefully preventing someone from retreating in the browser history by moving forward whenever they attempt to move back and the consequent pagebeforechange event's default is prevented.
