### ISSUE TITLE
IOS orientation Change fixed header not resizing

### ISSUE THREAD

**Issue by webdpro** [jquery/jquery-mobile#3956]
On IOS when viewing the rc1 and nightly with fixed header the orientation change both fixed header and footer do no expand after orientation. They will change a few second after or if you move the screen but it make it look kind of sloppy. 

I tested it on a new ipod with the RC1.1 demo code and the nightlies same result.

**Comment by apsdehal** [comment]
I have tested this iOS 8, which is the minimum version we support now with version 1.5 and this appears no longer to be an issue. Closing accordingly.
![bs_realios_mobile_iphone 6-8 0](https://cloud.githubusercontent.com/assets/3616806/16207210/8fc14196-3749-11e6-9249-062c17cec405.jpg)
