### ISSUE TITLE
add support for Opera transitions

### ISSUE THREAD

**Issue by chrisben** [jquery/jquery-mobile#4521]
While checking the JQM doc pages ('1.1.0' or 'test') on Opera 12 I found that navigating to another page shows an empty page (then a click on the browser back button shows another empty page). If the destination page is reloaded though it shows the page correctly.

When the first page loads, the "Scripts" developer panel shows a :

     Unhandled DOMException: SYNTAX_ERR

in jquery code with this call stack (sorry minified code there):

m jquery-1.7.1.min.js:3
a.find jquery.mobile-1.1.0.min.js:25
find jquery-1.7.1.min.js:3
a.mobile.focusPage jquery.mobile-1.1.0.min.js:51
<anonymous function> jquery.mobile-1.1.0.min.js:40
<anonymous function> jquery.mobile-1.1.0.min.js:41
f jquery.mobile-1.1.0.min.js:42
a.mobile.changePage jquery.mobile-1.1.0.min.js:63
initializePage jquery.mobile-1.1.0.min.js:175
<anonymous function> jquery.mobile-1.1.0.min.js:176
f.Callbacks jquery-1.7.1.min.js:2
fireWith jquery-1.7.1.min.js:2
ready jquery-1.7.1.min.js:2
B jquery-1.7.1.min.js:2

Maybe this is not related to the above navigation problem by the way..

Not sure if that's a jquery problem, a JQM one or Opera..

Tested using Opera 12.00 Build 1467 for Linux  (Opera Turbo Off and On : same problem).

Update: Problem not reproduced in opera 12 mobile on Android ICS.

**Comment by jaspermdegroot** [comment]
Actually ```& !opera``` was removed with the same commit: https://github.com/jquery/jquery-mobile/commit/749c78e6407da683a720d15635bc938b3b864df2#diff-07cac4035b048ed039811db6b43d4d5dL211. Closing as resolved.
