### ISSUE TITLE
Popup Flip-Transition places content under Video in Safari

### ISSUE THREAD

**Issue by cschnell** [jquery/jquery-mobile#4981]
When using the flip transition to open a popup on a page that has a video included, the content of the popup is placed below the video. This happens only on safari for MacOS and iOS. Chrome, Firefox and others do not have this issue. Also, when using another transition, like pop, the problem does not happen.

here is a jsFiddle that shows the issue: http://jsfiddle.net/KsM8r/

Again, this only happens on Safari (MacOS and iOS) and only, if there is a video on the page.

**Comment by apsdehal** [comment]
No longer an issue with latest jqm closing.
