### ISSUE TITLE
On changePage with reloadPage: true pageInit its applied to the current page in the DOM not the reloaded one 

### ISSUE THREAD

**Issue by gheiler** [jquery/jquery-mobile#5002]
This is a tricky one, suppose you load a page, that page has a pageinit event binded that does something (in my example writes some html), then you change to another page, and as expected your last page its still in the DOM. So now if you want to go back to that page using changePage with the option reloadPage: true, the pageInit event that should be executed on the new reloaded page executes in the one that was already in the DOM. Of course you can avoid this by removing the conflicting page once you change the page the first time but that's just an ugly fix.

Here jsbin to demonstrate:

http://jsbin.com/welcome/22772

Always nice to say your doing a magnificent job!

**Comment by gabrielschulhof** [comment]
This is indeed a design issue and will likely remain this way. The initial page is never removed from the DOM, even if reloadPage is specified.
