### ISSUE TITLE
Series 40 and Symbian^3 loading / enhancement issues

### ISSUE THREAD

**Issue by Hamdiakoguz** [jquery/jquery-mobile#5309]
When I try to visit jquerymobile.com/test  page with Nokia 1680 c-2 (which is a Series 40 5th Edition phone) it at first loads the bare html page and then says it is processing the page. Then all content disappears and a white page is displayed. 

When i test with http://jquerymobile.com/demos/1.1.0/ page loads normally.

**Comment by arschmitz** [comment]
These device are so far out of support at this point im going to close this.
