### ISSUE TITLE
Rename class ui-disabled to ui-state-disabled and implement .widget() method

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#5390]
The widget factory's implementation of _setOption( "disabled", newValue ) assigns two classes to the element returned by a widget implementation's widget() function: namespace-widgetname-disabled and ui-state-disabled.

So, we should do two things to take advantage of this functionality:

1. Implement .widget() for all our widgets. The default implementation in the widget factory returns this.element from .widget(), which means the above-mentioned classes will be assigned to this.element. This is not very useful for us, because we often wrap this.element in what is really the widget's outermost element, so we should override that method for those widgets that do that.

2. Rename our ui-disabled class to ui-state-disabled, so as to avoid duplicating the code from the widget factory. That is, our _setOption( "disabled", newValue ) implementations should not have to add/remove the class ui-disabled, when the widget factory already does that for us.

**Comment by arschmitz** [comment]
Closing this we have addressed this everywhere
