### ISSUE TITLE
Popups - re-position in iOS6

### ISSUE THREAD

**Issue by toddparker** [jquery/jquery-mobile#5523]
In iOS6, if you open a page like:
http://jquerymobile.com/test/docs/demos/buttons/

Then tap the view source button, you will see the popup open, then hide, then reshow. This is due to it re-calculating it's positioning that we looked at earlier and its crept back in.

**Comment by gabrielschulhof** [comment]
@RobertMe, @DirkTeurlings can you please try http://view.jquerymobile.com/7862-popup-repositioning/demos/popup/? #7862 has a fix that seeks to minimize the popup's jumping around the screen in response to virtual keyboard appearance/disappearance.
