### ISSUE TITLE
[1.3.0-beta.1] Hash Processing error when hash has parameters (e.g., /#taskGroupDetails/7)

### ISSUE THREAD

**Issue by bjwiederholt** [jquery/jquery-mobile#5567]
This is issue similar to #5483 

I am using backbone and have attempted to turn off all JQM processing

$(document).bind("mobileinit", function () {
    $.mobile.ajaxEnabled = false;
    $.mobile.linkBindingEnabled = false;
    $.mobile.hashListeningEnabled = false;
    $.mobile.pushStateEnabled = false;
    $.mobile.changePage.defaults.changeHash = false;
);
I handle the changing of the page with the $.mobile.changePage() method

$.mobile.changePage($(view.el), {
                                    changeHash:false,
                                });

As resolved in that issue #5483, this works with simple hash like /#groups or /#settings, but when I have hash that includes parameters, like http://localhost:8080/#taskGroupDetails/7 
I am seeing attempts by JQM to process the url.
In particular, I am seeing a 404 when JQM attempts to call backend with 
http://localhost:8080/taskGroupDetails/7   (notice lack of hash)
I am seeing this 404 before my backbone router code get executed.  There should not be an attempt by JQM to perform this request.

Another side effect is that all subsequent URL processing now includes 'taskGroupDetails' in the URL, e.g., http://localhost:8080/taskGroupDetails/7/...now-we-see-the-correct-piece-of-url...

I can provide sample code as necessary.

**Comment by arschmitz** [comment]
looks like this was fixed already from the links closing

**Comment by pYr0x** [comment]
i didnt see a fix?
