### ISSUE TITLE
Select element as a non-native menu is too slow on Samsung Galaxy S3.

### ISSUE THREAD

**Issue by kadaj** [jquery/jquery-mobile#5625]
The select element with `data-native-menu="false"` which brings up a dialog component which has only 95 `li` elements including optgroup elements makes the list very slow in Samsung Galaxy S3 when packaged as a PhoneGap application. When our app is taken using Chrome browser, the list scrolls smoothly, but the item click which marks the checkbox is very slow. It seems like the list items is re-created on each item click. Why so?
Btw the select menu allows for multiple selections.
Thanks.

**Comment by arschmitz** [comment]
@Ruffio no we are going to be replacing the current selectmenu with the one from jQuery UI in the near future so we will not be putting any substantial changes to the current selectmenu. 

Also note this *MAY* no longer be an issue anyway there have been many related perf improvements made in the last year and a half. 

Im going to close this as wont fix ( though if there are simple things that could improve it with out ay real refactor we would be open to suggestions / pr's )
