### ISSUE TITLE
Make the presence of ARIA landmarks inside pages configurable

### ISSUE THREAD

**Issue by vick08** [jquery/jquery-mobile#5650]
Currently, JQM inserts ARIA landmarks such as Banner, Main and others into the pages by default. While this is a good idea for mobile web sites, this is rather unnecessary in self-contained apps (created with Phonegap, for example).
I therefore propose that these landmarks can be toggled on or off via the configuration options.

**Comment by arschmitz** [comment]
We have discussed this and this is important in all environments screen readers still work in in apps with phonegap. We do not consider accessibility optional so im going to close this. As far as HTML5 elements it will not hurt anything to add them still. These will not cause a repaint or reflow so adding them is not really a performance concern.
