### ISSUE TITLE
Forms and popups - role="fieldcontain" and popup-appending

### ISSUE THREAD

**Issue by Pfilop** [jquery/jquery-mobile#5780]
Hi.

A div with data-role="fieldcontain" doesnt work inside a popup.
You can see an example here: http://jsfiddle.net/B3pyG/

Also jQM is appending all the popup-containers at the end of the role="page" no matter where its placed in the HTML.
When you have a big form and some of its fields inside a popup, these fields will be moved and are no longer inside the form itself, so you cant read the values anymore and are forced to move them again, before the form submit.

Thanks

**Comment by gabrielschulhof** [comment]
@Pfilop I believe you can solve the button-outside-the-form problem by giving the form an ID, and referring to the form via the button's ```form``` attribute:
```HTML
<form id="the-form">
...
</form>
...
<button form="the-form">Submit</button>
```
Note though that, in the case of a submit button inside a popup, there's a [bug](https://github.com/jquery/jquery-mobile/issues/6119) for which the [fix](https://github.com/jquery/jquery-mobile/pull/7929) will land in 1.5.0.
