### ISSUE TITLE
Manually setting selected option in SELECT on focus doesn't update text if user doesn't change.

### ISSUE THREAD

**Issue by joshmouch** [jquery/jquery-mobile#5802]
I have a focus listener on a select element.  In it, I select the middle option, to make it easier to scroll through all the options.

If the user clicks on the SELECT element and selects an option *OTHER* than the one I programmatically selected, things work fine.

However, if they select the option that I selected manually, the text in the select element does not update.  The actual select element has the correct value.  It's just that the ".ui-btn-text" element isn't updating.

I'm assuming that internally it's doing some sort of check to see if the select value changed between the focus event and the select event, which doesn't allow for anybody to change the value programmatically.

**Comment by gabrielschulhof** [comment]
I've tried to reproduce this using http://jsbin.com/umacun/2/ (which references master) and it seems to be working on IE10, IE9, and IE8. Please reopen if this is not the case.
