### ISSUE TITLE
Buggy Popups _handleDocumentFocusIn method and IE (at least IE7)

### ISSUE THREAD

**Issue by andi1984** [jquery/jquery-mobile#5814]
Hi,

the new _handleDocumentFocusIn is really buggy at least for IE7. 

When I call $(selector).popup('open') or the corresponding close call, the complete browser window is loosing focus.

Due to the fact that IE7 is listed under "Enhanced experience except without Ajax navigation features." this should work either, shouldn't it?

After commenting out _handleDocumentFocusin and the method calls in the jquery mobile core code the IE7 bug is gone. Please investigate this problem or at least exclude all IEs from this feature.

**Comment by gabrielschulhof** [comment]
This is fixed as of jQuery Mobile 1.4.5, precisely by avoiding a ```.blur()``` if the active element is the body or the window.
