### ISSUE TITLE
Panel: content blinks when opening a "unfixed" panel on iOS

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#5861]
When working on a fix for #5831 I noticed the following issue:

On iOS the page content blinks when opening a panel with position fixed that is unfixed by the framework because the panel content is longer than the viewport.

Tested on iPad Retina iOS 6.1.3 Mobile Safari and Chrome. Issue was not visible on Galaxy Nexus Android 4.2.1.
Test page: http://jsbin.com/alofim/10

Bit of history:

I initially fixed this by 3D-ing the page sections in the content wrap: de18420

That fix caused issues: the autocomplete search in the headers in the demo center shows a list with position absolute. The text of the page content was shown on top of this (seen on Chrome desktop).
To resolve this I only applied the 3D-ing when the panel is not closed: a6ff7de

That caused a regression: a blink on the page content and headings shifting a bit up and down when closing a panel.
Finally I completely removed the fix: 6b939a4

To fix this without downsides we have to find a way to unfix the panel before opening it. This requires the closed panel to already have a width of 17em so we it has the correct height. That should be possible but requires a few other changes.

**Comment by apsdehal** [comment]
No longer an issue with iOS version >= 7, below which we don't support anymore. Closing.
