### ISSUE TITLE
Prefetching breaks images on pages in subdirectory

### ISSUE THREAD

**Issue by jeromejaglale** [jquery/jquery-mobile#5986]
**Example**
index.html
a/test.html
images/night.jpg

index.html links (prefetch) to a/test.html which displays images/night.jpg using a relative url: ../images/night.jpg

**Problem**
When going directly to a/test.html, night.jpg is displayed.
When going from index.html to a/test.html (so test.html is prefetched), night.jpg is not displayed (it should).

On Ubuntu with Firefox 15 and Chrome 21.
jQuery Mobile 1.3.1
jQuery 1.9.1

**Test page/source code**
Test page: http://jeromejaglale.com/shared/jeromejaglale/jquery_mobile_prefetch_bug/
Source code online: http://code.google.com/p/jeromejaglale/source/browse/trunk/jquery_mobile_prefetch_bug
Source code download: http://jeromejaglale.com/shared/jquery_mobile_prefetch_bug.zip

**Notes**
The problem is that the base url is wrong for the prefetched page. If this can't be fixed, it would be useful to add a warning in the documention under "page prefetching".

**Comment by apsdehal** [comment]
Closing as per note in the content. Local fixes can be applied as per convenience.
