### ISSUE TITLE
Write unit tests for single module support

### ISSUE THREAD

**Issue by jzaefferer** [jquery/jquery-mobile#5987]
As discussed on the jquery-devs-team mailing list. These were my notes about issues when trying to use jQuery Mobile without the init module, in a very simple example:

Apart from an issue with nested listviews its mostly adding classes to various elements: ui-mobile to `<html>`, ui-mobile-viewport to `<body>`, ui-page and ui-page-active to a `<div>` that contains the actual content. And a few swatch classes to make things look okay.

Doesn't seem so bad now, but since this approach isn't documented anywhere (right?), I had to cobble that together from the generated markup. And the example really wasn't doing much. just a header, footer, a bit of navigation and a listview.

**Comment by apsdehal** [comment]
@arschmitz Can this be closed as we have individual modules now?

**Comment by arschmitz** [comment]
Yes but lets open issues for any widgets which dont have an individual module test already i think there are still a acouple
