### ISSUE TITLE
Internet Explorer and floating point numerical inputs

### ISSUE THREAD

**Issue by akloster** [jquery/jquery-mobile#6012]
I am working on a project where I need German users with IE8 through 10 to input floating point numbers in sliders. The decimal separator for German is "," not ".". In Chrome and Firefox I can input something like "5,5" and it will work as intended. In IE, no such luck, the comma gets deleted.

From my perspective this looks to be a compatibility issue, because the widget in IE doesn't accept the same input as other browsers do.

I don't have a good solution for this yet. I solved it by monkey patching window.parseFloat to replace commas with decimal points. That doesn't solve the display issue, because now the input displays a point-separated decimal.

**Comment by arschmitz** [comment]
No response in 8 months closing
