### ISSUE TITLE
Form validation fail in IE10 & IE11 with select-element

### ISSUE THREAD

**Issue by ottoville** [jquery/jquery-mobile#6021]
HTML5 form validation does not work correctly with select elements in IE 10 and latest jQuery Mobile

http://jsfiddle.net/BrBHM/

1: Choose some option.
2: Click "send" (You will see message "true" indicating that some choises were made)
3: Unchoose/clear any option you have chosen
4: Click "send", there should be message "false", but because of the bug, there is still message "true".

**Comment by apsdehal** [comment]
Working fine for with 1.5-dev.
