### ISSUE TITLE
Selectmenu in iframe fails in different conditions

### ISSUE THREAD

**Issue by ottoville** [jquery/jquery-mobile#6025]
I have found a bug in jQuery Mobile selection widget when using select widget with following rules:

(List updated)
*Data-native-menu=false
*Page is inside iframe
*There is facebook "like this page" widget in parent window
*User has refreshed the page  OR
  *browser history one page before is same page

Then closing the selection menu causes parent window to reload. That is tested with latest chrome and jQuery Mobile 1.3.1

The bug does not occur in every situation. It occurs when parent window's previous page (in browser history) is same than page itself, or parent window has been manually refreshed from browser refresh button.

I have not been able to reproduce this problem in jsfiddle so far, I will update issue if I am able to reproduce it in jsfiddle.

**Comment by apsdehal** [comment]
Closing I can no longer reproduce the issue.
