### ISSUE TITLE
Parsing the query string without the content after "?" causes loss of navigation

### ISSUE THREAD

**Issue by enanox** [jquery/jquery-mobile#6029]
Good evening, related to the closed issue #5710 in the 1.3.1 release, in the case that the app/website uses query string to pass data between callbacks (like using Facebook OAuth) the navigation crashes.

Please check the next link for clarification.

http://stackoverflow.com/questions/16422579/jquery-mobile-query-parameter-test-different-between-versions/16673287

Best regards.

**Comment by arschmitz** [comment]
This is working fine with code on master so im going to close this.

**Comment by enanox** [comment]
Awesome! Thank you!
