### ISSUE TITLE
Popup with select over popup button on android

### ISSUE THREAD

**Issue by webitstudios** [jquery/jquery-mobile#6034]
If a popup which contains a select element in it is opened and overlayed on top of button which opened the popup selects in the popup which are over the button are non functional they get highlight but do not open select on android 2.2 and 2.3 on 4.0 popup button text shows through popup but selects are functional.

**Comment by gabrielschulhof** [comment]
Is this issue still reproducible?

**Comment by arschmitz** [comment]
i can no longer confirm and no response from original reporter. We no longer support 2.2 or 4.0 so im going to close this.
