### ISSUE TITLE
listview( "option", "inset", true) does nothing

### ISSUE THREAD

**Issue by DerGuteWolf** [jquery/jquery-mobile#6059]
According to the documentation at http://api.jquerymobile.com/listview/#option-inset with ```listview( "option", "inset", true)``` one should be able to set the inset option after initialization. This does however not work and esp. does not set the inset classes, see http://jsbin.com/ataruz/1/

**Comment by gabrielschulhof** [comment]
I believe we can close this issue because we're deprecating style options such as this one altogether. Since we never got around to making listview's ```inset``` option work on-the-fly, and since now we're deprecating it, we're not going to make it work on-the-fly. Instead, you can simply ```.addClass( "ui-listview-inset ui-corner-all ui-shadow" )``` to the listview.
