### ISSUE TITLE
High Contrast Mode on Windows / IE

### ISSUE THREAD

**Issue by heiwen** [jquery/jquery-mobile#6123]
Set Microsoft Surface to High Contrast Mode by switching the theme in Control Panel\Appearance and Personalization\Personalization . Open http://jquerymobile.com/demos/1.3.0/ in Internet Explorer (in the modern UI). Notice that no icons are shown. There seem to be various recommendations around fixing this:

http://www.yaccessibilityblog.com/library/high-contrast-friendly-icons.html
http://msdn.microsoft.com/en-us/library/ie/hh771830(v=vs.85).aspx
http://www.w3.org/TR/wai-aria-practices/#accessiblewidget (12)

**Comment by jaspermdegroot** [comment]
@arschmitz @sfrisk

I suggest we close this ticket and open a new one for Windows/IE High Contrast Mode support in https://github.com/jquery/css-chassis. What do you think?

**Comment by sfrisk** [comment]
I agree, this is definitely a Chassis concern. I'll add an issue over there.

**Comment by arschmitz** [comment]
@sfrisk +1 i'm closing this.

**Comment by jaspermdegroot** [comment]
@sfrisk Thanks!

@arschmitz I think you missed the close button ;-)
