### ISSUE TITLE
Filterable: input label and ARIA attribute

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#6196]
For the new filterable widget we recommend people to add the ```input``` in their markup. However, it will be possible to have the framework generate this markup. In that case we should probably also add a ```label``` of which the text is configurable via an option. Default "Filter:"? Another thing to look into is if there is an ARIA attribute to associate the ```input``` with the widget that it is filtering.

**Comment by gabrielschulhof** [comment]
Actually, we've decided to deprecate the code for generating the input, so, I'm going to close this in favour of #7487.
