### ISSUE TITLE
Can not modify selectmenu properties.

### ISSUE THREAD

**Issue by Max-Might** [jquery/jquery-mobile#6202]
Hello.

I have tried to modify a selectmenu control but nothing changes visually.

Here is a very simple example: http://jsfiddle.net/WtsNb/1/

This one is with version 1.3 but the problem is present in 1.4 too.

Edit: updated the jsfiddle to show that the getter returns the new value after calling the setter.

**Comment by arschmitz** [comment]
Closing as a dup of #7412
