### ISSUE TITLE
Popup reposition method: 'origin' behaves like 'window'

### ISSUE THREAD

**Issue by globalmatt** [jquery/jquery-mobile#6205]
When using the popup reposition method, if you pass an options object containing positionTo: "origin" then the popup is actually centred in the window, as if positionTo: "window" had been passed. The expected result is that the popup is repositioned over the link that opened it (i.e. the origin).

Using "window" or a selector for positionTo appears to work correctly.

Test page: http://jsbin.com/ofuhaw/58/edit

Tested with 1.3.1 and latest, Mac Safari 6.0.5 & Mobile Safari (iOS 6.1).

**Comment by gabrielschulhof** [comment]
This, is currently expected behaviour, but see #5563 for possible future improvements.
