### ISSUE TITLE
Fixed Toolbar flckers on orientationchange when <meta name="apple-mobile-web-app-capable" content="yes" /> is set

### ISSUE THREAD

**Issue by jochenmanz** [jquery/jquery-mobile#6209]
Hallo,

if done a small test website with two fixed toobars. When adding the meta tag: <meta name="apple-mobile-web-app-capable" content="yes" /> and adding the site to the startscreen on my iphone4 (latest ios). On orientationchange the toolbars moves out of position and stay somewhere in the middle of the screen. If you are not at the top of the page. It only happens on larger pages, exceeding device-height.

Best Regards,
Jochen

**Comment by apsdehal** [comment]
Working fine with latest jqm and latest iOS on iPhone.
