### ISSUE TITLE
Listview: test Android 2.x fixed toolbar and list items with thumbs workaround

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#6273]
The fixed toolbar CSS contains this rule:
```
/* workarounds for other widgets */
.ui-android-2x-fixed .ui-li-has-thumb {
	-webkit-transform: translate3d(0,0,0);
}
```
We have to test if this is still needed with new listview markup. If so, we have to change the rule because ```ui-li-has-thumb``` has been deprecated.

**Comment by arschmitz** [comment]
We decided to no longer actively support 2.3 in the meeting today so this will stay until 1.6 and be removed
