### ISSUE TITLE
Why does $.mobile.maxTransitionWidth exist?

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-mobile#6301]
The docs don't say why you'd ever use it.

**Comment by jaspermdegroot** [comment]
Ticket https://github.com/jquery/jquery-mobile/issues/8130 shows a good use case.

API docs tickets https://github.com/jquery/api.jquerymobile.com/issues/154 and https://github.com/jquery/api.jquerymobile.com/issues/146 cover the documentation issue so I am closing this one.
