### ISSUE TITLE
Handling dependencies with RequireJS

### ISSUE THREAD

**Issue by davidmpaz** [jquery/jquery-mobile#6404]
Working recently with Backbone and RequireJS I did notice that when loading jQuery Mobile an error like this arose:

    Uncaught TypeError: Cannot set property 'mobile' of undefined

When loading jQuery Mobile the jQuery dependency was not yet met, even when requiring both modules, I did fix it declaring the dependency directly on jQuery Mobile when 'defining' it, since jQuery already define itself as a named module on line 16, for jQuery Mobile 1.3.2 stable, instead of:

    define( [ "" ], function ( $ ) { ......

I did: 

    define( [ "jquery" ], function ( $ ) {....

I wonder if this don’t brake anything else and if it is possible to add it to upstream for future releases, at least while jQuery continue defining itself with a module named "jquery" :)

Thanks for JQM and for your time
Cheers,
David

**Comment by gabrielschulhof** [comment]
I believe this is fixed since we now have js/ns.js which defines the mobile workspace under jQuery, and which also AMD-depends on jQuery. All other jQuery Mobile modules depend on js/ns.js to make sure the mobile namespace is defined.
