### ISSUE TITLE
Bug with Fastclick.js and the panel widget

### ISSUE THREAD

**Issue by vshjxyz** [jquery/jquery-mobile#6440]
Hello,
I'm building an app using jQuery Mobile and Fastclick.js, but I noticed a bug on the panel dismiss.

If you open the panel and you try to close it by clicking (or tapping) outside the panel body, you will be unable to close it (if Fastclick is on).

this is probably due because of an "error" here https://github.com/jquery/jquery-mobile/blob/master/js/widgets/panel.js#L90-99 where the dismission is performed listening to the "mousedown" event. 

Has anyone been into this?

I managed to create a jsbin example where you can see the problem

http://jsbin.com/IResuRo/16

**The bug appears only if you are browsing with a mobile phone or touch-enabled browser**

**Comment by kumquat0601** [comment]
@stereoscott , @kerwitz  Thanks! It works very well !!! it' s good workaround.
