### ISSUE TITLE
Popup issue with opened panel in android 4.0

### ISSUE THREAD

**Issue by lvil** [jquery/jquery-mobile#6455]
This is the same issue as here: https://github.com/jquery/jquery-mobile/issues/6044
Updated testing page: http://jsbin.com/otevuh/15
The change in testing is Popup with opened panel. 
Works fine (popup above the panel) except android 4.0 where the popup is cut.

**Comment by apsdehal** [comment]
no more an issue, works fine in 1.5-dev.
