### ISSUE TITLE
Fixed footer on wrong position while virtual keyboard is sliding up in IOS 7

### ISSUE THREAD

**Issue by PhilippSoehnlein** [jquery/jquery-mobile#6513]
This is probably a follow up to #4113.

If you have a fixed footer and there's something in the content that triggers a keyboard slideup, the position of the footer isn't always at the bottom while the keyboard slides up. If the position of the footer is then coincidentally over the input field that triggered the keyboard slideup the link of the main navigation will be executed.
Strangely this does only occur, if the jquery mobile page is running in fullscreen (home screen app or in a native app as webview).

How to reproduce:
* Grab an iPad or an iPhone with iOS 7 (I tested on an iPad 2 and on an iPhone 4S).
* Go to http://jsbin.com/ofuhaw/433/.
* Save as homescreen app.
* Start the homescreen app.
* Make sure the page is scrolled to top.
* Tap a textfield: On an iPad in landscape tap the textfield number 5, in portrait the problem appears with textfield 14. With an iPhone it can be reproduced by using textfield number 1 in landscape and textfield number 3 in portrait.
* If you tapped the left half of it, you're going to Google, on the right half you will see the Yahoo page next which are the links the navigation links point to.

In the current version of js/widgets/fixedToolbar.js there's an if condition on line 252:
``if ( screen.width < 1025 && $( e.target ).is( o.hideDuringFocus ) && !$( e.target ).closest( ".ui-header-fixed, .ui-footer-fixed" ).length )``
If I force this condition to be true, everything seems to work fine.

**Comment by apsdehal** [comment]
This has been fixed in 1.5-dev. http://jsbin.com/velunekeqa/2
