### ISSUE TITLE
Remove buttonMarkup

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#6568]
Also have a look at #6272, #5933 / #7230 (toolbar buttons are required to have all their classes in place a priori), https://github.com/jquery/jquery-mobile/pull/6252#issuecomment-22080524 (navbar-related) when we do this, even if those issues are closed.

**Comment by gabrielschulhof** [comment]
@arschmitz since you accomplished the removal on branch ui-1-12, you should add that it fixes this issue to one of the commits before landing the branch, right?

**Comment by jaspermdegroot** [comment]
We should also check which demos use ```buttonMarkup()``` and update them.
For example: http://demos.jquerymobile.com/1.4.5/controlgroup-dynamic/

**Comment by arschmitz** [comment]
@gabrielschulhof yes but @jaspermdegroot is correct any demos need to be updated first

**Comment by arschmitz** [comment]
This is already done closing
