### ISSUE TITLE
Select menu highlights default option when interrupted by hideRenderingClass under Chrome

### ISSUE THREAD

**Issue by GeoffColburn** [jquery/jquery-mobile#6611]
To Reproduce:
- http://jsbin.com/ofuhaw/626/edit under Chrome 32.0.1664.3 on desktop.

Breaking Behavior:
- Refresh test page.
- Open select menu and move mouse cursor over last option to highlight.
- After ~5 seconds the top option is highlighted.

Expected Behavior:
- Last option should still be highlighted.

So maybe check for the existence of the rendering class before removing it?

**Comment by gabrielschulhof** [comment]
I can no longer reproduce this when I try Chrome Version 40.0.2214.91 m on Windows 7.
