### ISSUE TITLE
Panel display: overlay breaks in FF 17 ESR & FF 24 & IE11

### ISSUE THREAD

**Issue by yvesdWork** [jquery/jquery-mobile#6638]
Hello guys,

I'm facing a problem I'm able to reproduce once in 4 tries, under Firefox 17.0.2 ESR (Windows XP), with jQuery Mobile 1.4.0 beta1 / jQuery 1.10.2. Update: also in FF 24 and IE11

1. Visit http://jsfiddle.net/k7mDE/ with FF 17.0.2 ESR
2. Make window and pane bigger, so you have lots of white space right of the link
3. To reproduce : click on the link (over the word "fast"), and then, very fast, move your pointer to the right as fast as you can

Expected : panel continues to open
Actual : Sometimes panel closes (with animation) WHILE expanding (weired), and sometimes panel break completely (have to reload the page).

I'll do other tests and keep you updated.

Yves Dessertine

**Comment by gabrielschulhof** [comment]
I can't reproduce this anymore. Please reopen or file a new issue if you're still experiencing this problem.
