### ISSUE TITLE
1.4.0 Beta 1: Tapping associated label for select with data-role="flipswitch" on iOS opens select wheel

### ISSUE THREAD

**Issue by burdeasa** [jquery/jquery-mobile#6661]
With jQuery Mobile 1.4.0 Beta 1 running on iOS 6.1.3 or iOS 7.0.3, use the new flipswitch widget by defining a select with a data-role of "flipswitch".  Also, include an associated label.

If you tap directly on the switch, the switch toggles as expected.  If you tap on the associated label, the switch toggles, but iOS also opens the select "wheel" with choices of "On" and "Off", as usually occurs with a native select.

As a test page, see the demo page at:
http://view.jquerymobile.com/1.4.0-beta.1/demos/flipswitch/
Be sure to try the demo entitled "Basic select switch" (the third demo on the page).

Note: This problem does not occur when using input type="checkbox" instead of select.

**Comment by gabrielschulhof** [comment]
This is still valid in iOS 6.1.2 with the latest code.

**Comment by gabrielschulhof** [comment]
Egads! Looks terrible on iOS 7 (iPhone 5S), at least with BrowserStack: https://www.youtube.com/watch?v=O9E_zDlnaOM
