### ISSUE TITLE
convertUrlToDataUrl: save one call to parseUrl

### ISSUE THREAD

**Issue by frequent** [jquery/jquery-mobile#6671]
In `convertUrlToDataUrl` , `path.isEmbeddedPage( u )` is called passing `u` which is the object created by `path.parseUrl(absUrl)`

Inside  `path.isEmbeddedPage` the passed object is parsed again through  `path.parseUrl()`, so it should be enough passing just `absUrl` and save one call to `parseUrl`.

**Comment by apsdehal** [comment]
Closing `$.mobile.path.isEmbeddedPage` is used at many other place than this one, so it may introduce bugs by considering this change.
