### ISSUE TITLE
Columntoggle table refresh ignores columns toggle state

### ISSUE THREAD

**Issue by ghost** [jquery/jquery-mobile#6673]
1. Description
When refreshing a "columntoggle table" the currently toggled columns state is ignored.

2. Test page
http://jsbin.com/ofuhaw/741/

3. Steps to reproduce
To start the page should be wide enough that column 3 is showing, and have the console ready.
Now hide column 3 using the "Columns..." menu
Call "addNewRow()" which will add a row and refresh the table.

4. Expected outcome
It should only show 3 columns, namely column 1,2 and 4.

5. Actual outcome
The new row and the header shows all 4 columns, while other/previous rows only show column 1,2 and 4.

6. Platforms/browsers and devices tested
Google Chrome Version 30.0.1599.101 m
Mozilla Firefox Version 24.0
both on a desktop running windows 7 Ultimate 32 bit

7. jQuery Mobile and jQuery core version used
jquery-1.10.1.js
jquery.mobile-1.4.0-alpha.2.css  /  jquery.mobile-git.js  (a few minutes before submiting this)

8. Other relevant information
May or may not be related to this bug https://github.com/jquery/jquery-mobile/issues/6683

**Comment by apsdehal** [comment]
No longer an issue with latest master.
