### ISSUE TITLE
.listview('refresh') iterates over entire list?

### ISSUE THREAD

**Issue by lightsurge** [jquery/jquery-mobile#6680]
I'm finding container.listview('refresh') does work over the entire list rather than just new (i.e. appended) items?

In my use case I'm regularly appending (via ajax) a small number (5) of items. In order to style the new items, the documentation advises me to call listview('refresh'). This starts fast, and then becomes exponentially slower.

Once my list reaches a length of 200 items, on my fastest testing device (Nexus 7), I'm waiting ~7 seconds for listview('refresh') to complete, during which my list is unusable, on my slowest device, I'm waiting >10 seconds.

Is this normal behaviour? I can see the use case for needing to check for changes to items, but in my case items never change, and all this work taking place every time the list is appended is obviously a complete waste of resources and renders the list unusable.

If it is normal behaviour, is there an alternative to listview('refresh'), like listview('appended'), that just selects the items after ".ui-last-item"? Currently I have a workaround where I put appended items into a hidden list, call .listview('refresh') on that, and then move the list items into my visible list.

**Comment by arschmitz** [comment]
@Ruffio the roadmap needs to be updated but listview re-write due to changing team amount of help and other things is going to be moved to 1.6 so adding that label

**Comment by arschmitz** [comment]
Moved this back to 1.5 we ended up getting to this as part of some other updates to listview

**Comment by gabrielschulhof** [comment]
Actually, this is already fixed in 1.4.5.
