### ISSUE TITLE
Filterable Widget - Select menu

### ISSUE THREAD

**Issue by Palestinian** [jquery/jquery-mobile#6682]
Hiding (`display: none`) selectmenu options `<option>` isn't supported by Safari Mobile browser. The code in the demo below was tested on iPhone 5 v7.0.3.

Demo: http://jsfiddle.net/Palestinian/s9StB/

I made a workaround by listening to `filterablebeforefilter` event and disable/enable options using `.prop( "disabled", true)` and removed `.ui-screen-hidden`.

**Comment by arschmitz** [comment]
@Ruffio @Palestinian This is just something thats not natively. This is really just a bad demo we should not demo something that is not actually supported while you can do disabled on them instead i'm not sure we should demo this at all. ill let others weigh in on if we should fix this by removing the demo completely or switching it to disabled.
