### ISSUE TITLE
page size issue with toolbar

### ISSUE THREAD

**Issue by pupvogel** [jquery/jquery-mobile#6712]
Hi,

this issue has been bothering me a while and can be seen quite nicely when opening the current GoogleMaps-demo on

http://view.jquerymobile.com/1.4.0-rc.1/dist/demos/map-geolocation

The content-div seems to report a wrong height to the GoogleMaps-API, so that the resulting map will NEVER fit into the visible area - the browser lets you scroll down to see the bottom of the map.
This was also true in earlier versions of jQM, so I always built in a calculation to set the height manually (subtracting the toolbar-height...) before connecting to GoogleMaps.

But isn't there a better way, can't jQM take care about this somehow ?

**Comment by apsdehal** [comment]
Closing as per #6758
