### ISSUE TITLE
External panel push: Content not displayed in Safari / iOS

### ISSUE THREAD

**Issue by denniedegroot** [jquery/jquery-mobile#6713]
When using push on an external page the content of the panel is not shown in Safari 7  and iOS 7.0.3 (maybe also older versions). When touching or hovering over the panel the content appears. I included 2 images to show the problem:

https://dl.dropboxusercontent.com/u/2640640/left-menu.png
https://dl.dropboxusercontent.com/u/2640640/right-menu.png

Test page: http://view.jquerymobile.com/1.4.0-rc.1/dist/demos/panel-external/

**Comment by apsdehal** [comment]
Closing not able to reproduce anymore with 1.5.
