### ISSUE TITLE
Page is not returning to the "top" state after "long" panel is closed in android 2.3.3 browser

### ISSUE THREAD

**Issue by polarfish** [jquery/jquery-mobile#6767]
### Issue description
Closing "long" panel returns the page to the "top" state on desktop browser and modern android versions. As for android 2.3.3 browser - after panel is closed user continue seeing empty space (because page was scrolled with panel) until he taps the screen.

### Test page
http://jsbin.com/IyeKuFuv/7/
### Steps to reproduce
Create page with a few elements and panel with a lot of elements. Open panel, scroll down to the bottom and close the panel.

### Expected outcome
After panel is closed, page "jumped up" to the top so user sees it's elements

![2013-11-27 15 12 33](https://f.cloud.github.com/assets/1070579/1631525/c983f54c-5766-11e3-8cf5-004fdf49f43a.png)

### Actual outcome
After panel is closed, nothing happens. But if user taps the screen - page jumps up and looks like in Expected Outcome case.
![2013-11-27 15 12 24](https://f.cloud.github.com/assets/1070579/1631526/c984e9f2-5766-11e3-8c88-d2a2e0722490.png)

### Platforms/browsers (including version) and devices tested
Chrome 31, Fedora 19
Chrome 31, Android 4.2.2, Samsung Galaxy Ace 3
Default browser, Android 2.3.3 emulator
### jQuery Mobile and jQuery core versions used
JQM - latest
JQ - 1.10.1

**Comment by jaspermdegroot** [comment]
I am going to reopen this ticket because I think we should discuss the desired behaviour first. Maybe there has been a discussion before and I missed it, in that case ... sorry.

I think we should only scroll to top after closing a panel if `ui-content` is out of view.

**Comment by jaspermdegroot** [comment]
As discussed during today's meeting we are going to change this so we only scroll to top after closing a panel if ui-content is out of view.
