### ISSUE TITLE
Issue with landscape view in Android ICS version 4.0.4

### ISSUE THREAD

**Issue by anandupadhyay** [jquery/jquery-mobile#6771]
I am building a mobile site with a background cover image and form fields in the footer.
When i view the page in portrait and landscape view it is working fine in iphone 4S OS version 6.0 but the landscape view is not working in Android ICS version 4.0.4. There is a  white space appearing at the bottom of the page even when i tilt the phone back to portrait view the white space at the bottom of the page remains and does not go away.
The image is also tiled up at the corners. The white space remains even after tilting the phone back to landscape and portrait position.
The phone (XOLO B700) that i am using is running Android v4.0.4 (Ice Cream Sandwich) OS.
Please take a look at the page http://jsbin.com/ofuhaw/998

**Comment by apsdehal** [comment]
Closing as fiddle is outdated. Kindly reopen with fixed fiddle.
