### ISSUE TITLE
Issue with pagecontainer (1.4) and changePage(1.3) method

### ISSUE THREAD

**Issue by hewerton** [jquery/jquery-mobile#6788]
When navigates repeatedly between pages using navigate function occurs a error. The previous page is load back. To see this erro follow this steps:

1 - access (changePage -1.3 - http://jsbin.com/ofuhaw/1023/edit?html,js,output) or (pagecontainer - 1.4 - http://jsbin.com/ofuhaw/1025/edit?html,js,output)
2 - click on "go to page 1"
3 - click on "home"
4 - click on "go to page 1"
5 - click on "home"
6 - click on "go to page 1"
7 - click on "home"

The last click on "home" link will load back page 1.

**Comment by gabrielschulhof** [comment]
You should not use the navigate() function directly. Use 
```JS
$.mobile.pageContainer.pagecontainer( "change", url, options );
```

**Comment by gabrielschulhof** [comment]
Oh, NM. You *were* using pagecontainer change() ...

**Comment by gabrielschulhof** [comment]
Like @Palestinian said, you should definitely not attach handlers in response to an event that can fire multiple times. You can actually use pagecreate as well.
