### ISSUE TITLE
Suggestion: Add a 'flag for deprecated code' global option allowing for easier upgrade

### ISSUE THREAD

**Issue by Ruffio** [jquery/jquery-mobile#6846]
I just an idea. When upgrading from one version to another often methods, default values etc. are changed to align code/wording. As applications gets bigger and bigger it can often be difficult/time consuming to analyse which code is now deprecated. My suggestion is that if a global value 'flagForDepricatedCode' is set true, then every time deprecated code (only from previous version) is executed in browser, then a message is written to console which deprecated code was reached. That would allow developers to easy 'take a walk around the application' and get a (complete) list of deprecated/soon to be deprecated code that needs attention.

I know it's a wild shot, so no hard feelings if the idea isn't implemented :-)

**Comment by arschmitz** [comment]
So we actually have done this already in 1.5 but just found this issue. all backcompat code is now in its own modules and can also be disabled by setting $.mobileBackcompat = false before jQuery mobile is loaded. Im going to close this as fixed.
