### ISSUE TITLE
Either a bug or pagebeforechange docs are incorrect

### ISSUE THREAD

**Issue by srgstm** [jquery/jquery-mobile#6899]
http://api.jquerymobile.com/pagebeforechange/ says:

*Triggered twice during the page change cycle:*
- *When received with data.toPage set to a string, the event indicates that navigation is about to commence.*

- *When received with data.toPage set to a jQuery object, the event indicates that the destination page has been loaded and navigation will continue.*

However, when calling pagecontainer("change") not with a URL but a jQuery object, both times the event fires with data.toPage set to a jQuery object.

A test page: http://jsbin.com/ivoCuXe/11/edit
Open the console to see the logs.

Also note that when the test page is loaded initially, the pagebeforechange event is called both times with an object. However, if you load the same page with a hash ( http://jsbin.com/ivoCuXe/11#first ) the first event will be with a URL.

**Comment by gabrielschulhof** [comment]
I've moved this issue to the API docs.
