### ISSUE TITLE
Create real unit tests

### ISSUE THREAD

**Issue by gseguin** [jquery/jquery-mobile#6905]
As of today our unit tests are still relying on the DOM, have a lot of dependencies and require some kind of initialization of other widgets. I would like to move all these into the integration tests and create real unit tests that will just test how a each function behaves outside of the "system".

SinonJS would allow us to mock the parts of the system we're not testing and really isolate the function we're testing.

Also these tests should not have timing issues like our current ones and would execute much faster than our current "unit" tests.

**Comment by apsdehal** [comment]
Closing as discussed with @arschmitz. We plan to move on with our current structure of unit tests.
