### ISSUE TITLE
Bug: Selector instead of its children() is deleted when .empty() is called as a text input is one of the selector's children.

### ISSUE THREAD

**Issue by jessemao** [jquery/jquery-mobile#6924]
Hi, I have run into an issue with JQM 1.4.0 that when I use $('selector').empty() to clear its children, this function removed the selector instead of the children. Please see the attached image below. 

The DOM, 
![image](https://f.cloud.github.com/assets/1606623/1895812/713a131e-7b63-11e3-94bd-7d1928d9d9a2.png)

then I called $('#dbconnection-query-parameters').empty()
![image](https://f.cloud.github.com/assets/1606623/1895820/9f9f102e-7b63-11e3-90a1-a250fc446737.png)

this is what I have got. 

I have tried on some other elements as well and keep getting this issue. Please let me know if I am doing something wrong or there is some solution for it! 

Thank you!

Bests,

Jingxian

**Comment by apsdehal** [comment]
Not an issue with JQM but with jQuery, kindly refer the document for proper use and head over to irc for fixing it.
