### ISSUE TITLE
Slow transition in pages and panels in jQuery Mobile 1.4 and Android

### ISSUE THREAD

**Issue by RdlP** [jquery/jquery-mobile#6934]
Hello,

I was trying yesterday to develop a app with jQuery Mobile and Apache Cordova (3.3) to Android (2.2 and 4.0). The app is very simple, a main page with push panel and link to other page.

When I probed it, I noted that transitions were very slow. so how can i fix that?

Thanks

**Comment by apsdehal** [comment]
This is a very old issue and I justed tested in Cordova and performance is satisfactory.
