### ISSUE TITLE
widget pagecontainer, option reload in conflict with deprecated

### ISSUE THREAD

**Issue by DColl** [jquery/jquery-mobile#7066]
https://github.com/jquery/jquery-mobile/blob/abc97542dd55aef1c906d6cb3be07bc9c1720fce/js/widgets/pagecontainer.js#L607

The options "reload" for method "load" & "change", which is supposed to replace "reloadPage" is currently not used by the API. Check the link, only "reloadPage" is used to set ```settings.reload```

Actually, the fix to that is to use ```$('body').pagecontainer( "load|change", redirectUrl , { reload: true, reloadPage: true} );```

**Comment by apsdehal** [comment]
Fixed in 1.5-dev.
