### ISSUE TITLE
hoverDelay setting doesn't do anything

### ISSUE THREAD

**Issue by globalmatt** [jquery/jquery-mobile#7107]
```buttonMarkup.hoverDelay``` is documented at http://api.jquerymobile.com/global-config/ and it used to perform as documented in jQuery Mobile 1.3. However, in 1.4 it has no effect. The only place ```hoverDelay``` appears in the 1.4 code is:

		buttonMarkup: {
			hoverDelay: 200
		},

So I guess either the code that uses ```hoverDelay``` needs to be added back in, or the setting needs to be removed entirely (and the API docs updated accordingly).

On a related note: The API docs mention that ```buttonMarkup.hoverDelay``` is deprecated and recommend using ```$.mobile.hoverDelay``` instead. However ```$.mobile.hoverDelay``` isn't in the code at all, and therefore obviously doesn't do anything either.

**Comment by Ajaxy** [comment]
Guys, how is it working now?

**Comment by arschmitz** [comment]
@globalmatt @Ajaxy This should have been removed in 1.4 its actually not possible for this to work anymore. In 1.3 we used javascript to add hover classes and this allowed for a delay. In 1.4 this is all css with `:hover`. There is no way to set a hover delay in css so this simply is not possible anymore. 

I'm going to close this and open an issue to remove this from the api docs.

**Comment by Ajaxy** [comment]
Why did you decide to deal with `:hover` instead of managing it by JS?

There are bugs with `:hover` on iOS btw: https://github.com/jquery/jquery-mobile/issues/7740
