### ISSUE TITLE
Jquery mobile and google Map

### ISSUE THREAD

**Issue by gfr1991** [jquery/jquery-mobile#7120]
Hi there,
there's a problem with the jquery mobile map page of the demo; obviously I can't implement this feature in my website. I'm using the same code you can find here http://demos.jquerymobile.com/1.4.1/map-list-toggle/#map-page . If you try to click on any element of the "list" tab, you'll see that it doesn't work. It's impossible to open any of the link on the "list" tab directly on the map, that it's what I want to (and I guess the page was realized to). Anyone can help me? Let me know if you need further information. Lookin' in the code, as you can see, in the list the element are linked with<a href="#">, but it seems not working at all. Only one element (the third one) is linked in a different way (the href point to details.html?locationId=4719, but that file is not present on the server so it doesn't work too.

**Comment by gocheer** [comment]
The Demo pages are pretty worthless if you can't get them to work in a jQuery Mobile 1.4.5 page. If I had written the jQuery Mobile demos I would have setup stand alone ZIP files FOR EACH DEMO. It's easier to rip apart A WORKING DEMO than to copy code that doesn't work and try to get it to work. Too bad no one has responded to this simple request.

**Comment by apsdehal** [comment]
Closing in favor of #7570.
