### ISSUE TITLE
iPad 1 (iOs 5_1_1) crash on multiple select

### ISSUE THREAD

**Issue by cherouvim** [jquery/jquery-mobile#7216]
Crashes consistently when selecting an option from a multiselect using either:
```
Mozilla/5.0 (iPad; CPU OS 5_1_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B206 Safari/7534.48.3
```

or when packaged as a phonegap app.

Simplest HTML which reproduces problem is: http://pastebin.com/raw.php?i=jts55DxU
Live demo at: http://jsfiddle.net/jXW4x/embedded/result/

I confirm this with jqm 1.3.2 and 1.4.2 using simplest code possible with correct jquery version from jqm demos.

The crash doesn't happen if I remove the jqm script (and leaving just jquery) from the source. Which means that this is not just an HTML element bug with my ipad.

**Comment by arschmitz** [comment]
Im going to close this it was decided to no longer support ios older then 7 in the upcoming 1.5 version.
