### ISSUE TITLE
Navigating a form with keyboard breaks on select

### ISSUE THREAD

**Issue by jondmoon** [jquery/jquery-mobile#7219]
If you use tab while moving through a form and then come to a select box and press either an up/down arrow key or a letter to jump to an option, the select loses focus and you can't do anything. Pressing tab goes back to the beginning of the page. This was not broken in 1.3.1 (which is what I am trying to upgrade from to 1.4.2).

Test Page: The jQueryMobile Demos Form Gallery page

Works correctly in Firefox 27/28 and Safari 5.1, but not in Chrome 28+ (I didn't test older versions), IE9/10, or Opera. I testing in a combination of Windows 7 and Windows 8 virtual machines (through browserstack).

**Comment by apsdehal** [comment]
Working fine on 1.5 and latest. Closing.
