### ISSUE TITLE
Feature Request: Add automation testing support (New approach)

### ISSUE THREAD

**Issue by lastboy** [jquery/jquery-mobile#7241]
We (http://catjsteam.github.io) have created a new approach for adding automation testing as part of the application source code using annotation within comments.

You can see how we add UI tests for the JQM KitchenSink in here http://catjsteam.github.io/examples/jqm/index.html

We can integrate our technology with JQM development lifecycle (internal testing for the  KitchenSink) and\or give it to the developers as a daily based development tool.

**Comment by apsdehal** [comment]
No plans to shift on this till intern integration.

**Comment by lastboy** [comment]
Haha... After 2 years... You came back with your answer. Hmmm you are agile alright.
