### ISSUE TITLE
Page pushed too far when panel is open (reveal or push) on MS Surface Pro 

### ISSUE THREAD

**Issue by agcolom** [jquery/jquery-mobile#7245]
On the Microsoft Surface Pro2, running Windows 8.1, the page is pushed too far when the panel is open with reveal or push options. Happens on both right and left panels. This leaves a gap between the page and the panel. 
![panelbug](https://f.cloud.github.com/assets/688413/2422585/ded525f6-ab8f-11e3-9290-bbd577ce8852.png)

**Comment by apsdehal** [comment]
Not able to reproduce on 1.5
