### ISSUE TITLE
White bar appear above the tab bar after keyboard is close for iPhone with IOS 7.1

### ISSUE THREAD

**Issue by SengHin** [jquery/jquery-mobile#7262]
Hello,
I am building an app with jquery mobile. After upgrading to IOS 7.1, I notice that there is a white bar displayed whenever I hide the soft-keyboard. Need help on this issue.

Thanks.

**Comment by apsdehal** [comment]
Kindly provide a fiddle for the issue. Template: http://jsbin.com/huvoraba/1/edit?html,output. Closing till then.
