### ISSUE TITLE
Scrolling up and down in Chrome Browser in Android popup disappear for few seconds

### ISSUE THREAD

**Issue by akshays-iprogrammer** [jquery/jquery-mobile#7272]
I am using jquery mobile popup in my site. When popup opens with chrome in android device popup behavior slightly changed. Scrolling up and down with popup open, popup disappear for few seconds and comes again. In other browsers it work great only chrome have this problem. It work fine with iOS too. I am working on this problem with long time but not getting any solution. I am using jquery.mobile-1.4.2.js file.

Here is the demo page.
http://demos.jquerymobile.com/1.4.2/popup/

Steps to reproduce
Open the given demo link on Android device on Chrome browser and find sign In button, now click on sign in button and login box popup will open, now scroll up and down opened popup in chrome browser and look carefully, popup will disappear for few seconds and again appear.

Expected outcome
Popup should not disappear in chrome on android while scrolling like other browsers (default)

Actual outcome
Popup getting disappear while scrolling for few seconds in Chrome on Android device

Platforms/browsers (including version) and devices tested
Tested and working on iOS and android on all browsers and working fine except chrome on android for all version.

jQuery.mobile-1.4.2 Used

**Comment by apsdehal** [comment]
Not able to reproduce as of now. @gabrielschulhof If you are able to reproduce kindly reopen.

**Comment by Maltm** [comment]
is there a workaround for this? so that it doesn't disappear?
