### ISSUE TITLE
Decrease in performance in v.1.4.2. with mobile medium / low

### ISSUE THREAD

**Issue by Diegalex** [jquery/jquery-mobile#7273]
Hi!

I'm working with Phonegap and comming from jQuery Mobile 1.3.2. the performance of transitions and effects are really good on medium - low devices. My device of tests is a Samsung Young.

But today I have tested with 1.4.2. on the same device and the transitions on multiple-pages templates are slow giving me a white page during 0,5 sec. I insist that using 1.3.2. worked well. The same with fadeOuts. This transition isn't progressive. It's instant. 

I thought that it could be problem of Phonegap but I also tried on a Nexus 10 but It worked well. So, I think that 1.4.2. could be slow in medium-low end devices. 

My test work is the demo that is located on demo section: http://demos.jquerymobile.com/1.4.2/pages-multi-page/index.html

I have copied this code to my PC and have created a custom Phonegap project. 

Thanks.

**Comment by apsdehal** [comment]
Closing, kindly look into contribution guidelines and provide a specific fiddle that shows performance difference, I am not able to produce anything as of now with specific demo mentioned.

**Comment by apsdehal** [comment]
It would be even better if some performance benchmarks can be provided to justify your claims.
