### ISSUE TITLE
Panel: Difficulties and flashing when opening

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#7326]
http://jsbin.com/IFolanOW/400
http://jsbin.com/IFolanOW/401
http://tinypic.com/player.php?v=28ipb2d&s=8#.U0-GpznukzY
http://tinypic.com/player.php?v=mbqv13&s=8#.U0-RkjnukzY
http://tinypic.com/player.php?v=2ci9tnn&s=8#.U0-RyTnukzY
Android 4.0.4
Motorola RAZR XT885
Reproduced in the emulator with 4.0.3.

**Comment by apsdehal** [comment]
No longer an issue it seems, @gabrielschulhof if you are able to reproduce kindly reopen.
