### ISSUE TITLE
Base: dynamicBaseEnabled does not seem to work

### ISSUE THREAD

**Issue by frequent** [jquery/jquery-mobile#7331]
JSBIN:   [here](http://jsbin.com/ofuhaw/1342)

According to the docs, setting `dynamicBaseEnabled: false` will not make JQM handle the base tag. 

From the JQM source code, I would expect this option to not insert an unwanted base. But if you check the JSBIN, the base tag is injected, although the option is set.

Upon looking further, it boils down to why is the `<base>` tag inserted when the user wants to manage it?

**Comment by gabrielschulhof** [comment]
I think the base tag is inserted, but it is not updated. I will nevertheless make the insertion of a base tag contingent upon the presence of ```dynamicBaseEnabled```.

**Comment by frequent** [comment]
@gabrielschulhof: Cool. Thanks a lot! And happy new year!
