### ISSUE TITLE
Navbar Review

### ISSUE THREAD

**Issue by cgack** [jquery/jquery-mobile#7359]
# Navbar Review

## Description

A jQuery Mobile Widget that creates a row (bar) of buttons. The buttons are created from an unordered list of links wrapped in a container element with `data-role=”navbar”`. The buttons can contain text, icons, or text + icon. 

## Functional Specification

Navbar should extend the full available width of the viewport with a maximum number of buttons which, once reached, will: 
- "smart" stack the buttons. Not just in `n` rows of 2 columns, but in `n` rows of the maxbutton columns and then evenly distribute the remainder
- if the `morebutton` option is set to true - trigger display of a "viewmore" button to indicate there are more buttons available. When "viewmore" is selected the remaining buttons will become visible in a popup. This `morebutton` functionality will be an extension to the navbar widget

## Responsive Design Considerations

* Ensure that the navbar adapts to various viewport sizes 
* possibly ensure that the default max number of buttons responds to relative screen size (i.e. 5 buttons for small/medium , 8 for larger layouts)
* demo to highlight the ability to alter `maxbuttons` on `throttledresize`

## Accessibility Considerations

Ensure that the navbar receives the `role="navigation"` attribute - [spec](http://www.w3.org/TR/wai-aria/roles#navigation)

### Options

* iconpos 
  * _sets the position of the icons_
  * default: top
* maxbuttons
  * _sets the maximum number of buttons for the screen, i.e. 8 means each button takes 1/8th of the width_
  * default: 5

**morebutton extension**
* morebutton
  * _tells the widget to use the view more extension functionality and button_
  * default: false
* morebuttontext
  * _sets the text of the more button_
  * default: "..."
* morebuttoniconpos
  * _sets the location of the optional icon on the more button_
  * default: "top"
* morebuttonicon
  * _sets the icon to be used for the more button_
  * default: null

### Events

* create _triggered when a navbar is created_
  ```
 
  $( ".selector" ).on("navbarcreate", function(event, ui) {});
  
  $( ".selector" ).navbar({
    create: function(event, ui) { }
  });
  ```

### Methods
* destroy _removes navbar enhancements from the element_
  ```
  $( ".selector" ).navbar( "destroy" );
  ```

* refresh _refreshes the navbar_
```
$( ".selector" ).navbar( "refresh" );
```
### Initial Markup
```
<div class="selector" data-role="navbar" >
  <ul>
    <li><a href="#" class="ui-btn-active">Item 1</a></li>
      <li><a href="#">Item 2</a></li>
  </ul>
</div>
```
### Enhanced Markup
```
<div role="navigation" class="selector ui-navbar" data-role="navbar">
  <ul class="ui-navbar-bar">
    <li class="ui-navbar-baritem"><a class="ui-link ui-btn ui-btn-active" href="#">Item 1</a></li>
    <li class="ui-navbar-baritem"><a class="ui-link ui-btn" href="#">Item 2</a></li>
  </ul>
</div>
```
CSS
```
.ui-navbar {
 max-width: 100%
}

.ui-navbar ul {
  padding: 0;
  display: table; 
  table-layout:fixed; 
  width: 100%;  
}

.ui-navbar li{
  display: table-cell;
  width: 100%;
}
```
# Checklist 

* [ ] Widget avoids using ```document``` and ```window``` directly - uses ```this.document``` and ```this.window```
* [ ] Demos page
* [ ] Demos page added to menu
* [ ] Api PR # 
* [ ] update /js/index.php
* [ ] update /js/jquery.mobile.js
* [ ] check with download builder
* [ ] Full test coverage
* [ ] Device Testing
* [ ] Screen reader testing
* [ ] Full accessibility review by expert
* [ ] add instructions to the upgrade guide

**Comment by cgack** [comment]
tracking #7909 here to make sure that a navbar without links either works or throws an proper error

**Comment by caoliuxue** [comment]
I'm using navbar widget under JQM 1.4.5, but I get the error 
"no such method 'refresh' for navbar widget instance"
 when I tried to refresh the icon of my navbar, is this an already known bug?

**Comment by arschmitz** [comment]
@caoliuxue the nav bar widget does not have a refresh method please see http://api.jquerymobile.com/navbar/ this issue is an in-progress re-write for 1.5.0
