### ISSUE TITLE
External panels cut off with long content - visible on demo page

### ISSUE THREAD

**Issue by jawinn** [jquery/jquery-mobile#7364]
I just noticed this in my app and was able to reproduce on the demo page; add longer content to the external panel demo page, and the panel cuts off at the bottom:
http://demos.jquerymobile.com/1.4.2/panel-external/
Viewing in the latest Firefox.

![fireshot screen capture 006 - external panels - demos_jquerymobile_com_1_4_2_panel-external](https://cloud.githubusercontent.com/assets/965114/2874669/da441f5e-d3f5-11e3-84ba-0d420137d7b9.jpg)

**Comment by apsdehal** [comment]
Not able to reproduce in latest firefox using the given fiddle. Works as expected.
