### ISSUE TITLE
Feature request: Scroll instead of tap to toggle fixed toolbars

### ISSUE THREAD

**Issue by frankie-loves-jesus** [jquery/jquery-mobile#7433]
http://usabilitypost.com/2014/05/24/the-scroll-up-bar/

http://wicky.nillia.ms/headroom.js/

> A design pattern that is currently growing more popular is the fixed position bar at the top of the page. Sometimes the bar stays the same throughout, sometimes the header morphs into a slimmer bar as you scroll down, sometimes a completely new bar appears.
>
> While these bars may be useful, they take up vertical space, reducing the reading space the user has chosen for themselves by picking the size of their browser window. Additionally, information displayed on these bars does not do anything to aid the reading of the actual content, making the bar more of a nuisance than help.
> 
> An interesting way to solve the issue is to hide the bar when scrolling down, and show it when scrolling up. On mobile interfaces, where space is precious, this technique is used to hide chrome, such as Web browser controls, but it’s also a good pattern to use on the Web. For example, Medium has just updated their new navigation bar. As you scroll down, the bar goes away, but it can be revealed at any time by scrolling up.

**Comment by apsdehal** [comment]
Closing as no active discussion on the implementation.
