### ISSUE TITLE
checkboxradio: add CSS when using <legend> with a checkbox/label

### ISSUE THREAD

**Issue by frequent** [jquery/jquery-mobile#7453]
When doing a form, it's nice to align labels and inputs as JQM does. However when the form includes a checkbox the logic breaks, because the checkboxradio widget needs the `<label>` element for the ui.

See [here](http://jsbin.com/ofuhaw/1426/edit)

This can be fixed by using a `fieldset/legend` with the checkbox, but the `legend` element is missing the CSS analogue to the label:

See [here](http://jsbin.com/ofuhaw/1427/edit) 

which can be fixed by including legends in the respective label CSS. 

See [here](http://jsbin.com/ofuhaw/1428/edit)

If I'm misuing `legend` please close and I will keep custom overwriting. Otherwise would be nice to have out of the box.

**Comment by arschmitz** [comment]
So we have had a lot of discussion about this and the new widget in jQuery UI and the decision is that this is OK though we will also be supporting the use of multiple labels so that it can still be toggled via label if you like or not via using a legend.

**Comment by frequent** [comment]
Cool. Thanks a lot. And sorry for not being so active for the last .... eternity or such. Just too much other stuff going on but I'm trying to read along and keep up to date.

**Comment by arschmitz** [comment]
@frequent I did a PR for it already so this will be in 1.5 Sorry it took so long we went through several rounds of consultation trying to get a real answer on this.

No worries help is always welcome when you have time :-)
