### ISSUE TITLE
Panel Scrolls to Top on iOS Chrome after title bar is hidden/shown

### ISSUE THREAD

**Issue by AdamDougherty** [jquery/jquery-mobile#7529]
1. Using Chrome on iOS visit: http://demos.jquerymobile.com/1.4.2/panel/ 
2. Open the panel and scroll down to hide the titlebar.
3. Panel should scroll back up to the top (undesired behavior)

This is particularly annoying on sites that have long panels (e.g. panels with listviews)

Doesn't appear to be an issue on Safari. 
Have not been able to verify if its an issue on Android Chrome or other browsers.

The issue is caused by a non-literal check on scrollToTop inside of the _positionPanel method.

Changing:  if ( scrollToTop ) {
                        this.window[ 0 ].scrollTo( 0, $.mobile.defaultHomeScroll );
                    }

To:  if ( scrollToTop === true ) {
                        this.window[ 0 ].scrollTo( 0, $.mobile.defaultHomeScroll );
                    }

Fixes the issue as as _bindFixListener feeds an event object as the scrollToTop argument causing a non-literal check of scrollToTop to pass.

**Comment by apsdehal** [comment]
Not an issue with latest jqm, if persists, kindly reopen.
