### ISSUE TITLE
taphold also being initiated by "swipe" 

### ISSUE THREAD

**Issue by Bmint910** [jquery/jquery-mobile#7555]
I have found that the taphold (longclick) function for jquery mobile also seems to cause elements to change the same way by "swiping" as well.

A quick proof of this undesired effect is:
http://api.jquerymobile.com/taphold/

If I "swipe" the box well before 750ms it changes color and it bypasses me having to do a taphold (longclick).

also see:
http://stackoverflow.com/questions/24542481/how-to-disable-swipe-for-taphold
comment from stackoverflow: 
"taphold has no vertical/horizontal distance threshold"

Note: "swipe" is in quotes but it is not a true swipe just taphold without thresholds as verified by stackoverflow comment and source code

**Comment by arschmitz** [comment]
We decided to adopt hammer.js to replace our current touch events and pep to replace vmouse so im going to close this as a feature request and we will not be adding anything new to the old implementations.
