### ISSUE TITLE
Panel with content taller than page causes scroll position to jump up when resizing screen or scrolling on mobile.

### ISSUE THREAD

**Issue by bessiambre** [jquery/jquery-mobile#7572]
1. Open panel with tall content
2. Scroll down past the page content.
3. Resize browser window. 

The scroll position jumps up (probably to the top).

http://jsbin.com/lekok/1/edit

This is particularly bad on mobile (tested on android chrome) because scrolling up and down shows and hides the address bar which triggers resize events and makes scroll position jump.

I initially though this had the same root cause as issue
https://github.com/jquery/jquery-mobile/issues/7529 . However, it seems the suggested fix is not enough to solve the problem because it also happens when setting page.css min-height in resetActivePageHeight() which is triggered on resize.

**Comment by gabrielschulhof** [comment]
Interestingly, this is no longer reproducible if you reference jQuery Mobile git from the CDN, but it is reproducible if you reference jQuery Mobile from js/index.php ... the inclusion order must be influencing things.

**Comment by gabrielschulhof** [comment]
... or, rather, the lack of inclusion of events.js (which pulls throttledresize into the build), as I found out in #7925 ...
