### ISSUE TITLE
JQM conflicts with Jquery .ajax on Windows Phone 8/8.1

### ISSUE THREAD

**Issue by 3rror404** [jquery/jquery-mobile#7576]
I'm having some weird issue with Jquery's .ajax and .get on Windows Phone 8 and 8.1 in a Phonegap app that uses JQuery Mobile.

The following works on iOS and Android but fails silently on WP8.

    $.ajax({
        url: updateurl,
        type: "GET",
        dataType: "json"
    })
    .done(function (data) {
        alert("Done")
    })
    .fail(function () {
        alert("error");
    })
    .always(function () {
        alert("complete");
    });

The .get equivalent fails similarly.

The server responds with a 200 so I know the request is being sent but _none_ of the callbacks ever fire.

Removing JQuery Mobile fixes the issue hence why I am posting this here.

Currently using Phonegap 3.5.0, JQuery 1.11.1, JQM 1.4.3

Also tested JQuery 1.7.2, JQM 1.3.2. Same issue.

I have a test page here (http://jsbin.com/yacidudi/1/edit), though I'm not sure how much use it is as the issue doesn't exist in a browser.

**Comment by jnrepo** [comment]
I'm having similar problems as well; Is there a workaround for this error?

**Comment by apsdehal** [comment]
This is subpart of #6574. Closing in favor of it.
