### ISSUE TITLE
Active state gets removed from persistent navbar after page transition

### ISSUE THREAD

**Issue by intermedi8** [jquery/jquery-mobile#7583]
In JQM 1.4.3 its not possible to set the active state of an persistent navbar. 
The ui-btn-active class automatically gets removed after the show-event. Due to this, theres only an ugly workaround by using a setTimeout function, re-adding the class with some delay.

This bug can also be seen in the official demo:
http://demos.jquerymobile.com/1.4.3/toolbar-fixed-persistent/

**Comment by apsdehal** [comment]
Fixed in 1.5.
