### ISSUE TITLE
Fixed Toolbar: Header positioning fails after orientationchange in fullscreen mode

### ISSUE THREAD

**Issue by weases** [jquery/jquery-mobile#7593]
When using a fixed header toolbar in fullscreen mode, the header is positioned incorrectly after changing the orientation from portrait mode to landscape mode and back.
Tested with iPhone 4 (iOS 7.0) and iPhone 5s (iOS 7.1.2).

**What's fullscreen mode?**
-Adding this to the header
```JavaScript
<meta name="apple-mobile-web-app-capable" content="yes">
```
-Open the page from a bookmark on the homescreen

**Test Page**
http://jsbin.com/pimuduru/1/edit

**Steps to reproduce**
1. Open the test page from a bookmark on the device's homescreen.
2. Scroll down a little bit.
3. Change orientation to landscape mode and then back to portrait mode.

**Expected outcome**
Header should be positioned on top of visible page.

**Actual outcome**
Header is positioned inside the content.

**Comment by apsdehal** [comment]
This is fixed and no longer an issue. Closing.
