### ISSUE TITLE
Feature Request: Generic "clear" button on textinput widget and allow to use other elements than <a> links

### ISSUE THREAD

**Issue by frequent** [jquery/jquery-mobile#7601]
I remember reading about this on the IRC channel some time ago and since I stumbled over it today, I thought I'd post an issue/feature request

It would be nice to have a more generic "action" button available on textinputs = it can be a clear-button but must not always be. Also, it would be nice, if both `<a>` and `<input>` buttons would be possible, like here (form with search field and submit button):

http://jsbin.com/ofuhaw/1494/edit

So, "action" vs "clear" and `<a>` or `<input>`.

**Comment by arschmitz** [comment]
Im going to close this we will address it when we write the new textinput widget for UI.
