### ISSUE TITLE
ajaxEnabled = false breaks buttons ui-btn-active state

### ISSUE THREAD

**Issue by szegheo** [jquery/jquery-mobile#7607]
Button widget will not get "ui-btn-active" when pressed and $.mobile.ajaxEnabled is set to false.
http://jsbin.com/huvoraba/66/edit?html,output

**Comment by apsdehal** [comment]
This feature is specifically a part of navigation which in case of non ajax requests add ui-btn-active class to aid the user from not clicking twice on the link. Rest in the case when ajaxEnabled is false or form is nonAjax it behaves like a normal button should, you can refer to examples of bootstrap, ui and normal button.
