### ISSUE TITLE
JQM 1.4.3 Remote autocomplete demo does not work with iPhone Go button

### ISSUE THREAD

**Issue by ImpactDirectories** [jquery/jquery-mobile#7631]
The go button on iPhone does not work with the remote autocomplete demo for JQM 1.4.3 like it does for 1.3.2

Links
1.4.3 demo http://demos.jquerymobile.com/1.4.3/listview-autocomplete-remote/    
1.3.2 demo  http://demos.jquerymobile.com/1.3.2/widgets/autocomplete/autocomplete-remote.html

**Comment by apsdehal** [comment]
Working as expected.
