### ISSUE TITLE
Transition offset if data-role="page" has a parent div

### ISSUE THREAD

**Issue by ganchenkor** [jquery/jquery-mobile#7654]
if viewport class is not on the body because `data-role="page"` has a parent `div`.
it offsets whole screen while making a transition. here is jsfiddle for this one: http://jsfiddle.net/25c3ykjn/2/
it can only work correctly if the parent is `body` tag like here:
http://jsfiddle.net/25c3ykjn/3/ I think it's because initialized and assigns those 2 classes on body tag
`ui-mobile-viewport ui-overlay-a` but if it assigned on parent div, it makes this bug

Addition:
http://jsfiddle.net/1ykn7c5a/1/
in this fiddle, on transitioning the page footer, moves up and down :-(

**Dirty FIX**
```javascript
$('#parentDiv').removeClass('ui-mobile-viewport ui-overlay-a');
$('body').addClass('ui-mobile-viewport ui-overlay-a');
```
**OR**
I just simply add to my body tag those 2 classses:
```html
<body class="ui-mobile-viewport ui-overlay-a">
```
It works fine after that, but I see now I have 2 ui-mobile-viewport if I don't clean it up manually. Is this will be OK? Or Should I also clean it up from the parent div?
[Fiddle Fix with DOM manupulation](http://jsfiddle.net/25c3ykjn/4/) 
[Fiddle Fix with assigning manually to body class and having parent div also with viewport class](http://jsfiddle.net/25c3ykjn/8/)

**Comment by apsdehal** [comment]
Not able to reproduce it anymore with latest jqm, if issue persists kindly reopen.
