### ISSUE TITLE
Icons: Revert to spans

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#7664]
WIP branch: https://github.com/jquery/jquery-mobile/tree/1.5-button-css-and-demos

Before moving on we need to merge the new button/checkboxradio/controlgroup branch and the navbar rewrite branch, and remove the deprecated buttonMarkup.js to prevent working on updating on CSS and demos that will be replaced.

**Comment by arschmitz** [comment]
Fixed on 1.5
