### ISSUE TITLE
Incorrect border radius for buttons in first/last <li> of listviews

### ISSUE THREAD

**Issue by jhogervorst** [jquery/jquery-mobile#7670]
## Issue description

The border radius for button within the first/last `<li>` of a listview is incorrect. This seems to be an undesirable effect of a CSS rule.

## Test page

http://jsbin.com/huvoraba/121/edit?html,output

## Steps to reproduce

Place a button with rounded corners within the first or last `<li>` of a listview.

## Expected outcome

The button has four equally rounded corners.

## Actual outcome

Two of the button's corners are less rounded than expected.

## Platforms/browsers and devices tested

N/A, but to be complete: Safari 7.0.6 (9537.78.2) on Mac OS X 10.9.4 (13E28).

## jQuery Mobile and jQuery core version used

jQuery Mobile: latest (from Git)
jQuery core: 1.11.1

## Other relevant information

The problem is caused by [these two](https://github.com/jquery/jquery-mobile/blob/cb9112abb3acf73abc104051ac318647055b189c/css/structure/jquery.mobile.listview.css#L65-L78) CSS rules.

Manually re-applying `border-radius: 1em` is a workaround.

**Comment by jaspermdegroot** [comment]
@arschmitz - Yeah, that will make it possible to change the selector and solve this.

@gabrielschulhof - You were working on listview classes option in branch 7692-listview-classes-option. I think the class that will be added to each list item will be ```ui-listview-item```. If you can change the selector to ```.ui-listview > ui-listview-item.ui-first-child > a.ui-btn``` this issue will be fixed.
