### ISSUE TITLE
iOS7 / iPad body height issue

### ISSUE THREAD

**Issue by plkilroy** [jquery/jquery-mobile#7682]
Ive stripped JQM to its most basic form, a simple home page, using 1.4.4 out of the box to discover a bug.

<div data-role="page" id="home" data-theme="a">
 <div data-role="content">      
 </div>
</div>

set .ui body to have a background color so you can see it below window:
 
.ui-mobile body {
height: 99.9%;
background:blue
}

On iPad Air os7 you can see a blue space that extends past the bottom of window, ui body is actually larger than 99.9% high, more like 105%, changing height value makes no difference. The Blue over hang is hidden below, but is scrollable.

What does this mean? On orientation change the whole page moves up*

I have put a test project online here: 

mobi3g.com/ipad_test/index.htm

* IMPORTANT to replicate the bug you need to follow this exact process on an iPad device (not a browser or emulator);

1/ (Home)  in Landscape view tap the arrow btn
2/ whilst on this page turn iPad to Portrait and click back Home
 3/ turn iPad to Landscape again. You will see that the Blue .ui-mobile body now shows, moving everything up.

This bug has been around for a few releases now, may want to test your Web Apps also.

Any advice really appreciated. Really need this fixed!!! as I have new build on Paul

Here are some screen shots.

Onload:

![photo](https://cloud.githubusercontent.com/assets/2654356/4330059/29071256-3fa6-11e4-89ff-f02179113380.PNG)

After the rotation sequence:

![photo2](https://cloud.githubusercontent.com/assets/2654356/4330067/5fc6cfa2-3fa6-11e4-953e-2aca649c00ac.PNG)

**Comment by apsdehal** [comment]
Closing due to missing version.
