### ISSUE TITLE
Table: Reflow table rendering issue after switching between breakpoints

### ISSUE THREAD

**Issue by caipigott** [jquery/jquery-mobile#7684]
Hello,

i have a problem with the movie-list table (using: demos.jquerymobile.com / 1.3.2 / examples / tables / movie-list.html) on android 4.2 and inside Safari browser.

After switching between the two different view styles (movie-list and table) the columns are shifted and get worst the more often the window shrinks and expands again.

![movie-list](https://cloud.githubusercontent.com/assets/8737797/4322049/0ce9b77e-3f45-11e4-84f6-2c8a3b28b934.GIF)

If you need further information, just let me know.

Regards,
Caipigott

**Comment by apsdehal** [comment]
Closing as a duplicate and not reproducable on 1.5-dev.
