### ISSUE TITLE
Listview: Add classes option

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#7692]

**Comment by gabrielschulhof** [comment]
@jaspermdegroot in css/structure.jquery.mobile.listview.css it says that ui-li-has-icon is deprecated in 1.4.0 and that it should be removed. Well, we no longer add class ui-li-has-icon and ui-li-has-thumb by hand, but does that mean we remove the rules associated with them as well?

**Comment by jaspermdegroot** [comment]
@gabrielschulhof 

Yes. CSS for ```ui-li-has-icon``` should be removed. We keep the CSS for ```ui-li-has-thumb```.
See http://jquerymobile.com/upgrade-guide/1.4/#images

**Comment by jaspermdegroot** [comment]
Note: https://github.com/jquery/jquery-mobile/issues/7670 can be fixed when implementing the classes option.
