### ISSUE TITLE
Selectmenu: Add classes option

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#7731]

**Comment by gabrielschulhof** [comment]
- [ ] Use theme extension
- [ ] _(add|remove|toggle)Class
- [ ] deepEqual -> strictEqual
- [ ] hasClasses
- [ ] style options go into .deprecated.js
- [ ] tests for deprecated stuff

**Comment by arschmitz** [comment]
This was landed in 1.5-dev
