### ISSUE TITLE
Bugs with :hover on iOS

### ISSUE THREAD

**Issue by Ajaxy** [jquery/jquery-mobile#7740]
Guys, I've just discovered ugly bag with `touchmove` event on iOS.

Any listener for `touchmove` added on `window` makes all hovers go crazy after any scroll.
If you open this example on iOS (7 at least) http://jsbin.com/nisiyidizeyu/1/edit you can see that after little scroll any tap outside `span`s results in "hover" action on them. The only cause is the javascript line:
```javascript
window.addEventListener('touchmove', function () {}, false);
```

I haven't found any similar issue here and anywere else, and it's weird, because jQM adds those listeners by default and it provides the same result: hoverable elements get hovered all of a sudden.
http://jsbin.com/huvoraba/153 — jQM example

Any ideas on this?

**Comment by apsdehal** [comment]
Closing as not fixable.
