### ISSUE TITLE
Mini Button text is truncated on Android 4.4.2

### ISSUE THREAD

**Issue by dpolivy** [jquery/jquery-mobile#7746]
Repro: http://jsbin.com/zaxabifelaso/1

On Android 4.4.2 (and possibly other versions), mini-buttons seem to have their text truncated. Based on some experimentation, it appears to be related to the 12.5px font size used for these buttons. WebKit doesn't seem to handle them very well; by default I believe it rounds to the nearest integer size. Either way, it looks like the button isn't sized correctly, and thus the text is truncated.

**Bad rendering:**
![image](https://cloud.githubusercontent.com/assets/3200655/4535655/fe5c9894-4db7-11e4-9cd1-73409a70818e.png)

Captured from the simulator (api19-x86) with this UA: `Mozilla/5.0 (Linux; Android 4.4.2; Android SDK built for x86 Build/KK) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36`

**Good rendering example, from Android 4.3:**
![image](https://cloud.githubusercontent.com/assets/3200655/4535678/a4ca3ec0-4db8-11e4-9dd5-d445b2f95a1d.png)

If you change the font size to 13px, then it renders correctly. And it renders correctly at 12.5px in pretty much every other browser I tried. I wasn't able to repro this in Chrome 30 on any other platform, so it must be something specific with the Android port or the version in that OS build.

Is there a specific reason for the decimal font size for mini buttons?

**Comment by jaspermdegroot** [comment]
The problem is gone on Android 5 so it's only an issue on 4.4.
I think it's not the 12.5px font-size on itself that triggers the bug, but the fact that we use ```em``` values for padding. Chrome had/has some roundings issues when ```em```s are used for padding.

To be honest I don't know why 12.5px has been chosen as font-size for mini when the project started. We could consider changing it to 13px to avoid issues like this one.

**Comment by arschmitz** [comment]
Yeah it seems like an on choice since not all browsers even support sub pixel rendering. I do however worry about breaking existing layouts?

**Comment by jaspermdegroot** [comment]
Ref https://github.com/jquery/jquery-mobile/issues/6787

**Comment by jaspermdegroot** [comment]
I changed the font-size from 12.5px to 13px when updating button and icon CSS (1.5-dev-css branch).
