### ISSUE TITLE
Icon-only example of demos site incorrect

### ISSUE THREAD

**Issue by Shreerang** [jquery/jquery-mobile#7770]
Steps to view the issue.

1. Navigate to http://demos.jquerymobile.com/1.4.4/button/
2. Move down to Icons-only button section.
3. The description says - Icon-only buttons are round by default. Here we show how you can set the same border-radius as other buttons.
4. The second icon-only button should have a squarish look boreder-radius (refer to the image inline).
5. In the code, the div with id="custom-border-radius" should have the following CSS.

#custom-border-radius .ui-btn-icon-notext.ui-corner-all {
    -webkit-border-radius: .3125em;
    border-radius: .3125em;
}

![screen shot 2014-10-10 at 2 13 56 pm](https://cloud.githubusercontent.com/assets/3829231/4589876/a721863a-5059-11e4-9add-db179148868b.png)

**Comment by arschmitz** [comment]
This no longer exists in the new demos, so i'm going to close this.
