### ISSUE TITLE
External panels do not hold their scroll

### ISSUE THREAD

**Issue by jroets** [jquery/jquery-mobile#7786]
1. On an iphone, go to the jqm demo page for "External Panels"
2. Tap "Reveal" under "Left panel examples" (or any other type)
3. Flick the panel up and down a few times.
4. Notice that every other flick up will cause the panel to jump back down.

If you drag the panel up rather than flick it, it will hold its position, but you will notice a flash as you drag.

**Comment by apsdehal** [comment]
Yes, even on latest 1.5-dev, it do behaves weirdly with a lot of flickering in scrolling. Status is now confirmed.

**Comment by apsdehal** [comment]
not able to reproduce.
