### ISSUE TITLE
Toolbar hide method doesn't work for fixed header toolbar

### ISSUE THREAD

**Issue by yosikal** [jquery/jquery-mobile#7789]
Toolbar hide method doesn't work for fixed header toolbar. It does work for fixed footer toolbar. Click hide on this test page: http://jsbin.com/qayibocoyo/2/watch?html,output

**Comment by Jahrenski** [comment]
Doing just that will leave a dark shadow of the toolbar on the page. Is there a way to refresh the page padding? toolbar("updatePagePadding") doesn't seem to do the trick.

**Comment by arschmitz** [comment]
@Jahrenski you will have to do that yourself using `.css` just set it to `0`

**Comment by Jahrenski** [comment]
Thanks, I did just that and adjusted page height accordingly.
