### ISSUE TITLE
Toolbar: data-role="header" and data-role="footer" should be replaced with data-role="toolbar"

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#7803]
... and whether it's a header or a footer should be specified via a widget option.

When we do this, we should also modify ```$.mobile.resetActivePageHeight()```'s ```compensateToolbars()``` method to select toolbars exclusively via ```:mobile-toolbar``` and to restrict itself to examining widget instance option values for the purpose of determining whether the toolbar affects page height.

**Comment by jaspermdegroot** [comment]
I am going to close this because it landed in 1.5-dev as part of the toolbar rewrite by @cgack.
