### ISSUE TITLE
legend vs label in responsive form

### ISSUE THREAD

**Issue by afwd** [jquery/jquery-mobile#7815]
Legend and label should be treat as the same in terms of layout when it comes to a responsive form (correct me if I'm wrong).

At the moment they look slightly different in chrome because the user agent stylesheet adds
```
legend {
-webkit-padding-start: 2px;
-webkit-padding-end: 2px;
}
```

Also, text can be hidden behind a form input element that the legend refers to because the overflow goes outside the .controlgroup-label. Here is an example of a form which would cause this problem on a larger screen where the label might be under the form element.

```
<div class="ui-field-contain" data-controltype="radiobuttons" data-type="vertical">
    <fieldset data-role="controlgroup" data-type="vertical" data-mini="true">
        <legend>
            Transmission Type:
        </legend>
        <input id="rd" name="transmission" value="1" type="radio" checked="checked">
        <label for="rd">
            Rear Derailleur
        </label>
        <input id="ss" name="transmission" value="0" type="radio">
        <label for="ss">
            Single Speed
        </label>
    </fieldset>
</div>
```

If you're struggling to get this to work you can set the width on a page element using 
```
.ui-page {
    max-width: 28em;
}
```
and you'll see what I mean hopefully.

**Comment by apsdehal** [comment]
Not able to reproduce anymore, also since user agent css properties are being added, this is not directly related to jqm.
