### ISSUE TITLE
Spelling Mistake, change carat to caret

### ISSUE THREAD

**Issue by ryanwilliams83** [jquery/jquery-mobile#7819]
The caret /ˈkærət/ is an inverted V-shaped grapheme.
The carat is a unit of mass equal to 200 mg (0.2 g; 0.007055 oz) and is used for measuring gemstones and pearls.

Appears in css classes .ui-icon-carat-d, .ui-icon-carat-l, .ui-icon-carat-r, .ui-icon-carat-u etc
Appears in file names carat-d-black.png etc

**Comment by arschmitz** [comment]
This was fixed closing
