### ISSUE TITLE
Mini slider is broken in 1.4.5

### ISSUE THREAD

**Issue by slavap** [jquery/jquery-mobile#7821]
Test case: http://jsbin.com/zuyapirepi/1/edit
Workaround: .ui-slider-track.ui-mini { margin: 0 15px 0 68px; }

Originally reported here: https://plus.google.com/105587967205913541400/posts/4DQVj3o5xYE
It's also broken on official demo page: http://demos.jquerymobile.com/1.4.5/slider/

**Comment by jaspermdegroot** [comment]
This is a regression from commit https://github.com/jquery/jquery-mobile/commit/ab067cb8147f1b1155db0622fda18b792122b730. There is a PR for reverting that commit: https://github.com/jquery/jquery-mobile/pull/7999
There is another ticket for this issue, which describes all problems (https://github.com/jquery/jquery-mobile/issues/7991) so I am going to close this ticket as duplicate.
