### ISSUE TITLE
JQuery Mobile CSS without the structure

### ISSUE THREAD

**Issue by ghost** [jquery/jquery-mobile#7827]
Hi,

its nice to see that on the downloadpage i can download the jqm-css without the fullblown themes but there is only one problem for me... the structure - is it possible to cut that last part off too? i wish i would have a css file containing only the crossbrowser-fixes, things like user-select: none; for buttons etc. and the animation-part. thats all i need - and i dont want to reset the whole ui before starting a project... thanks.

**Comment by apsdehal** [comment]
You can try building the specific parts from the repo itself as it is highly modular. Closing as of now.
