### ISSUE TITLE
pagecontainerremove doesn't fire

### ISSUE THREAD

**Issue by Palestinian** [jquery/jquery-mobile#7831]
The `pagecontainerremove` should fire once navigated away off an _uncached external_ page. It doesn't fire while the deprecated [`pageremove`](https://github.com/jquery/jquery-mobile/blob/master/js/widgets/page.js#L120) does fire (page widget).

I have tested all 1.4 sub versions and it didn't work in either one. I have also checked [pagecontainer.js](https://github.com/jquery/jquery-mobile/blob/master/js/widgets/pagecontainer.js) but couldn't find any trace of it nor is it used by `_triggerWithDeprecated`.

[Demo](http://plnkr.co/edit/x1MrXk3xYldz1SvuaexL?p=preview) - jQM 1.4.5 - Single Page Model

**Comment by apsdehal** [comment]
Issue with docs. Closing here. We will keep track of this in api repo.
