### ISSUE TITLE
Swipe issue on nexus 7. works fine on samsung tab3 neo - jQm 1.4.2

### ISSUE THREAD

**Issue by pavanshirguppi** [jquery/jquery-mobile#7851]
$( document ).on( "pagecreate", ".ui-page", function() {
			$( document ).on( "swipeleft swiperight", ".ui-page", function( e ) {
				if ( $( ".ui-page-active" ).jqmData( "panel" ) !== "open" ) {
					if ( e.type === "swipeleft" ) {
						$( "#outside" ).panel( "open" );
					} else if ( e.type === "swiperight" ) {
						activePage = $.mobile.activePage.attr("id");
						if (activePage == "login") {
							//don't slide.
						}else { 
							$( "#menu" ).panel( "open" );
						 } 
					}
				}
			});
		});

The above code is written to enable swipe right function other than login page.
The swipe right slides a panel in the right of user and user can select options.

It just that code works fine on samsung tab and not on nexus. it just doesnt call the swipe

Android 4.2.2 sam
Android 4.4.4 nex
jqm - 1.4.2

**Comment by apsdehal** [comment]
Closing due to missing components on issue poster's side.
