### ISSUE TITLE
scrollstop & scrollstart multiple firing - Safari iOS 8 

### ISSUE THREAD

**Issue by Palestinian** [jquery/jquery-mobile#7855]
Both `scrollstop` and `scrollstart` fire multiple times in Safari iOS 8 but not Chrome same platform.

I tested the below code in iPhone 5 iOS 8.1.1 Safari and Chrome 39.0.2171.50.

Demo: http://jsbin.com/quhuge/

**Comment by apsdehal** [comment]
Closing as not an issue with jqm.
