### ISSUE TITLE
No visual feedback given when pressing a button/stylished link #4469 continued

### ISSUE THREAD

**Issue by pavanshirguppi** [jquery/jquery-mobile#7861]
Let me share this neither of them worked for me. Need your thoughts on this. 
Referring to this link https://github.com/jquery/jquery-mobile/issues/4469

What I tried ..?
$(document).bind("mobileinit", function(){ $.mobile.buttonMarkup.hoverDelay = 100; });
$('#WoBackbutton').bind('click', function(){ $(this).button('refresh'); return true; });
Its just that the button doesnt show the active state. This is my button.

anchor tag href="#" data-transition="none" id="WoBackbutton" data-icon="back" onclick="WorkOrder.updateBackData()" class="ui-btn-left">Back</a

Using jquery mobile 1.4.5 on android 4.1.2.
Guess what on 4.4.4 version the same above button -active state works sometimes. very rare one in like 10 clicks. but on 4.1.2 version it doesnt work at all. Kindly let me know anything else i need to modify.

**Comment by apsdehal** [comment]
Kindly use http://jsbin.com/huvoraba/1/edit?html,output to provide a fiddle, closing till then. Reopen whenever you can confirm the issue with fiddle.
