### ISSUE TITLE
Bower dependency on jQuery should use >=

### ISSUE THREAD

**Issue by gseguin** [jquery/jquery-mobile#7872]
We should use a >= instead of a fixed version for our dependency on jQuery

**Comment by arschmitz** [comment]
@gseguin Yup your right we should fix this.

**Comment by ajssd** [comment]
Until this is fixed, what is the workaround?  Running 'bower install jquery-mobile' pulls in an old version of jQuery, overwriting the current 2.1.3 in my bower_components, breaking my app.  The bower.json in jquery-mobile should not use fixed version numbers.
