### ISSUE TITLE
Tab Widget list item active tab does not maintain highlight when other buttons are pressed

### ISSUE THREAD

**Issue by adammatthewsmith** [jquery/jquery-mobile#7873]
Using tabs in a navbar as in http://view.jquerymobile.com/master/demos/tabs/, if you select other buttons in the page (not the navbar) the navbar button anchors lose the 'ui-btn-active' class and therefore lose the blue highlight. 

To test:
1. Go to the tabs demo page. (https://github.com/jquery/jquery-mobile/issues/7407 already captures the issue where the first tab is not highlighted by default even though its content is shown).
2. Select any tab.  It should become highlighted. 
3. Select the 'View Source' button.
4. Close the source window.
Expected: the selected tab should still be highlighted.
Actual: no tabs are highlighted.

**Comment by slavap** [comment]
It's better to look at this problem from the other side, i.e. from tabs widget. Active page header must always be highlighted. Period. Doesn't matter what else is going on on the page and what kind of other widgets are in use. It's just unnatural behavior, and fixing docs is not a solution.

**Comment by apsdehal** [comment]
@agcolom Are you still willing to fix the api docs? If not, I will take the charge.

**Comment by apsdehal** [comment]
I am closing this for now, but I will add this to TODO for docs.

**Comment by amitdhiman000** [comment]
I found same behaiour with
<input type="submit" value="SignUp" />

I submitted form by ajax some errors reported from server so I displayed the errors on same page.
but meanwhile tabs loose the focus and submit button getting focus.
Is there any fix for this ?
