### ISSUE TITLE
Popup: bb10 buttons won't trigger click if popup contains input with placeholder

### ISSUE THREAD

**Issue by mckenzielong** [jquery/jquery-mobile#7883]
Using cordova on BlackBerry OS10 (10.2 and 10.3), placing an input tag inside a popup, with a placeholder attribute, will cause buttons to require a second press to trigger the click event.  Removing the placeholder tag should return the click event to be triggered on the first press.  

Test page:
http://jsbin.com/vujimofumu/1/

Steps to reproduce:
1) Create page with an input tag with placeholder set inside a popup, create a button outside the popup.
2) Either log events or place a listener on the button outside the popup
3) Press the button

Expected outcome:
Click event will be triggered

Actual outcome:
Mousedown and mouseup events fire, but the click does not happen.

Versions used: 
JQM 1.4.5, JQ 2.1.1 with Cordova 3.5.1 on BlackBerry 10.2 and 10.3

**Comment by gabrielschulhof** [comment]
This class is removed from the popup before the popup is placed on screen, so I don't see how the contents of this class can affect the resulting popup.

**Comment by arschmitz** [comment]
This seems like a very obscure rendering issue with blackberry 10 and should probably be reported to them.

**Comment by mckenzielong** [comment]
BB10s browser has gone through a few revisions since I opened this item. Haven't seen this lately.  Closing.
