### ISSUE TITLE
sticky header 

### ISSUE THREAD

**Issue by dezudas** [jquery/jquery-mobile#7885]
There is issue with sticky header when I try to search something in the listview filter. It start to move once keyboard is up. This issue is only in IOS

App name: Chordpedia

![img_1516](https://cloud.githubusercontent.com/assets/289415/5560512/606e99f2-8db8-11e4-9450-e488ce7c577a.PNG)
![img_1515](https://cloud.githubusercontent.com/assets/289415/5560514/68bdb598-8db8-11e4-9925-150966f20125.PNG)

**Comment by Ruffio** [comment]
@dezudas Do you have a test page demonstration the issue?

**Comment by arschmitz** [comment]
Im going to close this as incomplete. Also note there is no such thing as fixed position in iOS while the keyboard is open. they fix where they are and then scroll with the page ( kinda almost like absolute position ).

So basically putting a textinput in a fixed header in iOS is pretty awkward in general.

**Comment by dezudas** [comment]
@Ruffio you can see the issue in my current version of the app hosted in appstore chordpedia.
