### ISSUE TITLE
Table is always printed in responsive mode

### ISSUE THREAD

**Issue by ottoville** [jquery/jquery-mobile#7896]
When printing a web page with responsive table, the table is always printed in responsive mode when paper is set to vertical position, no matter if the table can fit the page or not.. When changing the orientation to landscape, table is printed in normal mode.

I tested this by going to example page: http://api.jquerymobile.com/resources/table/example1.html
Then changed the font size to 1px, so the text for sure fit in A4 sized paper.

**Comment by ottoville** [comment]
I took a screenshot from chrome's print preview window to illustrate the problem
http://imageshack.com/a/img661/2883/7qs5O0.png

It also seems that there is a weird scroll bar printed into the paper, leaving some content out from paper

**Comment by gabrielschulhof** [comment]
@jaspermdegroot Is it possible to add some printer-related media queries for class ```ui-responsive```?

**Comment by jaspermdegroot** [comment]
@gabrielschulhof - Sure, I'll look into it.
