### ISSUE TITLE
Popup keyboard not hidden when tapping on a select (Chrome/iOS 8)

### ISSUE THREAD

**Issue by robcaldecott** [jquery/jquery-mobile#7899]
If a text input has focus and the popup keyboard is displayed, tapping on a select will not close the popup keyboard before the list of options is displayed. The keyboard won't disappear until you select an option from the list.

To reproduce, simple create page with the following content:

    <input type="text">
    <select><option>Option 1</option><option>Option 2</option></select>

Tap on the input to display the popup keyboard and then tap on the select.

Tested using Chrome 39 on iOS 8.1.2 (iPad Mini).
Safari works as expected.

Full sample below (JS Bin is blocked by my work proxy. Very sorry.):

	<!DOCTYPE html>
	<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
		<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
		<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
	</head>
	<body>
	<div data-role="page">
		<div role="main" class="ui-content">
			<input type="text">
			<select><option>Option 1</option><option>Option 2</option></select>
		</div>
	</div>
	</body>
	</html>

**Comment by gabrielschulhof** [comment]
@robcaldecott I don't have an iOS 8.1 device, so could you please check whether jQuery Mobile is required for this to happen? That is, if you use a plain HTML file with no scripts, does the same thing happen?

**Comment by robcaldecott** [comment]
Just tried some plain old HTML and am seeing the same issue, so it looks like a Chrome bug.

**Comment by arschmitz** [comment]
Doubt there is anything we can do here since this is a chrome bug and we have no direct control of the keyboard.
