### ISSUE TITLE
README: compatibility with newer Node

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-mobile#7900]
README [says](https://github.com/jquery/jquery-mobile#requirements) that the requirement to build is Node ~0.8.22 which means Node 0.10 won't work. Even Node 0.10 is currently old and many projects have dropped support for 0.8 long ago.

Shouldn't it say Node >=0.8.22?

**Comment by arschmitz** [comment]
Yes it should. Well really `>=0.8.0` since that whats in our package.json

**Comment by mzgol** [comment]
Actually, with the npm version included by default in latest 0.8.* the project doesn't build for me (npm install fails). Most people don't update the included npm version and Windows users even cannot do it easily (update installs to a different location and the one built into Node takes precedence...).

Even if it can be made work with Node 0.8, I'd advise to at least point people to newer versions

**Comment by scottgonzalez** [comment]
Just drop the field entirely. Also 0.10 is current, not old.

**Comment by arschmitz** [comment]
Im actually inclined to drop the whole thing here as well.

**Comment by mzgol** [comment]
> Also 0.10 is current, not old.

Yeah, I meant that it went out a long time ago (almost 2 years).

**Comment by mzgol** [comment]
So, how about dropping the Node requirement from README? Should I submit a PR?

**Comment by arschmitz** [comment]
@mzgol :+1:

**Comment by mzgol** [comment]
PR: #8275
