### ISSUE TITLE
Suggestion: Create an event for .draggable for mobile. 

### ISSUE THREAD

**Issue by KeeyaWangJones** [jquery/jquery-mobile#7901]
Drag left, right, up, down, and auto options. Currently, I am using jQuery UI Touch Punch to solve the problem, but wouldn't it be awesome if this feature was already package in jquery-mobile.

**Comment by arschmitz** [comment]
jQuery UI draggable will be part of jQuery mobile once it supports touch events via a pointer events polyfill ( we will also be replacing vmouse with the same polyfill ). So i'm going to close this as wont fix since we wont be making a separate widget.
