### ISSUE TITLE
Navbar without links

### ISSUE THREAD

**Issue by zimi-pl** [jquery/jquery-mobile#7909]
I had an issue with navbar. Links for this component was generated from my backend and when I tried to generate new page for my application I forget to declare navigation links for it.

When in navbar there is no link it fails to load page. And console is not very helpful. It's not idiot-proof. In fact it was not trivial for me to debug what's happening. It could more helpful, for example with appropriate error "There is no link for navbar! idiot!"... :P

Example: http://jsfiddle.net/9sbm3942/1/

**Comment by arschmitz** [comment]
@zimi-pi i agree this should either work and load just with no links or throw a proper error

**Comment by apsdehal** [comment]
Fixed in 1.5-dev.
