### ISSUE TITLE
Responsive panel in demo does not work as stated.

### ISSUE THREAD

**Issue by moriciogithub** [jquery/jquery-mobile#7910]
http://demos.jquerymobile.com/1.4.5/panel-responsive/

It doesn't become responsive. I have tried it in Chrome, Firefox, etc in a wide screen computer and also in tablets and it doesn't work.

**Comment by Ruffio** [comment]
I can confirm that there is no 'responsive' about the above mentioned page in Chrome. On a 4K screen none of the panels are visible.

**Comment by apsdehal** [comment]
I find it working fine in 1.5-dev. Closing.
