### ISSUE TITLE
Need swipeStopEvent for swipe

### ISSUE THREAD

**Issue by tryagains** [jquery/jquery-mobile#7911]
Okay so touchStopEvent has "touchend mouseup" so you can do this
$("#canvas").on("touchend mouseup",function(e){...}

swipe doesnt have it so I cant call
$("#canvas").on("touchend swipeup",function(e){...)

What can I do for swipeStopEvent?

**Comment by apsdehal** [comment]
Kindly consult the docs at https://api.jquerymobile.com/swipe/ for swipe stop event handler.
