### ISSUE TITLE
Panel Widget Stuck On Closing

### ISSUE THREAD

**Issue by yonasstephen** [jquery/jquery-mobile#7913]
The JQuery Mobile panel's body stuck for a while before closing. This happens only when the data-display type is of "reveal"

This test page explains best: http://jsbin.com/qogixiruli/2/

Any idea what's wrong?

**Comment by gabrielschulhof** [comment]
Please put page content (such as "test 123") into a div with class ui-content. This completes the jQuery UI page. http://jsbin.com/fakilu/1/edit shows you.
