### ISSUE TITLE
Selectmenu - mini, inline, multiple - count indicator visual glitch

### ISSUE THREAD

**Issue by slavap** [jquery/jquery-mobile#7918]
Demo: http://jsbin.com/bupisimofo/1/edit?html,css,output
Count indicator position must be different when mini="true".

**Comment by jaspermdegroot** [comment]
@slavap 

On what browser/device do you see the issue? I don't really see the problem when checking your JS Bin on OS X / Chrome.
Thanks!

**Comment by arschmitz** [comment]
@jaspermdegroot narrow the output pane and you will see it

**Comment by jaspermdegroot** [comment]
@slavap @arschmitz - Nevermind. I now see that the JS Bin contains the fix. I expected it to show the issue.
