### ISSUE TITLE
Can not back to Previous page on Safari

### ISSUE THREAD

**Issue by cuongtallcat** [jquery/jquery-mobile#7921]
My Demo: http://captheme.com/mobile/demo.html

Click Page 2 to show Popup, and click DEMO-2. Back button is enable but i can back

I test Safari on windows 8 + Iphone 5
Thanks

**Comment by arschmitz** [comment]
@cuongtallcat Please see our contributing guidlines and create a simple jsbin test page using the template there to recreate the issue. Im going to close this as incomplete. If a page is provided we will reopen.
