### ISSUE TITLE
Option to use (data-role="header") inside Collapsible Widget

### ISSUE THREAD

**Issue by baig** [jquery/jquery-mobile#7922]
It would be nice to have the option to use `data-role="header"` inside `data-role="collapsible"` like this

```H	
<div data-role="collapsible">
    <div data-role="header">
        <h4>Fruits</h4>
        <button class="ui-btn-right ui-btn ui-btn-a ui-icon-edit ui-btn-icon-right ui-btn-inline">Edit</button>
    </div>
    <ul data-role="listview">
        <li><a href="#">List item 1</a></li>
        <li><a href="#">List item 2</a></li>
        <li><a href="#">List item 3</a></li>
    </ul>
</div>
```

This will give us the flexibility to add buttons in the collapsible header.

**Comment by FritzTheBlitz** [comment]
Hi @baig 
Would this not end with a link inside a link, what means invalid markup?

**Comment by Ruffio** [comment]
@baig, any comments on this one? This issue has been stalled for 3 months, maybe it should be closed?

**Comment by baig** [comment]
Yeah close it. I found a simple way to do it. See [this](https://github.com/baig/jqm-extended-collapsible) if interested.
