### ISSUE TITLE
iOS7/8: Double page transition when swiping left/right through browser history

### ISSUE THREAD

**Issue by kinless** [jquery/jquery-mobile#7936]
On iOS 7 or 8 Safari, if there are any animating page transitions set, and the user swipes the left or right edge of the screen to navigate browser history, there appears to be a double transition, as the native iOS slide fires, and then JQM's transition fires in succession. So if page transition is set to "slide" there appears to be a double slide.

Any way to set transitions to 'none' only on back/forward events?

**Comment by apsdehal** [comment]
Kindly provide a jsbin according to contribution guidelines and reopen the issue.
