### ISSUE TITLE
problem with listview about set icon after init

### ISSUE THREAD

**Issue by kh2se2013** [jquery/jquery-mobile#7937]
Hi, I got a problem with listview. I need change the icon sometime after it init.

I followed the api doc to change the link icon, but it has no effert.

http://jsfiddle.net/zv2d7cLx/7/

**Comment by arschmitz** [comment]
The options on listview cannot be set at runtime.

**Comment by apsdehal** [comment]
Linked with #8334. This can be fixed with refresh. So closing as a preference to it.
