### ISSUE TITLE
Toolbar: Footer is offset during transition

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#7939]
Current HEAD of master is e0c83765ee47780d26fae1e5b97b759e47847ed2.

Steps to reproduce:
1. Go to http://view.jquerymobile.com/master/demos/toolbar-fixed-persistent/
2. Click around the demo pages and watch the footer/navbar closely

At this point, you will see the following during the transition (screenshot from before the transition overlaid with screenshot during the transition - red line added for emphasis):
![toolbar-offset-during-transition](https://cloud.githubusercontent.com/assets/976081/5893661/7e957438-a4f5-11e4-82af-86d8f25782ce.png)

I've seen this on
- Chrome Version 39.0.2171.95 (64-bit)/Linux desktop
- Chromium Version 41.0.2270.0 (64-bit)/Linux desktop

FF is fine.

**Comment by Ruffio** [comment]
I can confirm that on Windows 8.1 x64 Chrome Version 40.0.2214.91 m the navbar/footer is jumping 1px up and down. When the transition starts the navbar is moving 1px up and when the transition stops  it falls 1px down.

Further testing:
IE 11 - no problems at all
FX 34.0.5 - 
   Info -> Albums - 1px jumping
   Friends -> Albums  - 1px jumping
   Emails -> Albums - 1px jumping
   All other combinations are ok

I think it is the 'turn' transition that is the problem.

**Comment by gabrielschulhof** [comment]
This is a duplicate of #4259.

**Comment by gabrielschulhof** [comment]
@Ruffio it's not just the turn transition. It's all sequential transitions, I think. The only one that truly works is slide, because (I suspect) slide uses the simultaneous transition handler rather than the sequential one.
