### ISSUE TITLE
All: Deprecate portions of initSelector that are not "[data-ui-role='<widgetname>']"

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#7940]
Place comments in the code of the form
```JS
// The default value of initSelector is DEPRECATED as of 1.5.0 and will be removed in 1.6.0
```
before each ```initSelector``` declaration.

Make sure that it is clear that ```initSelector``` itself is not deprecated and that it will continue to be honoured in future versions, only that it will be set to ```[data-ui-role="<widgetname>"]``` by default for all widgets.

**Comment by gabrielschulhof** [comment]
See also https://github.com/jquery/api.jquerymobile.com/issues/353

**Comment by gabrielschulhof** [comment]
See also https://github.com/jquery/jquerymobile.com/issues/113

**Comment by ray007** [comment]
I guess that means `selectmenu` will also get a less greedy `initSelector`?
Something like `"select:not(:jqmData(role)), select:jqmData(role=selectmenu)"`?

**Comment by arschmitz** [comment]
@ray007 the init selector for selectmenu will be `[data-ui-role='selectmenu']` after this change

**Comment by apsdehal** [comment]
@arschmitz I guess this can be closed now.
