### ISSUE TITLE
Remove dates from copyright notice

### ISSUE THREAD

**Issue by agcolom** [jquery/jquery-mobile#7944]
Dates are not required so we can remove them and that avoid having to change everything every new year

**Comment by jtara** [comment]
I am not a lawyer, but... (don't you hate it when you see a post that starts like that...)

You might want your lawyers to look at this. Did this decision come down after conferring with an IP attorney? The following is not the text of the law, but a circular published by the U.S. Copyright Office to clarify copyright notice requirements:

  http://www.copyright.gov/circs/circ03.pdf

My (non-lawyerly take). You don't need a copyright notice at all. Adding one might provide some additional rights or proof, etc.and would see to me to be prudent.  Iff you do use one, it should include the date of first publication, according to the above publication. 

I don't see any mention of a requirement to include the most recent date of publication, so (after conferring with an appropriate attorney) you might want to clarify this to ask that only ONE date (the date of initial publication) be included.

But, then again, it seems to me that by omitting the most recent date of publication of a revised work, you might short-change yourself on the copyright period. I suppose it would not be difficult, though to prove the date of publication of any part of JQM...

I think it would be to clarify, if that is the case, that "the lawyers told us this is OK".

**Comment by agcolom** [comment]
@jtara Yes, our lawyer told us this was ok.

**Comment by arschmitz** [comment]
:+1:

**Comment by jaspermdegroot** [comment]
I will do a find and replace.

**Comment by arschmitz** [comment]
Fixed on 1.5

**Comment by pra85** [comment]
@arschmitz Were your commits reverted? Currently on `master` branch, files like `LICENSE-INFO.min.txt` , `LICENSE-INFO.txt` and `LICENSE.txt` still seem to have years in them

**Comment by jaspermdegroot** [comment]
@pra85

The changes are made in a 1.5 branch which hasn't been merged into master yet.
