### ISSUE TITLE
Is throttledresize missing in latest jquery.mobile-git.js?

### ISSUE THREAD

**Issue by DzenisevichK** [jquery/jquery-mobile#7950]
I found that `throttledresize` event is not fired in latest `jquery.mobile-git.js` because `js/events/throttledresize.js` is not included in it:

http://code.jquery.com/mobile/git/jquery.mobile-git.js

**Comment by gabrielschulhof** [comment]
Yes, and this is fixed by #7926.

**Comment by gabrielschulhof** [comment]
Thanks for noticing :)
