### ISSUE TITLE
$.mobile.resetActivePageHeight doesn't work correct on maximize-restoredown case

### ISSUE THREAD

**Issue by DzenisevichK** [jquery/jquery-mobile#7951]
Google Chrome (Version 40.0.2214.93 m) on Windows 7 SP1 x64

Problem introduced by commit:
[Helpers: Make resetActivePageHeight() less aggressive...](https://github.com/jquery/jquery-mobile/commit/459bb59eff0306a345b0a23d76263a73582e7432)

Workable example with jQueryMobile 1.4.2 (without above commit):
http://jsbin.com/hesesihiqi/1

Problem example with jQueryMobile 1.4.5 (with above commit):
http://jsbin.com/mukupoliwu/1

Steps to reproduce:
  1. Maximize browser window
  2. Restore-down browser window -> You will see that textarea are not expanded to take fullheight in problem example

**Comment by gabrielschulhof** [comment]
@DzenisevichK [this](http://jsbin.com/cazahi/4/) is how I've managed to get resize-with-window to work. Note that I'm referring to the jQuery Mobile JS via http://view.jquerymobile.com/master/js/ rather than the usual CDN URL of the git version because throttledresize is currently erroneously omitted from the build (#7925). Nevertheless, the jsbin works with 1.4.5 as well: http://jsbin.com/cazahi/6/

If this does not serve your purpose, please re-open this issue or, if github won't let you re-open, please file a new one and refer to this one.

**Comment by DzenisevichK** [comment]
@gabrielschulhof

Thank you for hint how to workaround new problem `$.mobile.resetActivePageHeight`:

```js
// Hookup resetActivePageHeight to trigger pageresize event
$.mobile.resetActivePageHeight = (function (prevHandler) {
	return function () {
		var $page = $("." + $.mobile.activePageClass),
			$content = $page.find(".ui-content");
		// Workaround for original resetActivePageHeight
		// (see https://github.com/jquery/jquery-mobile/issues/7951)
		// to have min-height always
		$content.height(0);
		prevHandler.apply(this, arguments);
		$content.css({ height: "" }); // Remove previous height setting
		$page.trigger("pageresize");
	};
})($.mobile.resetActivePageHeight);
```

And now all works also with jQueryMobile 1.4.5:

http://jsbin.com/yiqoqigaco/1

**Comment by DzenisevichK** [comment]
@gabrielschulhof 

Found that with `$content.height(0);` I have scroll jumping. So the same will be with your solution but when we have additional controls which allow to see scrolls. To fix this I need to save/restore `scrollTop`:

```js
// Hookup resetActivePageHeight to trigger pageresize event
$.mobile.resetActivePageHeight = (function (prevHandler) {
	return function () {
		var $window = $(window),
			$page = $("." + $.mobile.activePageClass),
			$content = $page.find(".ui-content"),
			scrollTop;
		// Workaround for original resetActivePageHeight
		// (see https://github.com/jquery/jquery-mobile/issues/7951)
		// to have min-height always
		scrollTop = $window.scrollTop();
		$content.height(0);
		prevHandler.apply(this, arguments);
		$content.css({ height: "" }); // Remove previous height setting
		$window.scrollTop(scrollTop);
		$page.trigger("pageresize");
	};
})($.mobile.resetActivePageHeight);
```

And now this hookup is too complex and I think that we need to review original `$.mobile.resetActivePageHeight` implementation...

**Comment by gabrielschulhof** [comment]
@DzenisevichK the code in my demo was designed for a page that is by default not as tall as the viewport. That is, it is designed for a page that needs to be stretched. If the page is taller than the viewport, then I'm not sure why you would want to stretch anything to the size of the viewport. Can you give me a demo illustrating your jump-to-top problem?

**Comment by DzenisevichK** [comment]
@gabrielschulhof 

Problem with scroll jumping is not reproduced (strange). But I extended example to have real live version:

**Without workaround** (check Maximize/Restore Down case where textarea will not be expaned on free space):
http://jsbin.com/tivadoxure/1/

**With workaround**:
http://jsbin.com/tivadoxure/4/

**Comment by DzenisevichK** [comment]
@gabrielschulhof

Found also that when we change header height by showing/hiding an element jQueryMobile doesn't call `$.mobile.resetActivePageHeight` but it's necessary because page padding is updated (by `$.mobile.toolbar.updatePagePadding`)...
