### ISSUE TITLE
Demos: Reflow table, last entry without stripes

### ISSUE THREAD

**Issue by roman-e** [jquery/jquery-mobile#7954]
Hi

If both styles, .table-strike and .table-stroke are given to a reflow table, 
the last row will have no stripes in the reflow mode.

You could reproduce this issue in your demo if you scale down the width of the window to reflow the table to the smartphone view:
http://demos.jquerymobile.com/1.4.5/table-reflow-stripes-strokes/

**Comment by gabrielschulhof** [comment]
Stripe and stroke for table are deprecated and will be removed. Might as well make this issue into a reminder. Thanks for bringing it to our attention!

**Comment by arschmitz** [comment]
@gabrielschulhof those classes are not used in that demo that demo was updated for 1.4 to remove the deprecated styles with an example of how to do this yourself. @kakul pr seems correct i don't see any extra or double borders as a result.
