### ISSUE TITLE
JQM 1.4.5 iPad/iPhone - drop down list inside dialog opens when dialog is closed

### ISSUE THREAD

**Issue by janey1986** [jquery/jquery-mobile#7955]
The problem I'm having is that when this page is opened in Safari (iPad iOS 7 / 8) and the dialog is opened it seems to be working fine. However, if I then close the dialog the options list flashes up on the screen whilst the dialog is closing. I think this is a bug as I have only been able to recreate it on the iPad / iPhone. I cannot recreate this on Android or PC. 

code: 

    <a href="#popupDialog" data-rel="popup" data-position-to="window" data-transition="pop" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-icon-delete ui-btn-icon-left ui-btn-b">Delete page...</a>
			<div data-role="popup" id="popupDialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
			    <div data-role="header" data-theme="a">
			    <h1>Delete Page?</h1>
			    </div>
			    <div role="main" class="ui-content">
			        <select name="select-choice-1" id="select-choice-1">
					    <option value="standard">Standard: 7 day</option>
					    <option value="rush">Rush: 3 days</option>
					    <option value="express">Express: next day</option>
					    <option value="overnight">Overnight</option>
					</select>
			        <a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back">Cancel</a>
			        <a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back" data-transition="flow">Delete</a>
			    </div>
			</div>

**Comment by gabrielschulhof** [comment]
Interesting. Sounds kinda like #6661 but in a different scenario.

**Comment by gabrielschulhof** [comment]
I think I know what it is. The focus restriction logic fires one last time when you click on the overlay behind the popup.

**Comment by gabrielschulhof** [comment]
@janey1986 I believe this is already fixed by the modification submitted via PR #7956 that also fixes #7856.

I made a jsbin illustrating the [broken](http://jsbin.com/pohali/1) version and one illustrating the [fixed](http://jsbin.com/pohali/2/) version. The latter uses code from PR #7956.
