### ISSUE TITLE
JQM 1.45 loading initial page slowly

### ISSUE THREAD

**Issue by mtamony** [jquery/jquery-mobile#7960]
I switched from jqm 1.4.0 js and css to 1.4.5 js and css and also changed to jquery 1.11.2 in a phone gap/ cordova project. Testing in iOS. On loading, after splash, the first page background kind of half loaded then approximately 3 seconds later the bottom of the background image loads. Here is the challenging part. It is only happening on iPad 3 device running 8.1 and on the resizable emulator running 8.1. 

To fix it I change JQM back to 1.4.0. I tried fixing by going back to previous versions of JQM CSS and jquery 1.10. Neither fixed it. Only reverting to JQM 1.4.0.

Confusing and I apologize in advance if this isn't a bug.

**Comment by gabrielschulhof** [comment]
Ideally we need a link to a page showing good performance with 1.4.0 and a link to a page that is identical to the first but which refers to 1.4.5 and shows bad performance. Is there a discrepancy in performance on plain Web pages as well, or just Cordova?

**Comment by mtamony** [comment]
@gabrielschulhof I uploaded the project to GitHub though I'm not sure it is correct or will work. Hopefully it will. If you swap out 1.4.0 and 1.4.5 in the www/js folder and open the index.html file you should see the issue.

https://github.com/mtamony/ios/tree/master/www

**Comment by Ruffio** [comment]
@mtamony can you make a jsbin sample showing the issue?

**Comment by apsdehal** [comment]
Kindly reopen this after providing a suitable fiddle for comparison. Use this as template: http://jsbin.com/huvoraba/1/edit. Thanks.
