### ISSUE TITLE
"pageshow" trigger before panel "complete" when changing page from panel

### ISSUE THREAD

**Issue by magourex** [jquery/jquery-mobile#7963]
I have no success to write an example on JsFiddle
my probleme is, panel does not open or close correctly after many page changes.
I am using two externals panels (see https://github.com/jquery/jquery-mobile/issues/7236 it is similar issue)
with jqm1.4.5

I will try to explain what is wrong.
When panel close the function _closePanel is called see the code below:
```javascript
if ( !immediate && $.support.cssTransform3d && !!o.animate ) {
	( self._wrapper || self.element )
		.animationComplete( complete, "transition" );
} else {
	setTimeout( complete, 0 );
}
```
in my case "complete" function will be called after the reset of _opendPage when pageshow event:
```javascript
this._on( this.document, {
	"pageshow": function() {
		this._openedPage = null;
		this._getWrapper();
	}
});
```
however "complete" fonction need to remove every classes in the previous closed page (need to set _openedPage to null after "complete" call)

To resolve this issue i just add setTimeout in reset function after pageshow event. See the code below:
```javascript
this._on( this.document, {
	"pageshow": function() {
		setTimeout(function(){
			self._openedPage = null;
			self._getWrapper();
		}, 0);
	}
});
```

**Comment by gabrielschulhof** [comment]
Does the same problem happen when you use the latest jQuery Mobile from git?
http://code.jquery.com/mobile/git/jquery.mobile-git.css
http://code.jquery.com/mobile/git/jquery.mobile-git.js

**Comment by gabrielschulhof** [comment]
The reason I ask is that I landed some fixes for panel that deal exactly with the problem where the panel tracks the wrong page.

**Comment by magourex** [comment]
I don't know i will try it next monday.

**Comment by magourex** [comment]
No success to use the lastest JQM from git with my application. i have problems with "tap" event on button but this has nothing to do with my panel issue.
However i read the code and usage of new variable "currentPage" in panel widget close function (the code you add in lastest jqm) seem to resolve this issue.

**Comment by gabrielschulhof** [comment]
@magourex right, that's the modification. Well, if the bug proves to still be present, please reopen this issue or file a new one, referring to this issue. We'll have a look then. Thanks for reporting!
