### ISSUE TITLE
Popup Open creates exception in IE with JQM 1.4.5 if document.activeElement is null

### ISSUE THREAD

**Issue by salluvada** [jquery/jquery-mobile#7968]
Browser : IE
jQuery Mobile version : 1.4.5

Issue : In IE browser, when a popup is being opened, if the document.activeElement is null, the _safelyBlur method is throwing an exception. So if you haven't clicked on any control or tabbed to any control on a html page, after the page is launched, the document.activeElement is null and due to this the exception is raised. How ever if you click/touch anywhere on the body, the document.activeElement is set to a value and this exception is not raised.

Below is the code from jsbin. Donot run it in jsbin as you cannot reproduce this error. You need to simply copy the html, put it in a .html file and place it in a virtual directory in iis/any other webserver and load it from there. 

http://jsbin.com/nivozeniwe/1/watch?html,output 

Screen Shot: https://onedrive.live.com/redir?resid=F5B706029F07E38E!6225&authkey=!AEg6QqUjyEogrDQ&v=3&ithint=photo%2cjpg

**Comment by gabrielschulhof** [comment]
What version of IE? Also, can you please try with the latest code from master? http://jsbin.com/xiyete/1/

**Comment by salluvada** [comment]
The latest code you gave me is also giving the same exception. 

The issue is occurring in IE 11,10,9,8 as far as I tested. This issue doesn't occur in Chrome because by default in Chrome, the document.activeElement is set to body.

**Comment by gabrielschulhof** [comment]
OK, I see it now. Reproduced.

**Comment by gabrielschulhof** [comment]
This will be fixed once the [implementation](https://github.com/jquery/jquery-mobile/pull/7927) of ```$.mobile.safelyBlur()``` lands, fixing this and #1560.
