### ISSUE TITLE
Native multiple select issue > iOS 8.x (only iPhone) 

### ISSUE THREAD

**Issue by csiszarattila** [jquery/jquery-mobile#7971]
There is an issue with selects using data-native-menu="true" and multiple="multiple" options under iOS 8.x. If you unselect a selected item it makes selected whatsoever. However it only affects iPhones, I cant reproduce this error on an iPad.

HTML:
http://jsbin.com/degujowura/1/edit?html,output

Steps To reproduce issue:
Select 1st Option
Select 2nd Option
UnSelect 1st Option

Results:
After closing select only the 'Select 1st Option' would be selected

Excepted results:
After closing select only the 'Select 2nd Option' would be selected

**Comment by gabrielschulhof** [comment]
I'm afraid there's nothing much we can do about it. This problem also happens with plain js: http://jsbin.com/xudaxo/2/

**Comment by gabrielschulhof** [comment]
I've filed a bug with Apple: 19901849
