### ISSUE TITLE
Unable to get property 'nodeName' of undefined or null reference

### ISSUE THREAD

**Issue by H2Os** [jquery/jquery-mobile#7978]
Very niche issue which appears to be limited to IE:

JavaScript runtime error: Unable to get property 'nodeName' of undefined or null reference

When displaying a popup using .popup('show') the error above is thrown in _safelyBlur, called from _openPrerequisitesComplete when this.document[ 0 ].activeElement is null.

http://jsbin.com/banaqi/1

Run in IE with the F11 dev tools open (also occurs in Visual Studio when in debug mode).

**Comment by gabrielschulhof** [comment]
This will be fixed when https://github.com/jquery/jquery-mobile/pull/7927 lands.

**Comment by hkt01** [comment]
Is this supposed to be fixed? Because I'm still experiencing the mentioned issue.

**Comment by H2Os** [comment]
I think it's due in 1.5 - in the meantime, I have been using this workaround:

    //Fix for nodeName undefined error on IE
    $.widget("mobile.popup", $.mobile.popup, {
        _safelyBlur: function (currentElement) {
            try {
                this._super();
            } catch (ex) {
            }
        }
    });

**Comment by hkt01** [comment]
Thanks, I'll try that!

**Comment by karmatom** [comment]
H20s - You sir are awesome!  Thank you; your fix resolved my IE popup issue.

**Comment by ponolson** [comment]
@H20s - worked for me as well.  Thanks a ton!

**Comment by cofetti** [comment]
Still getting this error in IE 10, but only on one of my several popups.
Good thing the fix works, thank you.

**Comment by pstanton** [comment]
still a problem in 1.12.4
