### ISSUE TITLE
Panel push/reveal won't work on tabs

### ISSUE THREAD

**Issue by Daytron** [jquery/jquery-mobile#7979]
Hello,
Sorry if this is brought up before, but I couldn't find it anywhere here if there is one. I got an external panel working on multiple pages and push/reveal transition works fine. But a page with only data-role tabs, won't work at all, it just overlays the page. 

I have setup something like this:
http://jsfiddle.net/wt7w8ex7/1/

My question is, is this a known bug? I am using the latest release. How do you make page with tabs transition to reveal/push?  Any help?

**Comment by kapilgarg1996** [comment]
Its not actually a bug. Jquery-mobile panels work on a page and its content.If you don't specify what part of a page your tabs are in then the problem will occur.Just include the tabs widget in the content part of the page and what you will get is what you want.Here is the jsfiddle example..
http://jsfiddle.net/wt7w8ex7/6/
I just included the tabs in data-role="content" division and its working fine.

**Comment by Daytron** [comment]
That makes sense. Cheers
