### ISSUE TITLE
two clicks needed on select buttons to open dialog page

### ISSUE THREAD

**Issue by louisdoe** [jquery/jquery-mobile#7982]
I am using JAM 1.4.5 (and tried with 1.4.3) and Phonegap Build 3.6.3, and the first click on the select buttons do not open the dialog page. I have two click a second time to get the dialog open.

Can you help me figure this out ?

**Comment by kapilgarg1996** [comment]
Can you specify your issue more clearly.? A jsfiddle or jsbin demo would help to understand the isuue easily..

**Comment by Ruffio** [comment]
No response/clearification in one month. Should this be closed because of stalling?
