### ISSUE TITLE
show-value tooltip extension is not working for mini slider

### ISSUE THREAD

**Issue by kapilgarg1996** [jquery/jquery-mobile#7990]
The data-show-value="true" option is not working for mini slider. I found this issue on the demos page. 
<a href="http://demos.jquerymobile.com/1.4.5/slider-tooltip/">Slider Tooltip Demos</a>. Also i tried to change the user agent and create a replica of code in jsfiddle but nothing helps.
Here is the <a href="http://jsfiddle.net/9o2aqqwk/">jsfiddle example</a>

**Comment by gabrielschulhof** [comment]
The value is omitted from the mini slider handle intentionally - because it wouldn't fit.
