### ISSUE TITLE
Slider: Fixing styling

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#7991]
Here are the issues:
- Track overlaps input in mini version. This is caused by the commit that was supposed to fix #6795 but didn't.
- Tooltip doesn't show when you click on the track
- When both the handle text and the tooltip are turned on, the handle text disappears when you press down on the handle, but then reappears when you start dragging.

**Comment by kapilgarg1996** [comment]
The first issue which you described "Track overlaps input in mini version. This is caused by the commit that was supposed to fix #6795 but didn't.". This is happening only on the demos site. I ran the same code in jsfiddle and it is working correct there.
http://jsfiddle.net/tmjenmpy/

**Comment by gabrielschulhof** [comment]
Interesting. It's also happening in the tests I wrote, which do not use the demo CSS.

**Comment by gabrielschulhof** [comment]
The bug was introduced between 1.4.4 and 1.4.5, IINM.

http://jsbin.com/kupozu/1/ shows 1.4.5 and
http://jsbin.com/kupozu/2/ shows master.

**Comment by gabrielschulhof** [comment]
@kapilgarg1996 The reason your link works is because it includes jQuery Mobile 1.4.2. The regression was introduced in 1.4.5.

**Comment by kapilgarg1996** [comment]
oh okayy..
