### ISSUE TITLE
modal panel, mousedown events and older android browser.

### ISSUE THREAD

**Issue by HolgerHees** [jquery/jquery-mobile#7996]
on older android browsers like the non chrome based webkit browsers the "mousedown" event in the panel.js => _createModal: function should be replaced with an click event. Otherwise the clickevent will be delivered to the underlying dom elements like a link element.

on iOS based webkit browsers and on newer chrome browsers everything works as expected.

**Comment by arschmitz** [comment]
@HolgerHees please see our contributing guidelines https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and create a reproducible test case demonstrating the issue using our jsbin template linked from there. Closing as incomplete.
