### ISSUE TITLE
Default clear button of date input type appears in webkit based browsers

### ISSUE THREAD

**Issue by kapilgarg1996** [jquery/jquery-mobile#8001]
The default clear button of html date input type appears in webkit based browsers like chrome and opera.
Here is the jsfiddle example http://jsbin.com/vobigiteto/1/edit
Also it can be seen in demos page http://demos.jquerymobile.com/1.4.5/textinput/

**Comment by arschmitz** [comment]
@kapilgarg1996 the jsbin you link to does not even contain a date input. I do see the double clear in the demos.

**Comment by kapilgarg1996** [comment]
@arschmitz  Oh sorry for that..wrong example..I have updated the link
