### ISSUE TITLE
Panel: Split Button

### ISSUE THREAD

**Issue by jeffkevin** [jquery/jquery-mobile#8003]
Feature Request: Split button inside the panel, with a small button on the right acts like a collapsible and the button on the left as a link.

![Sample Menu](http://s30.postimg.org/jw15hl8kh/Menu.jpg)

**Comment by kapilgarg1996** [comment]
Can you please provide a test page or any jsbin/jsfiddle example

**Comment by gabrielschulhof** [comment]
I'd definitely appreciate an illustration ...

**Comment by arschmitz** [comment]
No response to request for more information closing
