### ISSUE TITLE
Panel Disappears When Leaflet Map is in Main Content (IE 10,11)

### ISSUE THREAD

**Issue by roemhildtg** [jquery/jquery-mobile#8004]
1. Issue description
When using a Leaflet map with jQuery Mobile Panels, dragging on the map, causes the panel to disappear. 

2. Test page 
http://jsfiddle.net/08zn1cmt/

3. Steps to reproduce
Open the panel using the toggle toolbar button. Drag on the map.

4. Expected outcome
Panel should not be hidden because `data-dismissable="false"` on the panel widget

5. Actual outcome
Panel hides itself and must be toggled twice to become visible again

6. Platforms/browsers (including version) and devices tested
Internet explorer 10 and 11 appear to have this bug.

7. jQuery Mobile and jQuery core version used
jQuery - 1.9.1
jQuery Mobile -1.4.5

Not sure if I am missing something obvious here, or if there is a leaflet bug instead, but I would appreciate any suggestions.

**Comment by Ruffio** [comment]
Has is worked before? If yes in what version?

Venlig hilsen Rasmus Christiansen

2015-03-16 14:18 GMT+01:00 roemhildtg <notifications@github.com>:

**Comment by roemhildtg** [comment]
I have not tried with other versions.

**Comment by gabrielschulhof** [comment]
This may be a manifestation of #6925. @roemhildtg can you please try with the git version of jQuery Mobile as that contains a fix to #6925.

**Comment by gabrielschulhof** [comment]
BTW: I cannot reproduce the problem via the jsfiddle.

**Comment by roemhildtg** [comment]
I just updated the JSFiddle to the git js and css. http://jsfiddle.net/08zn1cmt/1/

I've looked into the issue a little more, and perhaps its an issue with the css I have included. I'm trying to achieve a result where the map fills the ui-content div completely, maybe there is a better way to do this. 
```css
.ui-content{
    position: absolute;
    top: 40px;
    right: 0;
    bottom: 0;
    left: 0;
    padding: 0 !important;
}
```

If not, here's some more details that I could glean from the dev tools in IE 11. The panel itself still has a class of ui-panel-open, it just gets bumped off to the left side when the map is dragged or clicked. 

Before being clicked:
![capture](https://cloud.githubusercontent.com/assets/5471079/6698301/90802a42-ccc5-11e4-97b1-18ef1226ffe9.PNG)

After:
![after_drag](https://cloud.githubusercontent.com/assets/5471079/6698368/02e64c1a-ccc6-11e4-8b87-23c9e4f82a67.png)

**Comment by roemhildtg** [comment]
After removing the css, that was formatting the ui-content, I was able to get what I need by using a jquery resizing function like this: 
```javascript
            $('.ui-content, #map').height($(window).height() - $('#mapPage .ui-header').height());
            $('.ui-content, #map').width($(window).width() - $('#left-sidebar').width());
            if (map) {
                map.invalidateSize();
            }
```

It must just be a conflict with the css that I had borrowed from another site.
