### ISSUE TITLE
string.isNullOrWhitespace

### ISSUE THREAD

**Issue by weitzhandler** [jquery/jquery-mobile#8007]
Please implement a string function that verifies a string contains at least one non-whitespace character.

**Comment by Ruffio** [comment]
In what way is this specific related to jQM?

**Comment by weitzhandler** [comment]
It's not.
I'm wishing it to be.

**Comment by weitzhandler** [comment]
Oh I now realize my mistake, wrong repo should be on regular jQ, sorry.

**Comment by arschmitz** [comment]
@weitzhandler just out of curiosity is there something with just checking `somestring? !!somestring.trim() : false`

**Comment by weitzhandler** [comment]
You're right, and not only that, but it's the wrong repo anyway.
Sorry and thanks.
