### ISSUE TITLE
Easy manipulation of data-* or data-val-* attributes

### ISSUE THREAD

**Issue by weitzhandler** [jquery/jquery-mobile#8009]
Hi,

Please implement an easy way to access `data-*`, `data-val-*`, or `aria-*` attribute names.

For example `$(this).attrs('^data-val-range').remove();` would remove extract the three range attributes from this element:

    <input data-val-range-min="1" data-val-range-max="10" data-val-range="Oops!"/>

Please see [this](http://stackoverflow.com/questions/29074077/jquery-select-when-attribute-name-starting-with) and [this](http://stackoverflow.com/questions/26657398/jquery-how-to-select-value-by-attribute-name-starts-with).

Currently I'm doing it like this:

    $(this).removeAttr("data-val-length data-val-length-min data-val-length-max");

Thanks!

**Comment by kapilgarg1996** [comment]
Whats the use of removing all the data- attributes btw ?

**Comment by weitzhandler** [comment]
I'm sorry but I didn't know about the `.data()` function.
I believe this feature is redundant.
