### ISSUE TITLE
Popup: Lightbox demo on IE8 - icon is outside the button

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#8039]
The ✕ of the close button is in the top left corner of the lightbox popup. The close button itself is correctly placed.

**Comment by gabrielschulhof** [comment]
... on IE8.

**Comment by kapilgarg1996** [comment]
@gabrielschulhof I tried to reproduce the issue using user-agent switcher on chrome and switched ti IE8 but its not showing any error regarding the lightbox popup demo. Does the user-agent switcher not a good way to check the issue..??

**Comment by arschmitz** [comment]
@kapilgarg1996 the user agent switcher does just that switches user agents to fool browser sniffing it does not emulate the rendering of capabilities of ie8 in any way.

**Comment by apsdehal** [comment]
I see that this issue has been fixed. Closing.
![image](https://cloud.githubusercontent.com/assets/3616806/15807453/4feb2858-2b7c-11e6-8cf8-3316638624f5.png)
