### ISSUE TITLE
Header width extends outside body when using default slide transition

### ISSUE THREAD

**Issue by clehnert-psl** [jquery/jquery-mobile#8041]
This is happening in Safari on iOS with the iPhone4s, iPhone5, iPhone6, and the iPhone6Plus (iOS simulator and actual devices). I can't reproduce on Android or iPad.

[Full screen example for mobile viewing](http://jsbin.com/runuxu/3/)

**To reproduce on an actual iPhone or in iOS simulator:**

1) Click "Go to step 2" to slide to Page 2

2) Reload the page by tapping the circle arrow button on the right of the address bar in mobile Safari.

The page title in the header bar is now shifted to the right and is not centered. It's actually wider than the actual body or html width. This only happens when setting the default page transition like this:

`$.mobile.defaultPageTransition = 'slide';`

The margin on the h1.ui-title is lengthening, but there doesn't seem to be any logical reason for this.

[JSBin example showing HTML and JS](http://jsbin.com/runuxu/3/edit?html,js,output)

(Using jQuery Mobile 1.4.5)

**Comment by gabrielschulhof** [comment]
Is this anything like #7797?

**Comment by clehnert-psl** [comment]
Yes, this looks to be the same issue.

--------------------------------------------------------------
*Charles Lehnert*
UI UX Development Lead
P\S\L Group America
--------------------------------------------------------------


On Mon, Mar 30, 2015 at 11:12 AM, gabrielschulhof <notifications@github.com>
wrote:

> Is this anything like #7797
> <https://github.com/jquery/jquery-mobile/issues/7797>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/jquery-mobile/issues/8041#issuecomment-87717939>
> .
>

-- 


The information in this communication may be confidential and/or privileged 
and is intended only for the person(s) to whom it is rightfully addressed. 
If you are not the intended recipient, you may not read, copy, use or 
disclose any information contained in or attached to this communication. If 
you have received this communication in error, please notify the sender 
immediately and delete the entire original communication, including any 
files or documents attached to it, without reproducing, distributing or 
retaining copies of any part thereof.


The views or opinions expressed may solely be those of the author and not, 
unless specifically stated, reflect those of our group or of any of the 
companies in our group.


Please note that we reserve the right to monitor electronic communications 
passing through our network

**Comment by apsdehal** [comment]
Closing as duplicate.
