### ISSUE TITLE
Transitions: Tests fail with core from git

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#8044]
Something must've changed in core, because our transitions tests are failing with core from git.

**Comment by kapilgarg1996** [comment]
Transitions are going to be enhanced and changed as its a gsoc project. Hence new tests will be written.

**Comment by arschmitz** [comment]
@kapilgarg1996 this is a failure due to a bad test assumption this has nothing to do with potential future changes to our transitions or GSoC
