### ISSUE TITLE
popup window closes automatically when initiated via javascript

### ISSUE THREAD

**Issue by rhysryan** [jquery/jquery-mobile#8045]
I have noticed that in my Safari on a MAC, a pop-up window automatically closes when it is opened via JavaScript.  All seems to work well in Chrome and Firefox.  This is related to issue #5794.

Here's my environment:
- MAC Yosemite 10.10.2
- Safari 8.0.4
- jQuery 2.1.3
- jQuery Mobile 1.4.5

Here's the JavaScript to open the popup:
`$("#refreshPopup").popup( "open" );`

Here's the main line of the popup itself:
`<div data-role="popup" id="refreshPopup" data-overlay-theme="b" data-theme="b" data-dismissible="true" data-history="false" style="max-width:400px;">`

To get around the problem,in jquery.mobile.1.4.5.js, I commented out line 11137:
`self._bindContainerClose();`

I really hate to do this but I couldn't go back to 1.3.2, which seems to be the last version that this issue was fixed.  I tested this on my MAC with Firefox, Safari and Chrome and no more problems.  I also tested on Safari on IOS 8 and Android with Chrome without any issues.  I also tested on Windows 8.1 with the newest version of IE, Safari, Chrome and Firefox and the fix seemed to work.  I know I probably broke something else but I really needed this to work.

**Comment by gabrielschulhof** [comment]
@rhysryan if you're opening the popup from a click handler, you must prevent default on the click event. Can you modify our [template](http://jsbin.com/huvoraba/1) to create a test case illustrating the problem?

**Comment by rhysryan** [comment]
Hello.

No, I am not using a click handler.  In my pageshow function I am just 
calling the open method.

Thanks.



gabrielschulhof wrote:
>
> @rhysryan <https://github.com/rhysryan> if you're opening the popup 
> from a click handler, you must prevent default on the click event. Can 
> you modify our template <http://jsbin.com/huvoraba/1> to create a test 
> case illustrating the problem?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jquery/jquery-mobile/issues/8045#issuecomment-86599747>.
>


Rhys
------------------------------------------------------------------------
"Sometimes it does take a rocket scientist to make a movie!"

**Comment by kapilgarg1996** [comment]
@rhysryan The issue you referenced provides a demo http://jsbin.com/onuduw/5
Are you trying to do the same..?

**Comment by rhysryan** [comment]
@kapilgarg1996 Yes, basically the same.  I even took that exact code of that demo, which worked with 1.3.2, and pointed it to 1.4.5.  The result was that the popup no longer worked.

**Comment by gabrielschulhof** [comment]
Yeah, there's a spurious navigate event which closes the popup. This used to be a problem in Chrome too, but it seems it got fixed. Not so in Safari.

**Comment by kapilgarg1996** [comment]
@gabrielschulhof I don't think it has been fixed in chrome.
http://jsbin.com/rifuha/1/edit

**Comment by gabrielschulhof** [comment]
@kapilgarg1996 It has been. You must define the mobileinit handler before you refer to jQuery Mobile via a script tag, because mobileinit is fired from one of mobile's outermost IIFEs: http://jsbin.com/vohozu/1/

**Comment by khaanYoufoot** [comment]
I was calling 'open' method within a function and this function was beign called by  click event. Applying preventDefault() on that click event fixed the issue for me. (and the issue was only seen in android 4.3 default stock browser, not chrome, not even default stock browsers of any other android version).

Thank you @gabrielschulhof

**Comment by chaintan17** [comment]
I also have this problem too. Is there anyway to fix this problem yet?

**Comment by arschmitz** [comment]
@chaintan17 this is already fixed on master thats why its closed.
