### ISSUE TITLE
Navigation: Implementation of navigate event must properly attach to/detach from underlying events

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#8050]
Currently the navigate event attaches to popstate/hashchange when the first call to ```setup()``` is made, and sets a flag indicating that it has attached. Upon subsequent calls to ```setup()``` it merely checks the flag to make sure it has already attached.

We need to change this to attach a handler upon ```setup()``` and detach <em>that same handler - <strong>identified exactly by means of its function pointer</strong></em> upon ```teardown()```.

**Comment by apsdehal** [comment]
Closing as fixed on 1.5-dev.
