### ISSUE TITLE
Add an 'afterposition' event to popup

### ISSUE THREAD

**Issue by jodator** [jquery/jquery-mobile#8053]
It would be nice if "popup" have an event triggered after doing positioning.

Right now I have to do `setTimeout` in [beforeposition event](http://api.jquerymobile.com/popup/#event-beforeposition) do do some calculation after the dialog has changed position.

**Comment by gabrielschulhof** [comment]
@jodator you can solve this with an extension:

```JS
$.widget( "mobile.popup", $.mobile.popup, {
	_reposition: function() {

		// Do whatever popup does to reposition itself
		this._super();

		this._trigger( "afterposition" );
	}
} );
```

Also, if you need to perform this calculation for every popup in your application, you can just perform it right after ```this._super()``` and forego triggering ```afterposition``` altogether.

If this still does not address your concerns, please feel free to reopen the issue.

**Comment by jodator** [comment]
Thanks for that @gabrielschulhof. This probably will solve this, but I've added this request in case some else would want such event also I don't like to mess with external lib's "_private" methods in case something changes.

**Comment by gabrielschulhof** [comment]
@jodator OK, that's fair. I'll add this to our list of feature requests.

**Comment by gabrielschulhof** [comment]
OK, so it's already added :)
