### ISSUE TITLE
Navigation: Deep linking doesn't work on OSX Yosemite Safari 8.0 on Browserstack

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#8056]
http://jsbin.com/jobaho/4.html#/wubowa/4.html&ui-state=dialog
Should result in the start page (wubowa) being shown. It's shown, but then it transitions to the redirect page (jobaho).

**Comment by arschmitz** [comment]
I cannot confirm this on OSX Yosemite with Chrome? what are you seeing this on? OSX is pretty broad i doubt this is a general OSX issue across all browsers?

**Comment by gabrielschulhof** [comment]
Sorry! Safari.

**Comment by arschmitz** [comment]
@gabrielschulhof What OSX? As i said i cannot confirm on OSX Yosemite Safari 8

**Comment by gabrielschulhof** [comment]
OK, weird. I was using Browserstack.

**Comment by gabrielschulhof** [comment]
OK, I accidentally changed the jsbin link to point to my local copy which already has the fix. I'll update the test page.

**Comment by arschmitz** [comment]
@gabrielschulhof Well browserstack has 5 versions of OSX which one?

**Comment by gabrielschulhof** [comment]
Yosemite.

**Comment by gabrielschulhof** [comment]
http://jsbin.com/jobaho/4.html#http://jsbin.com/wubowa/4.html&ui-state=dialog

**Comment by gabrielschulhof** [comment]
The above link should reproduce the problem on Safari 8 running on OSX Yosemite. It should reproduce with or without Browserstack, though I cannot test without Browserstack.

**Comment by gabrielschulhof** [comment]
Dang! The link is still wrong!

**Comment by arschmitz** [comment]
@gabrielschulhof the original test page does not point to a local copy it points to git and works fine in OSX Safari 8 Yosemeti and browser stack the updated # 4 jsbin is exactly the same and still works fine both places

**Comment by gabrielschulhof** [comment]
OK, then I must be dreaming. I'll make a video.

**Comment by gabrielschulhof** [comment]
https://www.youtube.com/watch?v=B_-VLTu4pjQ

**Comment by arschmitz** [comment]
@gabrielschulhof there is indeed a transition flash there but the URL at the end if you check it is http://jsbin.com/wubowa/4.html&ui-state=dialog which is what it should be.

**Comment by gabrielschulhof** [comment]
Right, but the page isn't. It's the redirect page, not the start page.

**Comment by arschmitz** [comment]
You never show that in anyway way in your test page or video since they are identical. and you never show the inspector to show this either. However the whole thing is cause because your url is invalid

http://jsbin.com/jobaho/4.html#http://jsbin.com/wubowa/4.html&ui-state=dialog should be http://jsbin.com/jobaho/4.html#http://jsbin.com/wubowa/4.html?ui-state=dialog

**Comment by gabrielschulhof** [comment]
I've fixed the URL in the original post, and I've reproduced the issue with that URL on an actual, physical iOS 6.1.2 iPod Touch.

It's not reproducible 100% of the time, because I suspect there's a race condition between our initial redirect when encountering an initial URL that requires an Ajax page load, and the arrival of the spurious popstate that Webkit produces.

The fix for this issue, which I already have handy, also fixes a problem that arises in 1.5-dev after you remove the defaults dependency on json!../package.json. This causes the load order to change when using requirejs and, for some reason, causes the phantomjs initial popstate to break our redirect sequence tests.

That's how I got the idea of testing this on Safari - since it's the only Webkit-based browser (aside probably from old Android).

I've also created a video illustrating how a URL of a form <domain>/path/to/file1.html#/path/to/file2.html&ui-state=dialog might arise. Hint: Alice runs an app on IE8 which does not support pushState, copies the location and sends it to Bob, who's running Safari.

**Comment by gabrielschulhof** [comment]
https://www.youtube.com/watch?v=X5RK3MGhdWE

**Comment by gabrielschulhof** [comment]
The root cause seems to be that, while we identify the spurious popstate in navigator, we do not prevent default on it, because the location.href at that time is not the same as the location.href we record duing the loading of navigator. We then do a squash() from init, causing the location.href to change. So, when the spurious popstate arrives, the location is no longer of the form path1/path2, because of the squash() we ran from init, so the default for the spurious popstate is not prevented, causing a navigate event, which pagecontainer handles incorrectly.

**Comment by gabrielschulhof** [comment]
I'd sure like to see someone else reproduce this issue though ...

**Comment by gabrielschulhof** [comment]
Just to recap: Steps to reproduce:

1. Visit http://jsbin.com/jobaho/4.html#/wubowa/4.html&ui-state=dialog
2. Read the title in the header

If you see "Redirect", the bug is present.
If you see "Start Page", the behaviour is correct.

**Comment by gabrielschulhof** [comment]
Safari 7/Mavericks on Browserstack also reproduces the issue.

**Comment by jaspermdegroot** [comment]
I tested on OS X Yosemite 10.10.2 / Safari 8.0.4 and don't see the issue (title is "Start Page").

**Comment by gabrielschulhof** [comment]
@jaspermdegroot  Can you try iOS?

**Comment by gabrielschulhof** [comment]
@jaspermdegroot Also, can you try loading the URL multiple times?

**Comment by arschmitz** [comment]
well after 40+ reloads i managed to break it some how this is seeming pretty obscure. i feel like if you reload any page with enough JS going on enough times in a tight loop something will hiccup once in a while lol

**Comment by gabrielschulhof** [comment]
Well, it's pretty reliable on iOS 6.1.2 on my iPod. Have you tried multiple iDevices? Also, a straight-up reload is not enough, because it does the replace state. You actually need to paste in the URL and hit Enter repeatedly.

**Comment by arschmitz** [comment]
only iphone 6 ios 8 but yes i was repasting the url each time

**Comment by jaspermdegroot** [comment]
The first time I tested I just clicked on the link. When I copy and paste the url and hit enter I can easily reproduce. Every time I briefly get to see the "Start Page" and then the "Redirect" page.
This is still on MBP OS X Yosemite 10.10.2 / Safari 8.0.4. On Chrome on the same machine I always get the "Start Page".
Haven't tested on iPhone and iPad yet.
