### ISSUE TITLE
Footer(Fixed) lift up "temporary" for a  while(With JQuery UI easing effect), deleting element from swipe delete

### ISSUE THREAD

**Issue by 05bca054** [jquery/jquery-mobile#8057]
Hello,

I recently encounter that deleting element from JQuery list "http://localhost/proj_x/js/jqm/demos/swipe-list/#demo-page" with jquery UI easing effect For example "slideUp" as shown below can up lift footer for a while UI effect completes.

function confirmAndDelete_coupon( coupon_id ,listitem, transition ) {
				//alert("confirm and delete"+ listitem + " : " + transition);
				// Highlight the list item that will be removed
				listitem.children( ".ui-btn" ).addClass( "ui-btn-active" );
				// Inject topic in confirmation popup after removing any previous injected topics
				$( "#confirm .topic" ).remove();
				listitem.find( ".topic" ).clone().insertAfter( "#question" );
				// Show the confirmation popup
				$( "#confirm" ).popup( "open" );
				// Proceed when the user confirms
				$( "#confirm #yes" ).on( "click", function() {
					// Remove with a transition							
					coupon.deleteExpires(coupon_id);
					listitem.slideUp('slow', function(){
	                	listitem.remove();
					});
					$( "#list" ).listview( "refresh" );
					
					$( "#confirm" ).popup( "close" );
					
				});
				// Remove active state and unbind when the cancel button is clicked
				$( "#confirm #cancel" ).on( "click", function() {
					listitem.children( ".ui-btn" ).removeClass( "ui-btn-active" );
					$( "#confirm #yes" ).off();
					$( "#confirm" ).popup( "close" );
				});
			}

Thanks in advance for your time and consideration.

Feel free to ask for more information about issue if needed.

-Niks

**Comment by kapilgarg1996** [comment]
I couldn't reproduce the issue..
see this jsbin demo http://jsbin.com/gomijogaca/1/edit?js,output
check if it is what you want..
Click the 'X' button to open the popup and the listitem will slide up and footer won't lift up..There is no issue at all..
