### ISSUE TITLE
Jquery Mobile div Data role Panel not getting displayed propely

### ISSUE THREAD

**Issue by ravikiranv** [jquery/jquery-mobile#8060]
http://jsfiddle.net/jWaEv/13/

When you run this fiddle

Click on the square box on the right side of the locations (A Panel is getting displayed and its working fine)
The issue is that .

When you click on the Delivery and click on the square box on the right side of the locations (The Panel gets displayed but its not working properly (not getting closed and not aligned properly))

Could you please let me know how to fix this ??

To solve the i tried calling the same above panel that is rightpanel when clicked on the Locations square box on the right side , but this did not solve the issue .

$(document).on('click', 'a[href=#rightpanel_2]', function(event) {
        $("a[href=#rightpanel]").trigger("click");
    });
could you please let me kno how to resolve the issue ??

Thanks in advance

**Comment by kapilgarg1996** [comment]
Firstly, your provided fiddle is totally broken. Secondly, why are you attempting to hide panel wrapper ?
Thirdly, i created a fiddle to take care of what you want and its working perfectly. Check it out http://jsfiddle.net/kapilgarg1996/jWaEv/16/
If you still have some issue then please provide a test page according to the jquery-mobile jsbin template.

**Comment by gabrielschulhof** [comment]
@ravikiranv ... and please either reopen this issue or file a new one.
