### ISSUE TITLE
btn-down applied when scrolling on some browsers in both android and iOS

### ISSUE THREAD

**Issue by ceblanda** [jquery/jquery-mobile#8064]
Load the listview demo page - http://demos.jquerymobile.com/1.4.5/listview/ - in the default browser on an android device or safari or chrome on an iPhone / iPod.  Scroll down to "Linked" item, then continue scrolling but put your finger on one of the list items to scroll.  The item gets the btn-down class while you scroll and the btn-visited class after.

Run Chrome on the android device and do the same test, the classes are not applied.  This is the behavior I would expect.

**Comment by apsdehal** [comment]
Not able to reproduce on Safari 9 on iOS.
