### ISSUE TITLE
flipswitch destroy throws exception

### ISSUE THREAD

**Issue by ramihaly** [jquery/jquery-mobile#8071]
Calling method destroy (https://api.jquerymobile.com/flipswitch/#method-destroy) on a flipswitch control throws an exception:

Object doesn't support property or method 'removeClass'
http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.js line 9408: this.removeClass( "ui-flipswitch-input" );

**Comment by arschmitz** [comment]
Thank you for reporting this it is indeed a bug that line should be `this.element.removeClass( ... );`
