### ISSUE TITLE
Demos: pages-multi-page and pages-single-page wrongly refer to CDN versions

### ISSUE THREAD

**Issue by dforsi** [jquery/jquery-mobile#8117]
Text in the pages-multi-page and pages-single-page demos say "All the CSS and JS is linked to the jQuery CDN versions" but instead they link to relative URIs:
``` HTML
<link rel="stylesheet" href="../../css/themes/default/jquery.mobile.css">
<link rel="stylesheet" href="../_assets/css/jqm-demos.css">
<link rel="shortcut icon" href="../favicon.ico">
<script src="../../external/jquery/jquery.js"></script>
```
https://github.com/jquery/jquery-mobile/blob/master/demos/pages-multi-page/index.html
https://github.com/jquery/jquery-mobile/blob/master/demos/pages-single-page/index.html

**Comment by apsdehal** [comment]
Fixed in 1.5.
