### ISSUE TITLE
jQuery mobile breaks in Firefox when the webpage is included in an iframe with style "display:none"

### ISSUE THREAD

**Issue by zaoudis** [jquery/jquery-mobile#8120]
Environment: Firefox 37.0.1
Test page: http://www.chioshome.gr/jqueryMobileIframe.html

jQuery version: 1.8.3
jQuery mobile version: 1.4.5

In jQuery mobile non-minified:

Line 2103: supports = getComputedStyle &&
Line 2104: getComputedStyle( element, "" ).pointerEvents === "auto";

getComputedStyle( element, "" ) is null and since no check for that is applied it breaks

Same issue with jQuery mobile version: 1.3.2

**Comment by apsdehal** [comment]
Kindly provide a fiddle for easy testing of the bug according to contribution guidelines and reopen the issue.
