### ISSUE TITLE
Flipswitch wrapperClass setter not working

### ISSUE THREAD

**Issue by AlvinStanescu** [jquery/jquery-mobile#8125]
**Issue description** - Setting the wrapperClass for an already-created flipswitch using the option parameter does not work. Passing the wrapperClass into the constructor works fine. I used an input-based flipswitch.
**Test page** - http://output.jsbin.com/yonivugeqo
**Steps to reproduce** - Instantiate a new input-based flipswitch (possibly also reproduces for select-based flipswitches). After instantiating it, attempt to set the wrapperClass using the flipswitchDivElement by calling .flipswitch("option","wrapperClass","someClass").
**Expected outcome** - CSS class applied to the div, see example.
**Actual outcome** - No application of CSS class to the div.
**Platforms/browsers (including version) and devices tested** - Win8.1, Chrome
**jQuery Mobile and jQuery core version used** - latest (used issue template), initially found using jQuery Mobile 1.4.2

**Comment by kapilgarg1996** [comment]
@arschmitz Its happening because we aren't doing anything to update the wrapperClass in _setOptions().
Should it be changed or is it gonna deprecated in 1.5.0 ?

**Comment by apsdehal** [comment]
Deprecated in 1.5. Use classes options now.
