### ISSUE TITLE
Problem in page with popup component on windows phone 8 (only).

### ISSUE THREAD

**Issue by JonathasRodrigues** [jquery/jquery-mobile#8126]
Problem in page with popup component on windows phone 8 (only).
I'm using Cordova, jquery-2.1.1.min.js and Basic popup example http://demos.jquerymobile.com/1.4.5/popup/

Error : Object doesn't support property or method 'getAttribute'.

The problem may be comments on html pages and I found two comments from the popup component in jquery-mobile-1.4.5.js file.

Line 10402: placeholder: $( "<div style='display: none;'></div>" ),

Line 10416: .html( "" );

**Comment by arschmitz** [comment]
@JonathasRodrigues can you please create a simple test page recreating the problem using our jsbin test page http://jsbin.com/ofuhaw/1/edit. I understand it wont directly recreate since it wont be in cordova but we can use this to make sure we are using the exact same markup JS you are using

**Comment by apsdehal** [comment]
Closing due to missing jsbin. Reopen with that.
