### ISSUE TITLE
Demos: copy and paste the source code in utf8  encoding fail 

### ISSUE THREAD

**Issue by evilripper** [jquery/jquery-mobile#8127]
When I copy from view source from demos:

![popup jquery mobile demos](https://cloud.githubusercontent.com/assets/1646220/7470343/9479b78a-f31c-11e4-866b-3c053a2078cb.png)

If I paste it in utf-8 document there are ghost chars:

![screenshot 2015-05-05 11 41 57](https://cloud.githubusercontent.com/assets/1646220/7470355/aefcf0cc-f31c-11e4-9209-75e583253a8e.png)

In ANSI they appear

![screenshot 2015-05-05 11 46 30](https://cloud.githubusercontent.com/assets/1646220/7470349/a1598070-f31c-11e4-99c5-4e344989b94c.png)

This happens on Windows 7 and it is annoying because breaks the layout.

**Comment by jaspermdegroot** [comment]
I can confirm that the indentation is something other than actual whitespace. We use an external tool for the view source, but let's see if we can fix this anyway. It might take a while though before we have time to look into this.

**Comment by apsdehal** [comment]
Fixed in 1.5-dev.
