### ISSUE TITLE
No documentation for actually getting started

### ISSUE THREAD

**Issue by bradisbell** [jquery/jquery-mobile#8128]
I've been using jQuery Mobile on various projects for many years.  Yet, I can't find clear documentation anywhere on how to actually set up a page with jQuery Mobile initially.  Here are some steps I tried initially, to be used as a real-world example as how someone like myself might try to find the documentation:

1. I looked for "getting started" or something similar on the site at http://jquerymobile.com/.  I didn't find anything.

1. I Googled for "jQuery Mobile 1.4 Getting Started", landed on the demo home page, and saw, "New to jQuery Mobile? Get started by reading this introduction."  Unfortunately, the introduction didn't say anything at all about what to include on a fresh page, nor did it give any example.

1. I checked the API documentation at http://api.jquerymobile.com/, but there aren't instructions there either.

1. The "Resources" page at http://jquerymobile.com/resources/ is only a collection of ads for sites using jQuery Mobile.

1. I decided to check the "Download" page and eventually found a snippet for loading the CDN versions.  This works, but isn't clear to new users.  I know this because I answer this question for new users all the time.

What's lacking in current versions of jQuery Mobile is the "Quick Start" guide, such as this page for older versions:  http://demos.jquerymobile.com/1.2.0/docs/about/getting-started.html  The older documentation for jQuery Mobile was much better and enabled folks to get up and running quickly.  I suggest creating an updated version of this page and linking to it prominently.

Would such a page be welcomed if I created a pull request?

**Comment by arschmitz** [comment]
@bradisbell thank you for reporting this articles on getting started and other in depth topics like that all live on http://learn.jquery.com for getting started there is this http://learn.jquery.com/jquery-mobile/getting-started/ which is very similar to what you link.

**Comment by bradisbell** [comment]
Interesting... I've never seen that site.  Perhaps all that is needed then are some links.

**Comment by arschmitz** [comment]
Its linked from the top of each of the websites except for the demos, under support. If there are specific places you think we could use a link to it happy to have a PR

**Comment by kapilgarg1996** [comment]
@arschmitz there is a link on http://learn.jquery.com/jquery-mobile/getting-started/ which points to http://jquerymobile.com/demos/1.2.0/ I think that should be updated.

**Comment by arschmitz** [comment]
@kapilgarg1996 yes it should

**Comment by kapilgarg1996** [comment]
@arschmitz the update is going to be included in learn.jquery.com repo..So p.r. should be made for that repo.. right ?

**Comment by bradisbell** [comment]
"support" sounds like "paid support".  And in fact, even after having the learn.jquery.com link, I found that page by using the footer of the site rather than in the header.  "Learning Center" sounds like classes or paid tutorials.  I think the messaging you're going for isn't coming through.

In any case, a simple link to the quick start example, wherever it is hosted and maintained, from the API documentation and the demo home page would likely solve the problem completely.

**Comment by apsdehal** [comment]
Closing, as not directly related to source code repository of jQuery Mobile. Maybe a better place to open is api repo or learn repo, but not here.
