### ISSUE TITLE
In my applicatiion when i minimize the icons the grey gap is formed in the google map can anybody give the suggestion for this issue i am currently using tile map

### ISSUE THREAD

**Issue by SrikanthNode** [jquery/jquery-mobile#8129]

**Comment by jaspermdegroot** [comment]
@SrikanthNode - Please follow our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues) when reporting an issue. For support you can post in the forum. Thanks!
