### ISSUE TITLE
Custom select menu (v1.4.5) triggers some bug with  WP8.1 suspend/resume

### ISSUE THREAD

**Issue by ToniKorin** [jquery/jquery-mobile#8131]
Hello,

The env:
- Cordova Windows platform v3.8 for WP8.1 universal app (not WP8)
- jQuery Mobile v1.4.5

When the custom select menu is opened even once, my cordova app fails to suspend itself (gets killed) when switching to another app (the cordova pause event is also missing then) . If I use the native select menu (or not open the custom select menu), the suspend/resume of the app is working just fine.

Known issue?
Any workaround available?

Cheers,
 Toni

**Comment by ToniKorin** [comment]
The same workaround as for iOS9 helps:
https://github.com/jquery/jquery-mobile/issues/8262

    <script type="text/javascript" src="js/libs/jquery-2.1.3.min.js"></script>
    <script>
        $(document).bind("mobileinit", function(){
               $.mobile.hashListeningEnabled = false; // for select menu issues...
        });
    </script>
    <script type="text/javascript" src="js/libs/jquery.mobile-1.4.5.min.js"></script>

**Comment by apsdehal** [comment]
Not enough context available to reproduce the issue. A jsbin would be great, closing till then.
