### ISSUE TITLE
The virtual keyboard in the device hides the form inputs at the bottom of the page.

### ISSUE THREAD

**Issue by janey1986** [jquery/jquery-mobile#8132]
I'm using JQuery Mobile 1.4.5 to build a web app. I have found an issue which I'm sure is either a browser or JQM bug when using Google Chrome homescreen (fullscreen) mode in Android (v.4.4.2).

When I click on the "Click Here!!" collapsible header and select the text area, the keyboard appears but it hides the text input box, because it is on the lower half of the screen. This prevents the user from being able to see what they are typing, and from pressing "Submit", unless they minimise the keyboard.

When the keyboard opens, the textbox should be moved up, so it sits above the keyboard, and the page should be scrollable. This is the behaviour I expect and is what happens in Chrome web browser mode, and in iOS full screen and browser mode.

Any ideas on a work round for this? It makes sections of the app unusable!

      <!DOCTYPE html>
          <html>
	       <head>
		      <title>Test Page</title>
		
		  	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
			<meta name='apple-mobile-web-app-capable' content='yes' />
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<link rel="apple-touch-icon" href="apple-touch-icon.png" /> 
			<link rel="shortcut icon" href="apple-touch-icon.png" />
			<link rel="apple-touch-icon-precomposed" href="apple-touch-icon.png"/>
			
			<script src="./js/jquery.js"></script>
			<script src="./js/jqm1.4.5/jquery.mobile-1.4.5.min.js"></script>
			
			<link rel="stylesheet" href="./css/jqm1.4.5/jquery.mobile.external-png-1.4.5.min.css">
			<link rel="stylesheet" href="./css/jqm1.4.5/jquery.mobile.inline-png-1.4.5.min.css">
			<link rel="stylesheet" href="./css/jqm1.4.5/jquery.mobile.inline-svg-1.4.5.min.css">
			<link rel="stylesheet" href="./css/jqm1.4.5/jquery.mobile-1.4.5.css">
			<link rel="stylesheet" href="./css/jqm1.4.5/Theme.css">
			<link rel="stylesheet" href="./css/jqm1.4.5/jquery.mobile.icons-1.4.5.min.css">
			<link rel="stylesheet" href="./css/jqm1.4.5/jquery.mobile.structure-1.4.5.min.css">

	</head>
	<body>
		<div data-role="page" id="index" data-theme="a" >
			<style>
			.ui-title {
			  margin: 0em 15% 0em !important;
			}
			</style>
			<div data-role="header" data-theme="a" data-position="fixed" style="min-height: 40px;">
				<a href="#navigation" style="margin-left: 3px; margin-bottom: 3px;" data-icon="bars" data-iconpos="notext">Navigation</a>
			
						<h1 style="white-space:normal;">test</h1>
				
								
					<a href="#search" style="margin-right: 3px; margin-bottom: 3px;" data-icon="search" data-iconpos="notext">Search</a>
			</div>
				
			
			
			<div data-role="content">

				
				<div data-role='collapsible-set' data-corners='false' >
						<div data-role='collapsible' data-theme='b' data-collapsed='false'><h2>1</h2>
						</div> 
													
						<div data-role='collapsible' data-theme='b'><h2>2</h2> 			
						</div> 
									
						<div data-role='collapsible' data-theme='b'><h2>3</h2>
						</div> 

						<div data-role='collapsible' data-theme='b'><h2>4</h2>
						</div> 
						
						<div data-role='collapsible' data-theme='b'><h2>5</h2>
						</div> 
								
						<div data-role='collapsible' data-theme='b'><h2>6</h2>
						</div>	
							
						<div data-role='collapsible' data-theme='b'><h2>7</h2>
						</div>
						
						
						<div data-role='collapsible' data-theme='b'>
							<h2>Click Here!!</h2>
								<form>
									<textarea cols='40' rows='auto' style='height:100px;' name='newNotes' id='newNotes'></textarea>		
									<input type='submit' id='Submit'  value='Update' class='ui-btn ui-btn-c ui-btn-inline' data-theme='c' data-transition='pop' />
								</form>
						</div>
						
				</div> 	
			</div>
		</div>
	</body>
</html>

**Comment by arschmitz** [comment]
@janey1986 thank you for reporting this however this is definitely a bug in the android home screen mode and i'm not sure there is much we can do about this. http://jsbin.com/kagidi/3/edit?html,css,output shows this without any js or layout at all. The browser should move the content up to not be covered by the keyboard when it opens as you can see in the non home screen mode.

**Comment by arschmitz** [comment]
@janey1986 the only way i could think to attempt to work around this would be something like http://jsbin.com/kagidi/9/edit?html,css,output which fixes the issue on chrome homescreen however this is not really a complete fix it has a few issues that cant really be solved.

 * There is no way to know the keyboard size, and there for how much height to add to the body, on a particular device even more so when you keep in mind custom keyboards.

 * It requires a lot of `userAgent` sniffing to make it work properly

Because of these issues this is not really something we would add to the library i don't think. However this may solve your issue

**Comment by janey1986** [comment]
Hello - thanks for the reply, I'll give it a go! At least I know what the issue is now.

**Comment by apsdehal** [comment]
Closing as not really related to JQM.
