### ISSUE TITLE
Library loading completely broken because "this" context is not set to "window"

### ISSUE THREAD

**Issue by wyatt-mindnest** [jquery/jquery-mobile#8136]
jQuery mobile loads through a stub function like so:

    // Browser globals
    factory( root.jQuery, root, doc );

Which then loads the components. Each component is wrapped in a scoping closure. However, almost ALL the closures pass "this" as the "window" argument, when the factory did not set any scope (therefor "this", and all "window" variables are "undefined").

    (function( $, window, undefined ) {
    ...
    )( jQuery, this ) //this === undefined

Solution is to either set all "this" references to "window" as passed in via the stub, or set the context when calling the stub:

    factory.call( root, root.jQuery, root, doc );

**Comment by arschmitz** [comment]
@wyatt-mindnest thank you for reporting this however we no longer use the wrapper you are referring to please se the 1.5-dev branch for what the current code looks like. ( we no longer pass this or window in the way way you are referencing ) We now use the jquery-plugin UMD wrapper https://github.com/umdjs/umd/blob/master/jqueryPlugin.js
