### ISSUE TITLE
Change to visibility:hidden instead of display none for inactive pages

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#8137]

**Comment by arschmitz** [comment]
Something else to consider here is `opacity:0` where as toggling display or visibility triggers a layout and repaint an opacity change only repaints that element. However elements with `opacity:0` still receive events where as `visibility:none` do not. I cant think of a case where this would be an issue but something to keep in mind.

**Comment by jaspermdegroot** [comment]
PR: https://github.com/jquery/jquery-mobile/pull/8241

**Comment by arschmitz** [comment]
switching this to be for using `visibility:hidden` we cant use opacity because things in inactive pages will still be tabbable
