### ISSUE TITLE
Slide transition reversal does not behave as expected

### ISSUE THREAD

**Issue by routinet** [jquery/jquery-mobile#8140]
See http://jsbin.com/deduseraze/1/edit

Expected:
1. Behavior of a popup with data-transition="slide" will be to slide in from right, slide out to right (default behavior)
2. Behavior of a popup with data-transition="slide" and data-direction="reverse" will be to slide in from the left, slide out to the left
3. Behavior of a popup with data-transition="reverse slide" will be to slide in from the left, slide out to the left

Actual:
1. As expected
2. Same behavior as scenario 1, i.e, did not reverse the slide transition.  
3. The popup slides in from the left, but slides out to the right, effectively traversing the page during its lifetime.

The data-direction setting appears to do nothing to alter transition behaviors in popups.  The reverse modifier on the data-transition setting does alter the behavior, though not completely.

Tested in latest stable Firefox and IE, using the JSBin versions, and using jQuery 2.1.3 and jQuery Mobile 1.4.5 pulled from CDN.

**Comment by routinet** [comment]
I also saw these during my research, but these have been closed for about 2 years.  Is this a regression?

https://github.com/jquery/jquery-mobile/issues/5134
https://github.com/jquery/jquery-mobile/issues/4743

**Comment by apsdehal** [comment]
Confirmed on 1.5-dev.

**Comment by apsdehal** [comment]
First, there is no reverse option for data-transition and also http://api.jquerymobile.com/data-attribute/ mentions specifically that data-direction reverse is not supported on popup.
