### ISSUE TITLE
There is an issue when open datebox after selectmenu has been opened as dialog

### ISSUE THREAD

**Issue by shustinho** [jquery/jquery-mobile#8146]
Hi,

I'm using jquery-mobile-1.4 and i discovered an issue. I have two elements on the page for example
selectMenu: 

<select class="dropDown" name="selectPosition" data-native-menu="false" id="position"/>

and datebox:

<input class="maskedPlaceHolder" name="startTime" id="startTime" type="text" data-role="datebox" data-options=
            '{"mode": "timeflipbox", "timeFormatOverride": 12 , "minuteStep": 15,
                    "overrideTimeOutput": "%l:%M %p","overrideTimeFormat": 12, "lockInput": false}'
           placeholder="Start Time">

Steps:
1. Open position selectmenu (important note - as a dialog)
2. Close it
3. Open datebox - bug appears (the position dropdown has been opened in a second)

Thanks

**Comment by arschmitz** [comment]
@shustinho Thank you for reporting this however this is incomplete please see https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and create a reproducible test case. Also it seems like this is an issue with some 3rd party plugin or widget. 

Im closing this as incomplete we will reopen if you provide the necessary test case and information.

**Comment by shustinho** [comment]
@arschmitz, this is test page:
http://jsbin.com/nuqitohuku/1/edit?html,output

I'm using jquery mobile 1.3.2 and jquery mobile datebox plugin 1.4.0.
Steps to reproduce:
1. Open position dropdown (opened in dialog mode)
2. Choose some item in this dropdown.
3. Open dateBox - bug appears page is hanging.  

Note: this issue is reproducible for me in Chrome. In Firefox it works fine.

**Comment by arschmitz** [comment]
@shustinho Thank you for the details however we will not be doing any new releases of 1.3 to fix bugs its quite old. This is also an issue with a 3rd party plugin not an actual part of JQM. 

For what its worth this issue does not appear with 1.4
