### ISSUE TITLE
Label & Input not in one line

### ISSUE THREAD

**Issue by qpn35** [jquery/jquery-mobile#8149]
Label & Input break into two lines in the vertical view (tested with Samsung Galaxy S6). I have added custom css but no luck.

<div class="ui-field-contain">
<label for="name">Text Input:</label>
<input type="text" name="name" id="name" value="">
</div>

**Comment by arschmitz** [comment]
@qpn35 im not sure what your trying to do there is no example please see https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and create a test page reproducing the bug and we will reopen this.
