### ISSUE TITLE
Inconsistent swipe on android webview

### ISSUE THREAD

**Issue by glennpierce** [jquery/jquery-mobile#8150]
<b>Issue description</b>

For quite some time I have been unable to get the swipe to work reliably on android webview. It would sometimes work and sometimes not. As if swipe events were lost. I decided to look into the jquery.mobile source to see what was going on.

The main issue was a lot of the time when starting a swipe the line (4077)

```javascript
Math.abs( start.coords[ 0 ] - stop.coords[ 0 ] ) > $.event.special.swipe.scrollSupressionThreshold
```

would fail early, causing scrolling to occur.
```
Math.abs( start.coords[ 0 ] - stop.coords[ 0 ] )
```
 would trigger very soon with low numbers. Note this was even with scrollSupressionThreshold set low at 10.

So events will immediately be sent to the scrolling element and the swipe will stop.
I am not sure what the original design was here. Was it assumed events would not come in that quick
to trigger this ? This was triggered even though I was swiping fast. 
As soon as a user swipes moving events will come in fast and the distances will be small to start with.

I have set scrollSupressionThreshold = 5 in my code and that helps but can still fail sometimes and feels like a hack. More importantly scrolling an element is then an issue.

I found better results when I did the following.

Starting on line 4077 we have

```javascript
// prevent scrolling
if ( Math.abs( start.coords[ 0 ] - stop.coords[ 0 ] ) > $.event.special.swipe.scrollSupressionThreshold ) {
 event.preventDefault();
}
```

I changed this to

```javascript
// prevent scrolling
// When duration time is up assume scrolling 
if ( stop.time - start.time < $.event.special.swipe.durationThreshold &&
    Math.abs( start.coords[ 0 ] - stop.coords[ 0 ] ) > $.event.special.swipe.scrollSupressionThreshold ) {
   event.preventDefault();
}
else {
     // Reset the context to make way for the next swipe event
    $.event.special.swipe.eventInProgress = false;
}
```

I did this because when the durationThreshold time is up I feel it should assume scrolling at that point. So when duration time is up elements begin to scroll. 

Also when we start scrolling we should mark the swipe event done hence the else  I added. 
This seems to help scrolling when scrollSupressionThreshold is low.

Events probably should also be sent to the scrolling element when the vertical distance threshold is exceeded not sure.

Although my code works better than what is there my gut feeling is that deciding whether swipe or scrolling events should occur or not should not depend on the distance of the swipe only.
It should depend on the distance and the <b>speed</b> of the swipe.
Then scrollSupressionThreshold can be removed and we can have a pixels per sec threshold.

<b>Test page</b>

Any swipe test eg Newyork example on Android webview. Possibly most browsers ?

*Steps to reproduce</b>

Swipe on any swipe page over a scrollable element on android webview / chrome

<b>Expected outcome</b>

Swipe occurs

<b>Actual outcome</b>

Most of the time the first moving events sent by the browser cause the scrollSupressionThreshold check to fail because the x distances are very small of the first moving events. 
Scrolling is then assumed and swipe is stopped.

<b>Platforms/browsers (including version) and devices tested</b>
Android Webview / Chrome

<b>jQuery Mobile and jQuery core version used</b>

1.4.5

**Comment by glennpierce** [comment]
I had a quick play with the speed idea and did something like this added to $.event.special.swipe

```
// 200 pixels a second
swipeSpeedThreshold: 200,

...
In move handler

var xdist = start.coords[ 0 ] - stop.coords[ 0 ];
var ydist = start.coords[ 1 ] - stop.coords[ 1 ];

var dist = Math.sqrt((xdist*xdist) + (ydist*ydist))
var speed_px_per_sec = dist / ((stop.time - start.time) / 1000.0);
 
// prevent scrolling
if ( speed_px_per_sec >= $.event.special.swipe.swipeSpeedThreshold ) {
    event.preventDefault();
}
else {
   // Reset the context to make way for the next swipe event
  $.event.special.swipe.eventInProgress = false;
}


```
scrollSupressionThreshold can be removed.

Seems to work well for me as people scroll slower.
You can't flick to scroll here as that would be too fast and seen as a swipe.

**Comment by arschmitz** [comment]
@glennpierce Thank you for the suggestion we have decided to go with hammer.js as a replacment for our own touch events in the future as such we wont be adding any new features to our current ones. I'm going to close this.
