### ISSUE TITLE
Persistent toolbar transition visual incorrect

### ISSUE THREAD

**Issue by mac89** [jquery/jquery-mobile#8155]
<b>Issue description</b>

When navigating from one page to another, each having a persistent toolbar, the visuals for the transition between toolbars seem incorrect. 

<b>Test page</b>

<url>http://jsbin.com/zocunicipe/edit?html,js,output</url>

```javascript
    <div id="login" data-role="page" >
        <div data-role="header" data-position="fixed" data-tap-toggle="false" data-id="appHeader">
             <h1>Log in</h1>
        </div>
        <div class="content" data-role="content">
            <a href='#projects'>test</a>
        </div>
        <div data-role="footer" data-position="fixed" data-tap-toggle="false" data-id="appFooter">
             <h1></h1>
        </div>
    </div>
    <div id="projects" data-role="page">
        <div data-role="header" data-position="fixed" data-tap-toggle="false" data-id="appHeader">
             <h1>der in</h1>
        </div>
        <div data-role="footer" data-position="fixed" data-tap-toggle="false" data-id="appFooter">
             <h1></h1>
        </div>
    </div>
```

<b>Reproducing the issue</b>

Simply click the link "test" to navigate the next page and you can see the incorrect visual in the toolbar transition.

<b>Expected outcome</b>

Background color and edge colors staying the same.

<b>Actual outcome</b>

White background on toolbar and black edges.

<b>Platforms/browsers (including version) and devices tested</b>

Opera (29.0.1795.60)
Chrome (43.0.2357.124 m)
IE 11 (11.0.9600.17801)
Windows 8 Javascript App

<b>jQuery Mobile and jQuery core version used</b>

jquery-2.1.4.min.js
jquery.mobile-1.4.5.min.js

<b>Work around</b>

This was posted on the jquery mobile forums as a workaround:

<i>I just added 
      $( "[data-role='header'],[data-role='footer']" ).toolbar({theme:'a'});
to my pagebeforeshow event. It worked like a dream! </i>

<url>https://forum.jquery.com/topic/persistent-toolbar-transition-issue</url>

**Comment by arschmitz** [comment]
@mac89 thank you for reporting this however, this is a known issue persistent toolbars are also deprecated in 1.4.0 however there is a much simpler work around. just add `data-theme="a"` too your toolbars.
