### ISSUE TITLE
radio button change event fires without change

### ISSUE THREAD

**Issue by trixn** [jquery/jquery-mobile#8156]
Hey guys, 

i got a problem with radio buttons firing the change event, not matter if they really change. That means the change event on these radio buttons behaves exactly like the click event. Is that by intention?

Example Code:

``` javascript
$(document).ready(function() {
    $(":input[name= 'radio']").on('change', function(){
        alert("DO SOMETHING");
    });
});
```

```html
<fieldset data-role="controlgroup" data-type="horizontal" style="text-align: center" >
    <input name="radio" id="radio-a" type="radio" >
    <label for="radio-a">a → b</label>
    <input name="radio" id="radio-b" type="radio">
    <label for="radio-b">b → a</label>
</fieldset>
```

If i do not include JQuery mobile, everything works as expected. The change event only fires the first time i click the same radio button. Demonstration: https://jsfiddle.net/6cnLgonk/21/

If i use the same code but include jQuery mobile, the event starts firing always even if the checked status doesn't change... Demo: https://jsfiddle.net/6cnLgonk/25/

Is that a bug or did i miss something? If second, i'm sorry for this...

EDIT: I had a look into the source now. Seems to me that the click event on the radio button label always triggers the change event on the underlying (hidden) input element, no matter if it's "checked" property was set true oder false before. Can someone verify this ?

**Comment by trixn** [comment]
I've spotted the problem inside the Label click event handler of
https://github.com/jquery/jquery-mobile/blob/master/js/widgets/forms/checkboxradio.js
```javascript
_handleLabelVClick: function( event ) {
		var input = this.element;

		if ( input.is( ":disabled" ) ) {
			event.preventDefault();
			return;
		}

		this._cacheVals();

		input.prop( "checked", this.inputtype === "radio" && true || !input.prop( "checked" ) );

		// trigger click handler's bound directly to the input as a substitute for
		// how label clicks behave normally in the browsers
		// TODO: it would be nice to let the browser's handle the clicks and pass them
		//       through to the associate input. we can swallow that click at the parent
		//       wrapper element level
		input.triggerHandler( "click" );

		// Input set for common radio buttons will contain all the radio
		// buttons, but will not for checkboxes. clearing the checked status
		// of other radios ensures the active button state is applied properly
		this._getInputSet().not( input ).prop( "checked", false );

		this._updateAll();
		return false;
	}
```
This function handles the click event both for checkboxes and radio buttons. It sets the radio buttons property "checked" true for the clicked radio buttons and false for every other related radio button and triggers the click event on the hidden input element. The problem is, that it does this unconditionally. It should check the original "checked" property and only trigger the input "click" event if it was false before the click. For checkboxes this is different, because they change by definition, when clicked.

**Comment by arschmitz** [comment]
@trixn thank you for reporting this however this widget is completely replaced in 1.5 and it does not suffer from this issue. At the moment we do not plan any more 1.4.x releases but if we do one we will address this. Im going to close this for now though.
