### ISSUE TITLE
Why bower installer depends on jquery-ui ?

### ISSUE THREAD

**Issue by sprhawk** [jquery/jquery-mobile#8157]
I saw the documentation, jquery-mobile doesn't require jquery-ui

**Comment by arschmitz** [comment]
Because we do depend on jQuery UI parts of it are directly part of the jQuery Mobile distributable.

Closing this as not a bug

**Comment by sprhawk** [comment]
But jQuery UI requires 1.11 version of jquery, but jquery mobile can support up to 2.1 version of jquery.
1.11 and 2.1 are compatible, but a bit wired.

**Comment by arschmitz** [comment]
@sprhawk thats not true jQuery UI only requires jQuery 1.6+ while jQuery Mobile is 1.8+

**Comment by sprhawk** [comment]
@arschmitz thanks for your replying. bower will downgrade the jquery from 2.1 to 1.x.
