### ISSUE TITLE
Unable to focus slider in Firefox using keyboard

### ISSUE THREAD

**Issue by wwalc** [jquery/jquery-mobile#8158]
In Chrome I can access the slider with keyboard:
![screen shot 2015-06-19 at 11 42 26](https://cloud.githubusercontent.com/assets/545175/8250940/64b09576-1678-11e5-9272-43bacc507964.png)

while in Firefox I can just access the input element:
![screen shot 2015-06-19 at 11 42 40](https://cloud.githubusercontent.com/assets/545175/8250942/660ddb7c-1678-11e5-929e-3ce24385e643.png)

Is this a know difference between browsers (by design) or a bug?

**Comment by arschmitz** [comment]
@wwalc this is a bug

**Comment by arschmitz** [comment]
@wwalc it turns out this is a bug in firefox anchor elements are not tabbable even when you add a tabindex http://jsbin.com/rolucu/edit?html,output more on this here http://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox im going to close this can't fix

**Comment by wwalc** [comment]
Thanks for the research, I agree can't fix makes sense here.
