### ISSUE TITLE
Range slider doesn't fire change event

### ISSUE THREAD

**Issue by duizendnegen** [jquery/jquery-mobile#8159]
The range slider doesn't fire a change event when the lower bound is approaching the upper bound.

Imagine a slider with `{min=1, max=5}`. Now, the transition `{lower=4, upper=5}` to `{lower=5, upper=5}` happens visually, but no change event is fired. I've worked around this by listening to `$(".slider").on("slidedrag")`, then manually triggering a change event, but it's quite clumsy.

See the case live in a jsbin: http://jsbin.com/fajudodevi/1/edit?html,js,console,output - just drag the lower bound to 5.

**Comment by arschmitz** [comment]
@duizendnegen Hi thank you for reporting this. It is indeed a bug

**Comment by cgack** [comment]
fixed with bcca12a9baa19beb4a05e043fad7f93d6c39892d landing on 1.5-dev branch

**Comment by duizendnegen** [comment]
:+1:
