### ISSUE TITLE
Datepicker: Popup demo broken on 1.5-dev

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#8183]
The "Popup Datepicker" demo is broken. The widget fails to pop up when the user clicks into the textinput.

**Comment by marti1125** [comment]
Hi @gabrielschulhof the problem is the build of jquery-mobile in <script src="../../js/"></script>
it doesn't has zIndex() method like this http://code.jquery.com/mobile/git/jquery.mobile-git.js I'm  trying to fix this
