### ISSUE TITLE
jQM not working on Microsoft Edge: "Unspecified error"

### ISSUE THREAD

**Issue by T917820981726** [jquery/jquery-mobile#8188]
Hi,

I noticed that jQuery Mobile does not correctly work on Microsoft Edge on Windows 10, tested with builds 10162 and 10166.

The problem seems to be with the following code at line 3697 of jQuery Mobile 1.5.0-pre (Git HEAD hash: d04308f591d4d0e58443d6a645d0cc1f599888d2 <> Date: Thu Jun 18 2015 17:52:18 UTC):
```javascript
window.history.replaceState( state, state.title || document.title, href );
```

I have created a sample test page that reproduces the problem:
http://jsbin.com/wipera

Expected Output (works on IE 11, Firefox, Chrome): Page shows "Success!".

Actual Output on Edge (Windows 10 build 10162 and 10166): White page, only a loader icon is shown.
Edge console shows the following javascript error:
```
SCRIPT16389: Unspecified error.
jquery.mobile-git.js (3697,4)
```

The problem can also be reproduced with the multi page demo of jQuery Mobile 1.4.5 on Edge:
http://demos.jquerymobile.com/1.4.5/pages-multi-page/

Here, clicking on "Page 2" will successfully navigate to page two, but if you then click on "Back to page 'one'", nothing happens and the console shows the same javascript error.

For testing, you can download Windows 10 preview from here: http://windows.microsoft.com/en-us/windows/preview-iso

Thanks!

**Comment by T917820981726** [comment]
Sorry, it seems this was a bug in previous Edge versions. With Microsoft Edge on the current Windows 10 build (10240) the test page works correctly.

**Comment by arschmitz** [comment]
@T917820981726 awesome thank you for the update
@jacobrossi you are getting too good keep fixing all the bugs we find before we can even report them :-)
:+1:
