### ISSUE TITLE
Popup: ui-link must not be added anymore

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#8194]
The code at the top of js/widgets/popup.js adds the class ui-link to some anchors. It

a) does so incorrectly, because there's an extra ```.end()``` in the chain, and
b) shouldn't be doing it at all, because ui-link was deprecated and should be removed.

This issue reminds that the code adding ui-link should be removed.

**Comment by jaspermdegroot** [comment]
To avoid confusion; we only deprecated the adding of class ui-link. The CSS for that class remains. If you want to apply the style you can add the class to your markup.

The file js/links.js should be removed as well.

**Comment by gabrielschulhof** [comment]
590df65575744bac9d6a3995ea81758976d18273 removes the code that adds ui-link to popup links. The file js/links.js still needs to be removed.
