### ISSUE TITLE
Theme-Roller: Import / Export of Border-Colors not correct

### ISSUE THREAD

**Issue by bocksebastian** [jquery/jquery-mobile#8234]
Hello,

We found a wrong behaviour of the jQuery Mobile Themeroller Export. If we export a created theme with changed border-colors we have to change the colors manualy after exporting it.

![2015-07-21 16_33_23-examdiff - c__users_bock sebastian_downloads_inside-false css _ c__users_bock](https://cloud.githubusercontent.com/assets/12858281/8803290/5db4d108-2fc6-11e5-8590-f00125f982f1.png)

In the Screenshot you see the difference between the original code on the right side and the exported code on the left side, without making a change in the UI. This difference are in every swatch we made so that it is not easy for us to use an exported theme directly for our customers.

Hope you can work with this and fix this bug in one of the next versions of the Themeroller.

**Comment by jaspermdegroot** [comment]
@bocksebastian 

Thanks for reporting the issue. The ThemeRoller has its own issue tracker.
I think your issue might be related to this one: https://github.com/jquery/themeroller.jquerymobile.com/issues/218
Do you mind commenting on that ticket? Thanks!
