### ISSUE TITLE
when touch input element,header fixed lose effectiveness when use  jquerymobile in cordova.

### ISSUE THREAD

**Issue by liangzhenghui** [jquery/jquery-mobile#8237]
i test on android,found some can work well but some not.anybody meet this situation?
situation like https://github.com/jquery/jquery-mobile/issues/4113

**Comment by jaspermdegroot** [comment]
@liangzhenghui 

Please follow our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md) when reporting an issue. Thanks.
