### ISSUE TITLE
after changing to ajax loaded page, scripts in the page will not be called.

### ISSUE THREAD

**Issue by javaone199** [jquery/jquery-mobile#8242]
After ajax loading a page that contains two scripts: 
1.  changeToPage();
2.  foo();

When the page is inserted into DOM, jQuery will execute the two scripts inside the page.
But when the first script is called, change to the page, and the page will be enhanced.
As a result, the 2nd script foo() will not be called.

jquery.js

	for ( i = 0; i < hasScripts; i++ ) {
		node = scripts[ i ];
		if ( rscriptType.test( node.type || "" ) &&
		     !jQuery._data( node, "globalEval" ) && jQuery.contains( doc, node ) ) {

The condition is false for the 2nd script after the first script is executed.

**Comment by jaspermdegroot** [comment]
@javaone199 

Please follow our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues) when reporting an issue and include a test page.

With the information you provided we can't see if this is a bug in the framework or a problem in your code. Note that it is strongly recommended to place scripts in the ```head```, not inside the page.

I am closing this ticket for now as incomplete, but we will reopen once a complete bug report with test page has been provided.
