### ISSUE TITLE
Window scroll event stops firing after navigation

### ISSUE THREAD

**Issue by StephenCleary** [jquery/jquery-mobile#8250]
If I navigate to a page and then navigate back, the window scroll event no longer fires.

Fiddle here: https://jsfiddle.net/e2rkozjf/

Before navigation, I can scroll (logging events to the console). After navigating to a different page and back, the scroll event no longer fires.

In my real-world app, this breaks Waypoints.

**Comment by arschmitz** [comment]
@StephenCleary Thank you for reporting this this is indeed a bug in our scrollstart / stop events we are not properly unbinding. We will get this fixed ASAP however for version 1.4.x you can use this workaround http://jsbin.com/bapeno/edit?html,js,console,output

simple add the js in that file in to override the current method and everything should work as expected.

**Comment by StephenCleary** [comment]
That fixed it perfectly for me. Thanks a million!
