### ISSUE TITLE
1.5 Textinput: Enhanced doesn't work as expected

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#8252]
The widget treats the ```form``` element as wrapper and adds classes to it, while there is already a ```div``` that serves as wrapper present in the markup.
See http://view.jquerymobile.com/1.5-css-and-demos/demos/textinput/#Enhanced

**Comment by apsdehal** [comment]
This happens because textinput on the demo page doesn't have any div wrapper among it. See https://github.com/jquery/jquery-mobile/blob/1.5-dev/demos/textinput/index.php#L342 . In these cases when the parent has more than one child, I think we should create a wrapper around the element.
