### ISSUE TITLE
Button widgets - "faked" button text separately announced by screen readers

### ISSUE THREAD

**Issue by patrickhlauke** [jquery/jquery-mobile#8257]
Similar to https://github.com/jquery/jquery-mobile/issues/8256 the markup generated for all the different variations of button widgets http://demos.jquerymobile.com/1.4.5/button/ such as

```
<div class="ui-btn ui-input-btn ui-corner-all ui-shadow">
  Button
  <input type="button" value="Button">
</div>
```

 results in redundant VoiceOver/TalkBack announcements - first, the static text, then the actual `<input>` value / `<button>` content. Once again, using `aria-hidden="true"` (and an additional `<span>`) will suppress this:

```
<div class="ui-btn ui-input-btn ui-corner-all ui-shadow">
  <span aria-hidden="true">Button</span>
  <input type="button" value="Button">
</div>
```

**Comment by arschmitz** [comment]
@patrickhlauke the button widget has been replaced for the upcoming 1.5 version please see http://view.jquerymobile.com/1.5-css-and-demos/demos/button/ for what the new widget looks like. 

Note: This is the same widget as will be in the new version of jQuery UI. The button, checkboxradio, controlgroup widgets have all been re-written for for the upcoming 1.5 release. I believe the updated markup solves this problem already so i'm going to close this. If i am wrong and there is still an issue just comment here and i will re-open.

**Comment by patrickhlauke** [comment]
Confirming that from what I see in 1.5 there, the issue is resolved. Sorry for the added noise :)

**Comment by arschmitz** [comment]
@patrickhlauke no problem thats not on master so you had no way to know :-)
