### ISSUE TITLE
Select menu – prevents zooming (iPhone5 – iOS 8)

### ISSUE THREAD

**Issue by viveksandam** [jquery/jquery-mobile#8258]
Page stops pinch zooming when I tried to zoom on Select menu. I noticed this behavior when I try to zoom a page having select menu control.
You can reproduce this on JQuery mobile demo site which demonstrate the Select menu options. 

<b>Reproduction steps:</b>
Touch the Select menu control and try to zoom the page. It will not allowed zoom in/ zoom out. 
Now select any option from the drop down and then try to zoom, it will allowed.

**Comment by apsdehal** [comment]
Kindly use the template and reopen.
