### ISSUE TITLE
iPhone 5 (scrollable view) scrolling is not smooth

### ISSUE THREAD

**Issue by viveksandam** [jquery/jquery-mobile#8259]
I have scrollable view in my JQM page, but in iPhone the scrolling is not smooth. The scroll lag is clearly visible. The view has several collapsible widgets. 
Also when I tested the "http://www.gajotres.net/using-iscroll-with-jquery-mobile/" site in iPhone (iOS 8), having simple list controls, has same issue.

**Comment by arschmitz** [comment]
@viveksandam can you please create a test case for this using jsbin or jsfiddle not including any outside libs like iscroll

you can use out template from the contributing guidelines https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md

**Comment by apsdehal** [comment]
Kindly use the template and reopen.
