### ISSUE TITLE
iOS 9 (beta) Problems with select menu in UIWebView / Cordova app

### ISSUE THREAD

**Issue by skicson** [jquery/jquery-mobile#8262]
Description:

Select menus, particularly those with many items, do not work properly in iOS 9 UIWebView.  We have discovered these issues when testing our cordova/jquery-mobile app on iOS 9.   

There are two problems:
- The first problem is that when a select menu is first activated, it appears, and then is hidden.  (Based on some preliminary work, it looks like a navigation event is sent which causes it to close).  Subsequent activations perform as expected.  

- The second problem is that when a menu item is selected, it does not return to it's original state.  These images show the menu before activation, while the menu is showing, and after an item has been selected.

![simulator screen shot aug 10 2015 11 59 57 am](https://cloud.githubusercontent.com/assets/13732946/9176210/24237cc2-3f58-11e5-9c42-d2440fac8fef.png)
![simulator screen shot aug 10 2015 12 00 11 pm](https://cloud.githubusercontent.com/assets/13732946/9176211/242455f2-3f58-11e5-869a-6f20721f5893.png)
![simulator screen shot aug 10 2015 12 00 15 pm](https://cloud.githubusercontent.com/assets/13732946/9176212/242879c0-3f58-11e5-8011-091ae9fb64df.png)

Test Page: 

Here is the testbin page:  http://jsbin.com/dasaloselu/edit?html

Steps to Reproduce (I can send you the Xcode project if you'd like - I wasn't sure how to attach):

a) Create an single screen Xcode project that has a single UIWebView.
b) In the viewDidLoad, load the UIWebview with a URL request to http://output.jsbin.com/dasaloselu
c) Run the app and tap the button.

Expected Outcome:
The menu should appear on the first tap, and when an item is selected, it should return to being a button again.

Actual outcome
Shown above

Platforms/Browsers
Tested okay on Safari - Seems to have the similar issue on FireFox if you test in the "Output" pane of jsbin.

jQuery Mobile versions
Linking to the latest but noticed in 1.4.5

Other Info
Using iOS 9 beta 5

**Comment by skicson** [comment]
Some additional information:

It appears (warning: I'm not a Javascript guy) that these iOS 9 problems are related to the generation of navigate events on a hashchange.  Perhaps iOS 8 and before just didn't generate hashchanges properly?   Anyways, setting the "hashListeningEnabled" attribute in to false in the 1.4.5.js "fixes" the problem with iOS 9's UIWebView.  This change also works (in preliminary testing) in iOS 8 and iOS 9.  I'll continue to test...

**Comment by luigi37** [comment]
@skicson did you manage to confirm the issue. Eventually where should be put the hashListeningEnabled=false
Thanks

**Comment by skicson** [comment]
@luigi37   yes, I confirmed this was the issue.    This is how I set it (needs to go between the jquery.js and jquery.mobile-1.4.5.js in the index.html as shown here)

<script type="text/javascript" charset="utf-8" src="js/jquery.js"></script>
<script type="text/javascript">
  $(document).bind("mobileinit", function(){
      $.mobile.hashListeningEnabled = false;
  });
</script>  
<script type="text/javascript" charset="utf-8" src="js/jquery.mobile-1.4.5.js"></script>

**Comment by luigi37** [comment]
Thanks a lot! Any side effect?

**Comment by skicson** [comment]
surprisingly, no :)  works great.

**Comment by luigi37** [comment]
Wonderful, thanks again!

**Comment by Sanafan** [comment]
Side effect is that `data-transition="reverse"` is not working than.

**Comment by ham2qur** [comment]
Great It works. I was also facing JQM issues regarding events after upgrading to IOS9. Thanks

**Comment by jjm4256** [comment]
I had the same issue described above after iOS 9 upgrade, and $.mobile.hashListeningEnabled = false; fixed it for me too.  However, when I do a page change as follows:

$.mobile.changePage("#my-page-name", { reverse: true, transition: 'slide' });

the hashListeningEnabled fix stops working and I run into issues with select menus again.  I tried adding "changeHash: false" to the changePage call, but no luck.  Has anyone else experienced this - the fix working until you do a changePage transition?

**Comment by dezudas** [comment]
@skicson code works for back button but it disable the query string so passing values between pages is not working.

**Comment by agador** [comment]
The issue also occurs on Safari WebAPP (Add to Home Page) and Multi-Select.

The situation is very similar to what is happening with the Cordova/Jquery mobile apps.  

The temporary work around is to add the  $.mobile.hashListeningEnabled = false; to the Mobile Options.

I suspect the same transition issue will be a side effect (we don't use transitions).

I would attach, but apparently I don't have write permission to this repository.

Jim

**Comment by helloweenpad** [comment]
$.mobile.hashListeningEnabled = false works for select, but not for page switching. Disabling hashListeningEnabled will break lots of jquerymobile functionalities. Not a good solution for me. 

It seems ios9 breaks other frameworks too like http://blog.ionic.io/ios-9-potential-breaking-change/

**Comment by osos** [comment]
Unfortunately the @skicson solution disabling the hashListeningEnabled did not solve it for my simple application featurering some custom selectmenus

**Comment by fatha** [comment]
$(document).ready(function() {
    $(document).on('popupbeforeposition', function( event ){
        $.mobile.hashListeningEnabled = false;
    });

    $( document ).on( "popupafterclose", function() {
        $.mobile.hashListeningEnabled = true;
    });
});

Thank you guys you inspired me and it works like a charm, no side effects. You just have to turn "off" the  hashListeningEnabled before opening the popup and then turn it back "on" when you close it. I cannot think of any side effects. 

Thank you all for the constructive discussion.

**Comment by osos** [comment]
@fatha, thanks - unfortunately it does fix it for me.

Pasted my code here: http://output.jsbin.com/fiqosafehi/1/

Seems to work in IE10, problems in firefox. fine with iOS browser, problems as iOS "web app".

**Comment by helloweenpad** [comment]
it is a UIWebView bug of iphone. we replaced UIWebView with WKWebView in our app, the issue was resolved. 

ios 9 start to use wkwebview instead of uiwebview in safari too, that is why safari works well with jquerymobile.

**Comment by helloweenpad** [comment]
@osos @fatha thank you for the suggestions . see my comments above.

**Comment by apsdehal** [comment]
This issue occured when iOS changed hashlistening events' behavior in iOS 9 but this change was soon reverted. See first comment at https://openradar.appspot.com/22186109. This has been fixed.

**Comment by JasonGlez** [comment]
Or use
if(device.platform === "iOS" && parseInt(device.version) === 9){
   $.mobile.hashListeningEnabled = false;
}
