### ISSUE TITLE
overflow-x:hidden and problems with current VoiceOver/iOS

### ISSUE THREAD

**Issue by patrickhlauke** [jquery/jquery-mobile#8263]
Although this is clearly a bug in VoiceOver/iOS (8.4, not tested 9 beta), just a heads-up that there seem to be issues relating to the use of `overflow-x:hidden` (which seems to be quite core to many of the jQuery Mobile containers) and VoiceOver, which prevents the viewport from scrolling together with the VoiceOver focus and renders controls focused offscreen inoperable.

See the video demonstration https://www.youtube.com/watch?v=-dt0VMFji5Y and the bug report https://bugs.webkit.org/show_bug.cgi?id=147700

**Comment by arschmitz** [comment]
@patrickhlauke are you aware of any work arounds for this? `overflow-x:hidden` is pretty critical for jQuery Mobile it would break a lot if we stopped using it.

**Comment by patrickhlauke** [comment]
currently i'm not aware of any workarounds beyond "make sure your content doesn't overflow horizontally, and then drop the `overflow-x:hidden` I'm afraid. hoping for a fundamental fix from Apple on this.

**Comment by arschmitz** [comment]
Yeah im afraid in our case its a lot more complicated then just "make sure your content doesn't overflow" its an integral part of our layout and  transitions.

**Comment by patrickhlauke** [comment]
Good news is that it seems iOS9 beta fixed this bug, so once iOS9 final is out, this will become a non-issue.

**Comment by arschmitz** [comment]
That is indeed good news
