### ISSUE TITLE
Mobile jQuery  button click brings me to top of page. But I want to stay where I am

### ISSUE THREAD

**Issue by prncdahal** [jquery/jquery-mobile#8268]

**Comment by jaspermdegroot** [comment]
@prncdahal 

If you think this is a bug in jQuery Mobile please follow our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues) when submitting the issue.
If you don't think it is a bug, but you are looking for help with a problem, you can post on the [forum](https://forum.jquery.com/jquery-mobile).

Closing this ticket as incomplete.
