### ISSUE TITLE
jqm 1.4.5 loading error

### ISSUE THREAD

**Issue by hainzee** [jquery/jquery-mobile#8269]
Please can somebody point me to any previous issues on getting around the generic 'Error Loading Page' message. I have only started a basic page with a header, ui-content , footer and panel so far and it's the link that opens the panel causing the error. I am running a local web server. 
Grateful for any help.

**Comment by jaspermdegroot** [comment]
@hainzee 

This issue tracker is meant for bug reports. For getting help with problems you run into you can post on the [forum](https://forum.jquery.com/jquery-mobile). See also our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues).
When posting on the forum I suggest you include your markup. With just the information you provided here it will be very hard for people to help you. Best is to include a link to a test page (you can use JSBin for that) that actually shows the error.
