### ISSUE TITLE
History replaceState no longer working in Chrome for local file

### ISSUE THREAD

**Issue by dt1973** [jquery/jquery-mobile#8281]
Figured this might be relevant incase you're using jQuery Mobile locally in the latest Chrome:

http://stackoverflow.com/questions/32398578/history-replacestate-no-longer-working-in-chrome-for-local-file

**Comment by caleb87** [comment]
I'm running Chrome Version 45.0.2454.85 m - Windows 7 and this just popped up for my local app. 

No issues in Firefox or Safari. IE asks to allow for blocked content, and works. 

I haven't found a solid solution yet.

**Comment by jaspermdegroot** [comment]
@arschmitz 

I think we can close this ticket as duplicate of https://github.com/jquery/jquery-mobile/issues/8142. Agreed?

**Comment by dt1973** [comment]
Yup!
