### ISSUE TITLE
`npm install` fails on Node 4.2.1 & 5.0.0

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-mobile#8283]
`npm install` fails on Node 4.0.0-rc.2 due to a [contextify issue](https://github.com/brianmcd/contextify/issues/177). Node.js 4.0.0 stable should come out within the next few days so this will affect the default Node version soon. Unfortunately this is a recurring problem, we've had a [similar one with io.js 2](https://github.com/jquery/jquery/issues/2266) before.

Newer jsdom versions, ones that work only with io.js & the upcoming Node.js 4.0.0 don't depend on contextify so don't require any compiled dependencies. We've decided in Core to [not test jsdom on Node.js 0.10 & 0.12](https://github.com/jquery/jquery/pull/2526) at all during regular runs and just make it available for optional manual testing. Otherwise, we install the latest version that doesn't depend on contextify. This also makes it easier for Windows contributors who often [have problems installing native modules](https://github.com/jquery/jquery/issues/2519).

Could you apply a similar strategy here?

**Comment by arschmitz** [comment]
@mzgol this might not actually be an issue. We dont actually use jsdom any more this is a left over that needs to be removed. Will have to test to see if there are any other issues though

**Comment by mzgol** [comment]
Node.js 4.0.0 final has been released.

**Comment by mzgol** [comment]
Ping? Node 4.1.1 has been released, it's soon going into the LTS phase. More & more people will hit this block as this is the version you'll get when you download Node from the https://nodejs.org/ main page.

**Comment by mzgol** [comment]
@arschmitz Is anything blocking it? Node.js 5.0.0 was released so Mobile now doesn't compile on latest 2 Node releases, the only ones you can download directly from https://nodejs.org/en/ without going for more specialized downloads. Most new contributors will be affected by it.

**Comment by arschmitz** [comment]
@mzgol like i said in my last comment this is already fixed in our working branch we have not used jsdom in some time we use cheerio.

**Comment by mzgol** [comment]
Ah, I forgot about this branch. Thx for removing. What's the purpose of `master` then?

**Comment by apsdehal** [comment]
Closing as fixed in 1.5-dev. Master is not the latest development branch but the latest stable branch. 1.5 will be merged into master when ready to be released.

**Comment by mgol** [comment]
What's the purpose of the `master` branch then? Is it so that people can submit PRs against a stable version as that's what most of them would like?

If so, then the `master` branch should work on the most popular Node.js versions which include versions 4 and now 6.

However, the contextify issue seems to be fixed now as I was able to successfully ran `npm install` on `master` on Node.js 6.1.0.
