### ISSUE TITLE
Zip Download not working from Themeroller since about 12 hours ago

### ISSUE THREAD

**Issue by pietercal** [jquery/jquery-mobile#8286]
Hi,

It appears that the zip download is not working for the Themerolooer.

I reported it about 10 hours ago but it seems that it has been closed by mistake.

Thanks for looking into it

**Comment by arthurvr** [comment]
It wasn't closed by mistake, it was simply a duplicate. https://github.com/jquery/jquery-mobile/issues/8285#issuecomment-139137382

**Comment by pietercal** [comment]
Ok, but it is still not working and there is no other open issue showing it

Can you please tell me how to download the zip file without getting the 
problem?

Many thanks

----- Original Message -----

**Comment by arthurvr** [comment]
> Ok, but it is still not working and there is no other open issue showing it

As can be read in the link I posted, there's an open issue at https://github.com/jquery/themeroller.jquerymobile.com/issues/221.

**Comment by pietercal** [comment]
Ok, sorry about that, my mistake

**Comment by agcolom** [comment]
@pietercal yes, we only keep one issue open and as @arthurvr mentioned, we have this issue open in the themeroller repository. We are looking into the problem with the infrastructure team. I am closing this issue as we have it covered in https://github.com/jquery/themeroller.jquerymobile.com/issues/221
