### ISSUE TITLE
Panel click very slow response

### ISSUE THREAD

**Issue by dezudas** [jquery/jquery-mobile#8288]
ISSUE: Thank you for building JqueryMobile, I am using it for my one of the app where I am facing some issues with panel transaction.

Test page: app is smooth in browser but in android you can see the page try to install Chordpedia app 
Steps to reproduce : Once list gets loaded try to click on hamburger icon, it will take more then 10 sec and again disconnect to internet and try to click the same button.
Expected outcome: page transaction should have been smooth and there should be no lag in button click
Actual outcome: there is a time lag in hamburger button click
Platforms/browsers (including version) and devices tested: I can replicate the issue in all major android device
jQuery Mobile and jQuery core version used: jquery-1.11.1.min and jquery.mobile-1.4.5.min
Other relevant information: my recent build is in Cordova 5 but current published app is in cordova 4

**Comment by dezudas** [comment]
issue is with sliding panel too

**Comment by dezudas** [comment]
https://github.com/jquery/jquery-mobile/issues/4340
http://stackoverflow.com/questions/15673526/slow-jquery-mobile-panels-in-phonegap
https://github.com/jquery/jquery-mobile/issues/5636

Issue remains same

**Comment by jaspermdegroot** [comment]
@dezudas 

Can you please provide a test page. See https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#test-page. Thanks!

**Comment by dezudas** [comment]
@jaspermdegroot  issue is in mobile app, it works fine with browser, I read the contribution page and tried to replicated the issue in browser but it works fine so u need to check it in app :( app name is chordpedia, issue is more in recent beta version I am working on.

https://play.google.com/store/apps/details?id=com.dez.chordpedia

**Comment by jaspermdegroot** [comment]
@dezudas 

I understand that it's an app, but please provide the markup in our JSBin template. We will test in Webview and in Cordova. We can't debug an app installed via de Play Store.

**Comment by dezudas** [comment]
@jaspermdegroot  http://jsbin.com/seqapuvobu/edit?html,output

Please have a review

**Comment by jaspermdegroot** [comment]
@dezudas 

Thanks for the test page. On what Android version did you see the problem?

**Comment by dezudas** [comment]
I tried it different version and the issue is with all, my device version is 4.4.4 and i can fee the issue.

**Comment by rgfpy** [comment]
try with data-animate="false", but the animation is lost is good for old devices where the webview still uses the original Android not chrome

**Comment by dezudas** [comment]
@rgfpy I tried that too but the response time is almost same, I can see there is few sec might be 1-2 sec change

**Comment by dezudas** [comment]
jsbin is for latest version but I am using jquery.mobile-1.4.5

**Comment by rgfpy** [comment]
I download the app but in remote debugging for chrome not appear for testing.

Bot in my phone Galaxy S5 with Android 5.0 not see the bug every run ok with normal speed

**Comment by dezudas** [comment]
@rgfpy did you tried the side bar, issue is more the new beta version. could you send me ur email I will assign u the beta version

**Comment by apsdehal** [comment]
Closing, I find the latest version of app and jsbin template working fine.
