### ISSUE TITLE
JQM multiple links within TALL popups don't work on iOS

### ISSUE THREAD

**Issue by h1pchek** [jquery/jquery-mobile#8289]
I know there were some issues with the history and back buttons on iOS devices and at first i thought this was part of that as my close buttons where being blocked but I noticed it seems like in iOS devices that all links (close, href, onclick, etc) seem to break inside of a popup that you have to scroll on with the exception of the first link in that popup... weird part is that the subsequent link actually seem to recognize the click event but simply become anchor links to the first link in the popup.

on iOS devices (iphone 5s, iPad 4 both running on iOS 7/8) the default safari browser seems to have issues with links that are located within a popup (with overlay theme or dialog type styling).  if i have a short popup that will fit on the screen without having to scroll then ALL the buttons within a popup seem to work, but if my popup is tall and forces you to have to scroll then it seems like only the FIRST anchor tag on the popup will work and the others simply anchor link to the position of the first anchor tag in the popup.  even alerts, console.log, and other onclick calls don't work.

i've tried various data-ajax=false on the links, data-history=false on the popup, e.preventDefault, return false, pageinit, pagebeforecreate, pagecreate, etc. to see if i can get the links to work with no luck.  I even tried creating a link on the fly after the popup was opened but it had the same problem.
I can't seem to replicate this issue on any windows browsers (IE9+, Firefox, Chrome, Oprea) nor on a few of the Android 5+ devices I tried (Moto X, Nvidia Shield, Tab 5, etc, all running Chrome or “internet” browsers).

I put together a sample to look at in jsBin.com and put some spacer div tags to help force illustrate the issue on iPhones and iPads.

demo example for testing on iOS devices: 
https://output.jsbin.com/picema/

the full code/setup 
https://jsbin.com/picema/edit?html

As you can see it is pretty much an out of the box setup, the .click event isn’t even needed, I just put it there to help illustrate that the click event isn’t being triggered for iOS devices (but instead jumps the scroll position on the page?).

Am I  missing something with bad code?  Any ideas why this would be an iOS issue only?  Any suggestions on a fix?

Thanks!

**Comment by Alfred-Lu** [comment]
+1
Any fix for this?

**Comment by ronsweb** [comment]
This also happens with a tall listview in a popup.  If you scroll to the bottom of a tall listview and click on the listview item, the menu scrolls back up to the last listview item that was at the bottom of the popup before the scroll started and highlights the wrong listview item.  This is affecting a production app.  I cannot find a solution.  It is confirmed in ios 9 and safari on a desktop.  In Android, Chrome, IE 11 and Firefox the tall listview in a popup worked perfect.  Please fix this.

**Comment by ronsweb** [comment]
I just tested with the JQM version 1.5 and it fixed the problem.  The tall listview works now and I also tested the code provided for this bug from h1pchek.  I changed out the files to point to the github jqm version 1.5 files:
 <link rel="stylesheet" href="https://code.jquery.com/mobile/git/jquery.mobile-git.css" />
<script src="https://code.jquery.com/jquery-1.12.2.min.js"></script> 
<script src="https://code.jquery.com/mobile/git/jquery.mobile-git.min.js"></script>

Also tested in a Macbook Pro Safari 9.1.2 OSX 10.11.6.  JQM version 1.5 fixed it.

**Comment by jaspermdegroot** [comment]
@ronsweb - Thanks for testing again!

Closing as fixed.
