### ISSUE TITLE
Tabs widget doesn't work if loaded from a seperate html file with data-role page.

### ISSUE THREAD

**Issue by saurabhshah23** [jquery/jquery-mobile#8290]
Tabs widget works on first html page where jqm css and js is added.
When i try to add tabs widget on any other html with data-role="page" and load it via 
$( ":mobile-pagecontainer" ).pagecontainer( "change", url );
then it displays all the tab contents and the widget doesnt work as expected.

![screen shot 2015-09-21 at 6 49 12 pm](https://cloud.githubusercontent.com/assets/2903564/9992733/8f8faad0-6091-11e5-9929-eaf152e14a83.png)

**Comment by jaspermdegroot** [comment]
@saurabhshah23 

Please provide a test page. See our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues) for more information and link to our JSBin template.
I am going to close this ticket for now. We will reopen when the test page has been provided and we are able to reproduce the issue. Thanks.
