### ISSUE TITLE
iPad:  dialog opens and Scrolls Off-screen

### ISSUE THREAD

**Issue by chaudhan** [jquery/jquery-mobile#8295]
On the iPad Air, on Safari, when I click on a button, modal dialog opens.  When I scroll down on the page to click on a different button further down in the document, the dialog box does not scroll/remains stuck in its original open location.  In order to see the dialog, I have to scroll back up to the top of the document where I originally clicked on a previous button.

This  is not an issue on desktop environments.

If I click on a button to open the dialog, then I close it, then I scroll down the document, then I  click on another button, the dialog will open on the current screen.

**Comment by jaspermdegroot** [comment]
@chaudhan 

Can you please provide a test page and inform us about the iOS and jQuery Mobile version you are using. See our [contributing guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues). Thanks!
