### ISSUE TITLE
Navigating back in a single page app (all navigation via #tags) is broken on iOS 9 in UIWebViews

### ISSUE THREAD

**Issue by NipponMonkey** [jquery/jquery-mobile#8302]
In a simple multi-page app on iOS 9 in a UIWebView (what Cordova / PhoneGap uses by default) the hash navigation history is broken.

I've tested with jqm1.3.0 and the latest jqm.

All you have to do to reproduce the issue (in an iOS 9 UIWebView) is:
- page loads to page1
- nav to page2 either via a #page2 anchor or via $.mobile.changePage('#page2')
- On '#page2', nav to page3 either via a #page3 anchor or via $.mobile.changePage('#page3')
- When you nav back via window.history.back() you are taken to the first page, not the second page as the back history for # page changes is broken.

This is causing major issues to our apps on iOS 9.

I'm not sure when this is happening in iOS9 UIWebViews as it is not happening in any other browsers I've tested on, including iOS 9 safari and WKWebViews.

I've tested an even simpler version of this without JQM, just a simple page with # fragments links to different parts of the document, when I do this, window.history.back() works as expected, so I'm not sure what JQM does to stop this.

Cordova doesn't seem to affect this outcome it just seems to depend on running UIWebView in iOS9.

**Comment by NipponMonkey** [comment]
A work around seems to be setting $.mobile.pushStateEnabled to false (on mobileinit) if running in iOS 9 UIWebView. Then the back history works - from my initial testing.

**Comment by jaspermdegroot** [comment]
@NipponMonkey 

Thanks for reporting the issue. I think this is the same problem as https://github.com/jquery/jquery-mobile/issues/8293 so I am closing this ticket as duplicate.

**Comment by studio-dude** [comment]
It's also worth pointing out that the $.mobile.pushStateEnabled fix breaks all the back animations. For example if you have a popup that you get to with a flip animation, clicking a "Back" button won't do a flip.

**Comment by NipponMonkey** [comment]
Yes, I had the back transition animations issues too, but they aren't critical to the app so disabled all page transitions when running in iOS9 UIWebViews.
