### ISSUE TITLE
Update jquery-mobile on npm

### ISSUE THREAD

**Issue by bcomnes** [jquery/jquery-mobile#8303]
It looks like jquery mobile on npm is still at 1.4.1 published 2 years ago.  Can you update the version hosted on npm? https://www.npmjs.com/package/jquery-mobile

cc @gbraad

**Comment by arschmitz** [comment]
We don't maintain this package and don't have rights to it so we cannot. @gbraad has no affiliation with us.

**Comment by bcomnes** [comment]
@arschmitz would the jquery-mobile team be willing to maintain a version published on npm?  Or is that up to the community?

Also on a side note: would jquery-mobile be open to some of of the changes mentioned in http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm ?

**Comment by arschmitz** [comment]
@bcomnes we are open to a few options to make this easier. I think our first step would be along the lines of https://github.com/jquery/jquery-ui/pull/1600 . The real problem here is that to work the "npm way" we would need to publish each module individually which we don't want to do. We also wont commit built files for a number of reasons  including we don't want to encourage use of the library as a whole but rather its components.

**Comment by bcomnes** [comment]
I won't lie, a modularized jquery-mobile would be ideal (e.g. https://www.npmjs.com/browse/keyword/lodash-modularized), but I think there are some things that could be gained without going that far.

1.  Committing built assets to git is never good, agreed.  This is what [`prepublish` scripts](https://docs.npmjs.com/misc/scripts) + [.npmignore](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) are used for.  These allow you to publish built assets to npm, ensuring a fresh build on publishing, without committing them to git or publishing files not needed for running.  I could try to throw a quick/find a demonstration of its use if you are unfamiliar with it.

2. Publishing the necessary files to npm allows for custom task runners to perform custom builds of jquery-mobile assets coming in from npm (which is what you are hoping people do now?)

3. Publishing a built version of jquery-mobile to npm allows for shimming with https://github.com/thlorenz/browserify-shim.

4. The minor modifications mentioned in the npm post would afford quick require('jquery-mobile') without shimming or affecting anything else too much... although wouldn't promote a custom build.

If we can't get in touch with @gbraad I'm guessing it wouldn't be that much of a stretch to gain ownership of the namespace: https://www.npmjs.com/policies/disputes

I guess what I am primarily concerned with is that a built version of jquery-mobile gets published to npm (the same way I can hotload http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js), for use by  taskrunners, shimming for use with dependency management with npm.

**Comment by gbraad** [comment]
Hi guys... I wasn't aware of this discussion. I only published this package for my own needs and have to admit I haven't looked after it. I know jquery-mobile has a release on Bower, but at that time it did not fit my needs. I can remove it...

**Comment by arschmitz** [comment]
@gbraad yeah it would be great it we could get ownership of the npm package as we would like to publish the upcoming release to npm and continue to keep it up to date going forward.

**Comment by gbraad** [comment]
@arschmitz the easiest step would be to add you as collaborator first. I guess from there you can do anything. If not, we can always reach out to npmjs and ask them for support. What is the account name I can use? You can me a private message by email if needed.

**Comment by apsdehal** [comment]
@gbraad I am willing to do this, kindly add me as a collaborator.

**Comment by arschmitz** [comment]
@gbraad sorry got off on other things can you add me as a collaborator and i will cordinate with @apsdehal for moving this over to the official distribution

**Comment by gbraad** [comment]
Check. Will do so tomorrow (on mobile now)

**Comment by gbraad** [comment]
Done
