### ISSUE TITLE
Add commonJS export

### ISSUE THREAD

**Issue by bcomnes** [jquery/jquery-mobile#8304]
It would be great if I could simply require('jquery-mobile') in browserify like I can with jquery.  Instead I have to resort to something like https://github.com/thlorenz/browserify-shim or depend on load orders and global variables (ew!).

Would jquery mobile be open to adding a commonjs export to jquery-mobile?  It would involve a process like: http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm

**Comment by apsdehal** [comment]
I have discussed this with team and it require a lot of changes as of now. It would be better to use for https://github.com/jaredhanson/deamdify for unique usecases which require commonjs export.
