### ISSUE TITLE
degradeInputWithin loses events on inputs

### ISSUE THREAD

**Issue by dpeacock** [jquery/jquery-mobile#8317]
I ran across an issue using datatables with JQM where the search would not work.  It turns out the issue is related to the function degradeInputsWithin.  If you have an input with a type of search that you add to the page and have an event bound to that input, after calling enhanceWithin on the page the event is lost.

Here is a simple example of the issue (occurs even without datatables): http://codepen.io/anon/pen/zvRZjP
Select 'Add input', type in the input and you will see an alert.
Select 'Enhance', type in the input and you will see the alert no longer fires.

This is because degradeInputsWithin is trying to clone the element, and replaces the element with new html.  As a result, the events on the initial element are lost.  Set a breakpoint on:
element.replaceWith( html.replace( findstr, repstr ) );

Before this line executes check the events associated to the input ($._data(this).events), you will see the keypress.  After this line executes, if you check the events again, they are gone because the input has essentially been replaced.

Rather than replacing the input with new HTML, I would think I would think you could modify the existing input dom element to modify the attributes rather than creating the element from scratch.

**Comment by arschmitz** [comment]
@dpeacock this is intentional internet explorer does not allow changing the type property of on inputs and will throw an error the only way to do this is to replace the entire input. 

This behavior is deprecated in the upcoming 1.5 release

**Comment by arschmitz** [comment]
Im going to close this wont fix

**Comment by dpeacock** [comment]
Thanks for the info as to why this wasn't done.  Could you elaborate on exactly what is being depracated in 1.5?

From what I can tell the degradeInputsWithin in the 1.5-dev branch has the same behavior on the search inputs:

https://github.com/jquery/jquery-mobile/blob/1.5-dev/js/degradeInputs.js

**Comment by arschmitz** [comment]
@dpeacock degrade inputs itself is deprecated. This means it will still exist and be on by default in 1.5 but will be removed completely in 1.6
