### ISSUE TITLE
taphold doesn't prevent default

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery-mobile#8320]
Steps to reproduce:

1) Try any of these **on a real mobile device** (tested on Android 5.0, Chrome):
http://output.jsbin.com/kiwihi
http://output.jsbin.com/savesa

2) "Taphold" on the link that says "TAPHOLD ME"

Expected: in the first example the tapped node is replaced by a different node with different contents; in the second example the tapped node is not changed, but text is added after it. **In both cases the default behavior should be prevented**, due to the `return false` at the end of the event handler, so nothing more should happen.

Observed: the event is triggered correctly and the DOM manipulations are performed, but **the default is not prevented**, and hence, the usual menu that appears when you tap-hold on a link will show up.

Even using `preventDefault()` on the event instead of `return false` won't fix the issue.

**NOTE**: if you use Desktop Chrome (Linux at least) and emulate mobile in the Developer Tools, you will get different results: the first example won't work at all, showing the default menu without even executing the event handler.

**Comment by teo1978** [comment]
> NOTE: if you use Desktop Chrome (Linux at least) and emulate mobile in the Developer Tools, you will get different results

Well, this part is completely random. Sometimes it behaves like the real mobile device, sometimes it doesn't. But that's an issue in Chrome's devTools.

**Comment by kapilgarg1996** [comment]
The behaviour you want can be achieved by adding some css.
<code>a {
    -webkit-touch-callout: none !important;
}</code>

**Comment by teo1978** [comment]
That could be a workaround (I found it somewhere and read comments saying it didn't work in all platforms so I didn't even try it)

Another that works for me is adding a listener for the `contextmenu` event and preventing default there.

However, **neither should be needed**: jQueryMobile's implementation of the taphold event should take care of that.

**Comment by apsdehal** [comment]
Closing in support of tap events to be replaced using Hammer.js.
