### ISSUE TITLE
1.5-dev Panel: Page scrolls to top after closing a panel.

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#8323]
When you open a panel, scroll down, and then close the panel, the page scrolls to top. This was not the case in 1.4.5.

Test page: http://view.jquerymobile.com/1.5-dev/demos/panel/
For comparison: http://demos.jquerymobile.com/1.4.5/panel/

Tested on Chrome 46 on OS X.

This is also the cause of the problem with the Quick Links in our demos. Clicking the link makes the page scroll to the section, but because the panel closes at the same time the page immediately jumps back to the top.

**Comment by cgack** [comment]
@jaspermdegroot this looks like it was added with gh-6767 landing after the 1.4.5 release. Perhaps we should evaluate what we really want to happen here if this isn't desired.

**Comment by jaspermdegroot** [comment]
Ah you're right @cgack. I never noticed that ticket. Thanks!
I agree we should discuss this. I think we should only scroll to top if `ui-content` is out of view.
Will comment on that ticket and re-open it for discussion.
