### ISSUE TITLE
1.5-dev Panel: Toolbars don't transition together with content anymore

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#8324]
When opening/closing reveal and push panels, the header and footer don't transition together with the content anymore. I suppose this is because changes in the toolbar widget haven't been applied yet to the panel widget.

Test page: http://view.jquerymobile.com/1.5-dev/demos/panel/

**Comment by cgack** [comment]
making a note for my future self... these selectors should be changed here: https://github.com/jquery/jquery-mobile/blob/master/js/widgets/panel.js#L107-L124

**Comment by cgack** [comment]
It looks as though ui-toolbar-header isn't set by the time we are wrapping the content in ui-panel-wrapper, this is causing the headers to remain unwrapped. continuing to investigate

**Comment by cgack** [comment]
Closed via gh-8397
