### ISSUE TITLE
1.5-dev Listview: Truncation doesn't work with an icon

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#8325]
Trunctation of text in listview items to limit the text to one line doesn't work as expected with an inline icon. The text gets truncated with ellipsis but the icon wraps to a new line.

On Chrome 46 / OS X:

![image](https://cloud.githubusercontent.com/assets/1296793/11057120/cba44094-8788-11e5-9ae4-923290011a31.png)

**Comment by rgfpy** [comment]
up for the new version of jquery mobile!
