### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by acha5066** [jquery/jquery-mobile#8326]
Import of a previously downloaded, non-minified css file loads the visual styles in the theme roller ui, however the modal overlay does not go away unless you click cancel. 

The hex codes in the style picker on the left seem to be the default settings, while the UI itself is my theme.

I get the following in my console.

``` javascript
Error: Uncaught TypeError: Cannot read property '1' of null on line 1611 of app.js 

which is the code: 

//Function to convert hex format to a rgba color
TR.rgbatohex = function(rgba) {
    rgba = rgba.match(/^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/);
    return "#" + TR.hex(rgba[1]) + TR.hex(rgba[2]) + TR.hex(rgba[3]);
}

```

**Comment by acha5066** [comment]
Also, just to add the default theme imported fine, which is strange, because I never modified my custom theme file.

**Comment by jaspermdegroot** [comment]
@acha5066 

The ThemeRoller has its own repo and issue tracker: https://github.com/jquery/themeroller.jquerymobile.com/issues
Do you mind opening a new ticket there? Thanks!

I mean time I will try to reproduce the issue and find out what is the cause of it.
