### ISSUE TITLE
Custom Select Menu issue with iOS9

### ISSUE THREAD

**Issue by wwy94621** [jquery/jquery-mobile#8330]
After upgrade iOS9, popup will auto closed immediately when open it first time, I fixed this issue by add data-history="false". The custom select menu (dialog-style) has the same issue, but I have no idea about how to fix it.

**Comment by osos** [comment]
The custom select menu crashes on iOS 9.1 when run in apple-web-app-capable mode. Works fine in normal iPhone Safari.

**Comment by apsdehal** [comment]
@wwy94621 Kindly provide a fiddle using http://jsbin.com/huvoraba/1/edit?html,output

**Comment by apsdehal** [comment]
Closing, kindly reopen whenever fiddle is ready.
