### ISSUE TITLE
Filterable: Fix demos using data-role="listview"

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#8331]
When you use `data-filter-reveal="true"` to initially hide list items, the filter/search input itself gets hidden.

See: http://view.jquerymobile.com/1.5-dev/demos/filterable/#FilterReveal

**Comment by apsdehal** [comment]
The issue seems to be with listview instead of filterable, as the demo above filterReveal is also doesn't have any input. If filterReveal was not working it should also not work in case of search in navigation.

**Comment by apsdehal** [comment]
Discuss with arschmitz I got to know data-role="listview" is deprecated now. We need to update demos accordingly, Changing heading of the issue

**Comment by arschmitz** [comment]
@apsdehal not quite 

istview is not deprecated the list view auto filter functionality from 1.3 is in 1.4 we introduced the filter widget to replace it which no longer auto generates the input

**Comment by apsdehal** [comment]
Thanks. I actually meant: data-role="listview" is deprecated with a filterable.

**Comment by apsdehal** [comment]
Oh again wrong :p . Only autofilter is deprecated.
