### ISSUE TITLE
Listview('refresh') does not update the icons of list items

### ISSUE THREAD

**Issue by lukaseckert** [jquery/jquery-mobile#8334]
See
http://jsfiddle.net/us0egzdq/1/

I have a listview and would like to change the icon of one of it's entries after initialization (when the user clicks on it). Although the data-icon attribute of the < li > element is changed by the script, the listview('refresh') command will not update the icon class of the nested < a > element, so the new icon does not become visible.

Tested with jQM 1.4.5

**Comment by AHorak** [comment]
Any workaround for that?

**Comment by apsdehal** [comment]
Confirmed, for now you can manually remove ui icon class and add other one for workaround.

**Comment by gabrielschulhof** [comment]
* [ ] Add method ```updateItems()``` with optional collection which does sparing ```refresh()``` if the collection is not given and restricts itself to the collection if it is given.
* [ ] Change ```refresh()``` to agressively update all items and deprecate sparing ```refresh()```
