### ISSUE TITLE
Demo pages for buttons have me confused

### ISSUE THREAD

**Issue by SteveALee** [jquery/jquery-mobile#8335]
Reading the [button Widget](http://demos.jquerymobile.com/1.4.5/button/) page I got a little confused.

*  "Enhanced" buttons - I spent a while trying to figure what visuals or interactions were enhanced :) Eventually I read the API docs and read Enhancement is the PE that JQM provides and it seems you only need use data-enhanced if a parent turns enhancement off. But the demos do not make that clear as there is no parent turning it off. In fact the enhanced buttons appear to be doing something quite different - showing the text node in the parent div as a label with extra classes defined on the parent. 

Indeed the enhanced version seems be what  see in borwser F12 tools after JQM has done it's magic.

Can you point me to the docs about what exactly is going on or your point in included them is?

* "Icon-only buttons are round by default" - I can't see any difference between the 2 icon only buttons

**Comment by jaspermdegroot** [comment]
@SteveALee 

The `enhanced` option has been introduced to improve performance. You can always use this option if you want. When you set the option to `true` the widget's JavaScript will skip adding classes and/or generating elements which makes things faster. Your markup have to be exactly the same as it would be if it were enhanced by the widget. See also http://api.jquerymobile.com/button/#option-enhanced

I hope this makes it clear.

That "icon-only button with custom border-radius" demo is indeed broken. The custom style is missing :(
I made a working demo for you in a JSBin: http://jsbin.com/kiyeze/edit?html,output

Fixing that demo will be part of ticket https://github.com/jquery/jquery-mobile/issues/8245 so I am going to close this ticket as duplicate. Thanks for reporting it!

**Comment by SteveALee** [comment]
@jaspermdegroot  OK, thanks 

I got mixed up with `data-enhance` as documented on [Data Attributes](http://api.jquerymobile.com/data-attribute) when looking at the source. Easily done as only one letter difference! :)

Thanks for the jsbin demo. Much appreaciated even though I kinda guessed what it looked from from the similar example on the [Button markup](http://demos.jquerymobile.com/1.4.5/button-markup/) page.
