### ISSUE TITLE
Is there an outline of what's comming in 1.5?

### ISSUE THREAD

**Issue by SteveALee** [jquery/jquery-mobile#8336]
There's an awful lot of issues being in the milestone.
Any idea when it might land - other than 'when it's ready'?

Thanks

**Comment by ryanlin1986** [comment]
Yes we need a roadmap, timeline. Is this project abandoned or still alive, as compared to ionic, this is much less active.

**Comment by TimMagee** [comment]
There has not been a single commit since June. In other words, not a single developer has contributed ANY code in the past 5 months. I'm not sure when to call a project defunct, but jQueryMobile is seriously in need of more developers.

**Comment by arschmitz** [comment]
jQuery Mobile is by no means dead and we have had 231 commits since June and the commit you are talking about we simply moved development to the branch named 1.5-dev we are just about ready to release 1.5 we have 2 main blockers to finish and we will be releasing beta

**Comment by TimMagee** [comment]
Thank you for correcting my terrible misreading of commit logs. And I am so excited to hear that 1.5 will soon be released. I love jQuery Mobile!

**Comment by SteveALee** [comment]
@arschmitz @TimMagee I did manage to figure out you'd moved to the 1.5 branch and saw all the activity there. Hence my original question on this issue

However, I do feel the project status could be communicated better. The lack of clear communication on any of the obvious channels does give the impression of a very quiet project. My guess is lot of devs are keen to know the status.

For example:
* this [changlog] (https://github.com/jquery/jquery-mobile/wiki/1.5-Changelog) is stale (March)
* there's no info on the [1.5 milestone](https://github.com/jquery/jquery-mobile/milestones/1.5.0)
* Nothing on the [blog](http://blog.jquerymobile.com/) since 1.4 
* The [twitter channel](https://twitter.com/jquerymobile) is stale, though the [twitter hashtag](https://twitter.com/search?q=%23jquerymobile&src=typd) has very little community activity.

It all adds up to an impression that not much is happening and uncertainty if jQM is a safe dependency to have.

I *have* just discovered the [roadmap](http://jquerymobile.com/roadmap/) so assuming it is up-to-date can I suggest a link from the wiki here on github?

I also saw a note you use IRC. Is that used and archived so we can view past discussions? Or are you active somewhere else we can join in?

I'm keen to use jQM on my [latest project](https://github.com/OpenDirective/brian), primarily as it is the **only** frontend framework/library that explicitly supports Progressive enhancement. In my case I'm not so concerned of the project has become mature and stable without lots of new feature activity. But I do want to know what changes are coming up before I embark in a lot of custom code and styling. 

Thanks for an excellent project! Let me know if I can help in any way.

**Comment by SteveALee** [comment]
Only reopening as my initial Q was not answered. Thanks

**Comment by arschmitz** [comment]
@SteveALee Hi Steve we are actually going to publish a blog post shortly answering your question ill leave this open though until that is published.

**Comment by SteveALee** [comment]
@architecture that's good news especially as I still feel jqm is best option for PE, at least for now. I look forward to reading the post and thankd for the heads-up.

**Comment by arschmitz** [comment]
This was published http://blog.jquerymobile.com/2016/01/28/a-long-overdue-status-update/ an alpha will be out very soon waiting on one last pr to finish up
