### ISSUE TITLE
collapsible styles do not work well as child of ui-bar

### ISSUE THREAD

**Issue by thenewguy** [jquery/jquery-mobile#8338]
firefox console element explorer showing me the following is overriding the ui-collapsible-heading styles

.ui-bar h1, .ui-bar h2, .ui-bar h3, .ui-bar h4, .ui-bar h5, .ui-bar h6 {
    margin: 0px;
    padding: 0px;
    font-size: 1em;
    display: inline-block;
}

**Comment by marti1125** [comment]
Hi @thenewguy about collapsible 

> That said the collapsible widget has been deprecated in 1.5 and we are using the jQuery UI accordion widget instead which is properly accessible in all of our testing.

   https://github.com/jquery/jquery-mobile/issues/8382

please check this solution http://codepen.io/marti1125/pen/MyaKjr

**Comment by marti1125** [comment]
Hi @thenewguy  can I close this issue?

**Comment by thenewguy** [comment]
@marti1125 I am not really sure what you are showing me.  I've attached photos showing what it looks like

![screenshot-a pen by willy aguirre - mozilla firefox](https://cloud.githubusercontent.com/assets/77731/13796649/58282a7c-eade-11e5-8557-5ac96f80af55.png)

vs the demo

![screenshot-collapsible - jquery mobile demos - mozilla firefox](https://cloud.githubusercontent.com/assets/77731/13796655/5a2aede6-eade-11e5-9bfc-5bb7ece15f8f.png)

**Comment by marti1125** [comment]
the correct use of this... =/

```
.ui-bar h1, .ui-bar h2, .ui-bar h3, .ui-bar h4, .ui-bar h5, .ui-bar h6 {
margin: 0px;
padding: 0px;
font-size: 1em;
display: inline-block;
}
```

**Comment by thenewguy** [comment]
I greatly appreciate the attempt but I am not sure how you can help me.  The style selectors in jqm need to be adjusted.  But this isn't likely since the collapsible widget is depreciated.  The .ui-bar classes should not target the header in a collapsible or you end up with the look that your demo showed instead of the collapsible look like in the demos.

**Comment by marti1125** [comment]
in firefox  inspector I don't see ui-bar in  ui-collapsible-heading

![uibar](https://cloud.githubusercontent.com/assets/223240/13818763/2914b692-eb65-11e5-9498-5d997973578a.png)
http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.css
I think is for init ui-bar in general, simple demo http://codepen.io/marti1125/pen/YqNPme
http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.css same case but in it uses in header 
http://demos.jquerymobile.com/1.3.2/widgets/headers/

**Comment by thenewguy** [comment]
Your codepen doesn't place the collapsible as a child of a ui bar element does it? http://demos.jquerymobile.com/1.4.5/body-bar-classes/

Try moving the collapsible to the header like this http://codepen.io/anon/pen/PNWqwx

**Comment by thenewguy** [comment]
But I think I will just close this issue.  The widget is depreciated

**Comment by marti1125** [comment]
ok :)
