### ISSUE TITLE
Help！Why “data-native-menu="false” doesn't work?

### ISSUE THREAD

**Issue by pospospos2007** [jquery/jquery-mobile#8340]
<select name="papa" id="papa" data-native-menu="false" pId="2714" ></select>

ANGRY!!!!

**Comment by gseguin** [comment]
Angry? Go for a run, once you've calmed down and are ready to explain the issue you're having maybe you'll find help here or on the #jquery-ui channel on freenode.

**Comment by pospospos2007** [comment]
![qq 20151210142422](https://cloud.githubusercontent.com/assets/11675650/11708386/c3144cf2-9f49-11e5-98ec-2f821f489d1e.png)

here is brouser's console

and my jQuery Mobile version: 1.4.5

**Comment by pospospos2007** [comment]
![Uploading QQ图片20151210142811.png…]()

**Comment by pospospos2007** [comment]
thx,i had sovled my problem .the cause  i added a wrong JS file make me
crazzy

2015-12-10 13:45 GMT+08:00 Ghislain Seguin <notifications@github.com>:
