### ISSUE TITLE
Incorrect path to framework JS and CSS in demos

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#8342]
In the build, the path to the framework JS and CSS files in the demos is incorrect.

**Comment by jaspermdegroot** [comment]
Actually this was already broken on master and in 1.4-stable.

**Comment by jaspermdegroot** [comment]
It's not an issue when you go to the dist folder on a web server. Maybe I do something that's not supported, but I thought we changed file extensions to of demos files to .html because we want things to work without server as well.

**Comment by apsdehal** [comment]
@jaspermdegroot If I am not wrong, I think this has been fixed, right?

**Comment by arschmitz** [comment]
i fixed this forgot to close
