### ISSUE TITLE
tap event will be called automatically  if the element is appended to body in another tap event

### ISSUE THREAD

**Issue by thesadabc** [jquery/jquery-mobile#8346]
When I append a new div with a tap event  in a tap event, the new dev's tap event will be called automatically.

A demo [http://output.jsbin.com/bolibeqiba](http://output.jsbin.com/bolibeqiba)

This happened both in iOS 9.1' and Android 4.4' browsers, but didn't happened in desktop's browsers.

## Steps to reproduce

| step | expect | actual |
| --- | --- | ---- |
| tap the btn to append the new div (a red one) | new div will append to body | new div appended to body but its tap event was called (show a alert) |
| tap the new div | its tap event will be called | its tap event was called |

**Comment by marti1125** [comment]
Hi @thesadabc I'm confused @_@ you append a div in body and then tap event show and alert its ok for me... =?
http://codepen.io/marti1125/pen/qZObBJ
http://codepen.io/marti1125/full/qZObBJ/

`$layout.on('tap', ".child", function () {
		alert("child");
	});`
