### ISSUE TITLE
How to open popups through links with jquery mobile when there are ampersands within the URL?

### ISSUE THREAD

**Issue by WindohsCrasher** [jquery/jquery-mobile#8348]
I'm developing a web app using jQuery Mobile 1.4.5. I have a page where I pass GET parameters, e.g. like this:

`index.php?page=locations&id=12`

However, when entering the site with this URL and switching to another page using page transitions, there is no way a popup can be opened like this:

`<a href="#myPopup">click me</a>`

Popups can still be opened using the `$("#myPopup").popup('open');` function call, but this is not what I want.

If I remove the `&id=12` from the URL, the above link works correctly, so the problem must be the "&" sign within the URL breaking something internal in JQM. I guess there's some hidden referrer which still points to the original URL containing the `&id=12`.

This can be tested using the following: I've switched to page

`index.php?page=users`

coming originally from

`index.php?page=locations&id=12`

Then I changed the URL to the following by hand:

`index.php?page=users#myPopup`

What I got then was:

`index.php?page=locations&id=12#myPopup`

(which did nothing).

So is there any way I can get rid of this problem without having to switch to using Javascript calls? Maybe this is even a bug? I also need the GET parameters within my PHP scripts, so switching to another method is not what I'd like to do.

**Comment by apsdehal** [comment]
I tried replicating the scenario you mentioned in the demos page of jqm. But couldn't find the response as mentioned by you and worked as expected. Kindly check if there is some issue with your server side implementation. If problem persists, kindly reopen the issue with a demo.
