### ISSUE TITLE
First character is getting trimmed in listview data-filter

### ISSUE THREAD

**Issue by dineshg2t** [jquery/jquery-mobile#8351]
Hello all,
 I am just trying to make a phonegap application with JQM-1.4.5 framework and I have created a listview with a data-filter and I am just entering the text by means of a barcode scanner the issue is initially the whole text(Encoded in the BarCode) is getting entered but if I scan the same or someother barcode again the first character is getting trimmed.

P.S:I just tested by entering the code in a normal textbox by scanning the barcode it worked well all the time.

Please help me to solve this issue.

**Comment by apsdehal** [comment]
Please provide a fiddle as per contributing guidelines and reopen the issue.
