### ISSUE TITLE
transitions not work

### ISSUE THREAD

**Issue by leandrolimasi** [jquery/jquery-mobile#8352]
The transitions does not work when I have a list of over 50 items. The page changes correctly put without transition. The first 30 items work with transition, others are without transition.

I simulate de bug in JQM demo site: JQM 1.4.5

**Comment by anthonyac** [comment]
@leandrolimasi

This is a question probably more suited to the forums, but I'd venture that what you are finding is by design rather than a bug.

Refer to: http://demos.jquerymobile.com/1.4.5/transitions/#Maxscrollfortransitions

**Comment by apsdehal** [comment]
@leandrolimasi as mentioned in the previous comment, this happens due to performance reasons. Kindly refer to the link in the comment for more information. If you want to discuss this further, you can do so on #jqueryui on freenode.
