### ISSUE TITLE
white page flicker on page transitions

### ISSUE THREAD

**Issue by balabanmario** [jquery/jquery-mobile#8353]
Hi, 
I am developing a test application with phonegap and jquery mobile and I can see a white screen after clicking any navigation menu button. The source of the example app can be downloaded here: https://github.com/balabanmario/basicphonegap/ I'm using :  jquery-2.1.4 and jquery.mobile-1.4.5 The white screen does not show in "Ripple" but only on real device (Galaxy S III). Anybody has an idea why this is happening ? Thx.

**Comment by apsdehal** [comment]
Kindly provide a fiddle for use. See contributing guidelines for the same and reopen the issue.
