### ISSUE TITLE
Windows 10 App (JQM + Cordova) crashes after $.mobile.back();

### ISSUE THREAD

**Issue by nsteenbeek** [jquery/jquery-mobile#8359]
Configuration:
1) JQM 1.4.5 (Pagecontainer Widget for routing)
2) jQuery 2.2.0
3) Cordova (Building Windows-x64 App)

Installed on Windows 10, the App will crash using following reproduce:
1) Start application
2) Invoke $.mobile.back(); (in Javascript, so not a data-role="back" button)
3) Minimize app
4) Wait about 15 seconds => App crashes

Windows event log:
Event ID: 2484
Task Category: (2400)
Source: Apps
General: Package ... was terminated because it took too long to suspend.

It took me a full day to find that the $.mobile.back() was the reason. It may be a Windows problem as well, but I don't know.

**Comment by apsdehal** [comment]
@nsteenbeek Were you able to fix the issue? 
If not kindly provide me a fiddle so I can test it first on a Windows 10 browser.

**Comment by nsteenbeek** [comment]
Hi @apsdehal, It resulted in closing the Windows 10 app. When running directly in the browser it will not close the browser. So, that fiddler will not help, since you need an app.

**Comment by frankie-loves-jesus** [comment]
Creating a reduced test case is the best way to debug problems and report issues. Read http://css-tricks.com/reduced-test-cases/ on why they’re so great.

- A reduced test case clearly demonstrates the bug or issue
- It contains the bare minimum HTML, CSS, and JavaScript required to demonstrate the bug
- A link to your production site is not a reduced test case

Creating a reduced test case is the best way to get your issue addressed. They help you point out the problem. They help us debug the problem. They help others understand the problem.

**Comment by nsteenbeek** [comment]
We decided to extract JQM from our Software Product. Since It seems I'm the only one havingthis problem, it may be due to my configuration. So, let's close this issue.
