### ISSUE TITLE
$.mobile.changePage shows white screen on iphone 6s

### ISSUE THREAD

**Issue by Bukkanaresh** [jquery/jquery-mobile#8361]
Hi Friends,

I have 2 screens in Jquery Mobile. Home Screen and Send Message Screen. When a user clicks on a button on home screen, Send message screen is displayed. User will input some data in text fields and clicks on submit button in send message screen. Upon which user should see back Home screen.

The below code is working fine in all browsers except iphone 6s or greater version. From iphone 6s the screen is appearing for a fraction of seconds and then a white screen is populating on phone. There is a logic written in the script , so data-role="back" wouldn't be an option for me.

Can someone please help me on this problem

function _ReturnToHome() {
      $.mobile.changePage("#Home", { reverse: "true" });
        if(_isIOSSafari()) {

            setTimeout(function() { _setCompletionStatus(); }, 500);

        }
        else
            _setCompletionStatus();

**Comment by apsdehal** [comment]
Kindly reopen this by creating a fiddle representing your problem. Use template http://jsbin.com/ofuhaw/791/. Thanks.
