### ISSUE TITLE
Clicking on collapsible header expands wrong collapsible content

### ISSUE THREAD

**Issue by p60424** [jquery/jquery-mobile#8362]
I am using "jquery.mobile-1.4.5 min.js" and "jquery-1.11.1.min.js", but the collapsible sometimes shows the wrong content.

For example,
1. When I clicked the first title, it was highlighted with blue background but open the collapsible content of second title. (as following figure)
![ask1](https://cloud.githubusercontent.com/assets/13741347/12545979/ab8bc004-c381-11e5-8fe4-e0df6447ec60.png)
2. When I clicked the second title, it was highlighted with blue background but open the collapsible content of first title. (as following figure)
![ask2](https://cloud.githubusercontent.com/assets/13741347/12545956/7bd7d64a-c381-11e5-84df-4459ea373401.png)

This issue will happen highly if you click the collapsible between two titles.

The code of this test issue as following:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Error Event</title>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, height=device-height, user-scalable=no, initial-scale=1.0, minimal-ui"/>

<link rel="stylesheet" href="custom_v2.css"/>
<link rel="stylesheet" href="jquery.mobile.icons.min_v2.css"/>
<link rel="stylesheet" href="jquery.mobile-1.4.5.min.css"/>
<script src="jquery-1.11.1.min.js"></script>
<script src="jquery.mobile-1.4.5.min.js"></script>

</head>

<body>

<div id="container" data-role="page">
  <div id="header" data-role="header" data-position="fixed" data-tap-toggle="false" data-theme="c">
    <h1>Error Event</h1>
  </div>

  <div data-role="content" class="ui-content">
    <div data-role="collapsible-set">
      <div data-role="collapsible">
        <h1>Event ID 1</h1>
		  <table style="width:100%;border:2px double;" rules="all">
            <thead>
              <tr>
                <td><font size="1"><center><b>ID</b></center></td><td><font size="1"><center><b>Description</b></center></td><td><font size="1"><center><b>Time</b></center></td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><font size="1">ID 1</td><td><font size="1">test1</td><td><font size="1">2016</td>
              </tr>
			  <tr>
                <td><font size="1">ID 2</td><td><font size="1">test2</td><td><font size="1">2016</td>
              </tr>
            </tbody>
          </table>
	  </div>
	  <div data-role="collapsible">
        <h1>Event ID 2</h1>
	  </div>
	  <div data-role="collapsible">
        <h1>Event ID 3</h1>
	  </div>
	</div>
  </div>

</div>

</body>
</html>
```

Sorry about my poor English :'(

**Comment by apsdehal** [comment]
@p60424 I tried to replicate your issue in this [JSBin](http://jsbin.com/wonepiduxo/edit?html,js,output), but could not see the mentioned issue. Can you give more details about your platform?

**Comment by p60424** [comment]
@apsdehal 
1.
 I use my phone's browser to view the JSBin you supply, it will show the similar result as my issue both in iOS and Android. (click Event ID 1 and then click Event ID 2 quickly, both these two collapsible titles will highlight with blue background)
![screenshot_2016-01-26-09-27-52_com android chrome](https://cloud.githubusercontent.com/assets/13741347/12570026/46d5277a-c40f-11e5-9d8a-a768081ab330.png)


2.
I was put this testing web page in my server site and linked to it through the Chrome browser under the "Developer Tools (simulate as Apple iPhone 5)".
Under this situation, If you move mouse (which looks like a small black circle) between two titles (ex: between Event ID 1 and Event ID 2) then the wrong issue will highly happen after you click it. 

For example,
If the black circle is much nearer to Event ID 1 than Event ID 2, it will cause the issue as following figure.
![ask_n1](https://cloud.githubusercontent.com/assets/13741347/12569735/7b02b90c-c40c-11e5-945c-f492d7832f0f.png)

I'm not sure whether this issue is caused by the lower linked speed :-/

**Comment by apsdehal** [comment]
@p60424 I was able to reproduce the issue, and we will try to fix it. But collapsible is going to be deprecated in the upcoming version 1.5, so kindly use the accordion widget instead of that.

**Comment by apsdehal** [comment]
Collapsible is deprecated, kindly use accordion, if the issue persists kindly open an issue with ui.
