### ISSUE TITLE
Filterable custom selectmenu doesn't working for long list

### ISSUE THREAD

**Issue by wwy94621** [jquery/jquery-mobile#8363]
When I try filterable custom selectmenu from [http://demos.jquerymobile.com/1.4.5/selectmenu-custom-filter/](url), I found the last one (long list) doesn't working:
1. Can't close it with the cross at the left of header.
2. Can't select option, select any of them will empty the list.
3. I try it with iPhone, IE, Chrome, both of them doesn't working.

**Comment by marti1125** [comment]
Hi @wwy94621 I trying this https://jsfiddle.net/20zou0qb/
but I can not test  the example =/

**Comment by tomaszn** [comment]
The console reports "TypeError: listview is undefined" for this code:
`		listview = data.prevPage.jqmData( "listview" ),
		form = listview.jqmData( "filter-form" );
`

**Comment by wwy94621** [comment]
I found there is a bug in the demo, it's working now.
Thanks everyone.

**Comment by tomaszn** [comment]
Hi, the "long list example" doesn't work. "TypeError: listview is undefined"

**Comment by wwy94621** [comment]
Please check the demo, the bug in line 5, try to change it to 
"if (!pageIsSelectmenuDialog(data.prevPage)) {", and good luck.
*******************************************************************************************************************************
1 .on( "pagecontainerhide", function( event, data ) {
2		var listview, form;
3
4		// We only handle the disappearance of a dialog generated by a filterable selectmenu
5		if ( !pageIsSelectmenuDialog( data.toPage ) ) {
6			return;
7		}
8
9		listview = data.prevPage.jqmData( "listview" ),
10		form = listview.jqmData( "filter-form" );
11
12		// Put the form back in the popup. It goes ahead of the listview.
13		listview.before( form );
14	});
