### ISSUE TITLE
jquery issue on data-role="popup" on ios9

### ISSUE THREAD

**Issue by ourjouwan** [jquery/jquery-mobile#8367]
jquery issue on data-role="popup" on ios9
We are facing this issue on iOS devices , since we updated ipad and iphone to ios 9 before iOS 9 it was OK. the popup appears and suddenly disappear.

I have used the "data-history="false"" method, It doesn’t work.
Here is my code:

<div data-role="footer"  data-theme="a" data-position="fixed" >
<a href="#menu-items"  data-rel="popup"  data-transition="pop" data-theme="c" style="float:right; padding-right:1px;font-family:serif; font-style:italic" class="ui-btn-active1"> i </a>
				
<a href="" onclick='menu("audio_screen")' id="scanAudio"  class="classname" style="float:left; margin-right:5%;border-bottom-left-radius:0;  border-bottom-right-radius:0;border-top-left-radius:0" >
Audioguide</a>
					
							
<div data-role="popup" data-history="false" id="menu-items" data-overlay-theme="a" data-theme="c"  style="max-width:400px;" class="ui-corner-all">
<div data-role="content" data-theme="d" class="ui-corner-bottom ui-content">
						<ul data-role="listview" data-icon="false">
							<li style="font-size:14px; font-family:helvetica;"><a href="" onclick='menu("InMemoryOf")' >In memory of...main</a></li>
							<li style="font-size:14px; font-family:helvetica;"><a href="" onclick='menu("About")' >About</a></li>
							<li style="font-size:14px; font-family:helvetica;"><a href="" onclick='menu("VisitorInfo")' >Visitor Info.</a></li>
							<li style="font-size:14px; font-family:helvetica;"><a  href="index.html" >Change language</a></li>
						</ul>
						<p/>
					</div>
				</div>	
			</div>

**Comment by ourjouwan** [comment]
hello?

**Comment by ourjouwan** [comment]
nobody?
thanks

**Comment by arschmitz** [comment]
@ourjouwan we are a team of volunteers and cannot always respond to every issue immediately we all have full time jobs. Also you closed your issue which would indicate you found your problem. 

If you believe there is a bug in jQuery Mobile please see our contributing guidelines https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and include all the information listed there as well as a full jsbin test case using our template http://jsbin.com/ofuhaw/1/edit
