### ISSUE TITLE
change page inside document ready will reload/back to previous page in Safari (any ios/windows)

### ISSUE THREAD

**Issue by obxyann** [jquery/jquery-mobile#8368]
1. no problem in Firfox/Chome ** only in Safari ** (tested in iphone/mac and also last version 5.1.7 for windows)
2. uses 1.4.5 jqm and 2.1.4 jquery
3. when changing from an initial page to the my target pages in $(document).ready()
    it will back to initial page after show target page a while!

	$(document).ready(function() {
		console.log("Document ready...");
		$(":mobile-pagecontainer").pagecontainer("change", "#page1", { changeHash: false });
	});
4. a) if changed above changeHash: false -> true , no problem
    b) if repeated twice pagecontainer change to page1 continuously, no problem
5. if use $(document).on('pagecreate'..likes instead of $(document).ready still has the same problem

test file included:
[switchpage_2.zip](https://github.com/jquery/jquery-mobile/files/113563/switchpage_2.zip) in Safari
or
JSbin [http://jsbin.com/tuzoguleco/1/edit?html,js,console,output]( http://jsbin.com/tuzoguleco/1/edit?html,js,console,output)  load in Safari

**Comment by arschmitz** [comment]
calling `changpage` prior to the the app finishing loading is not currently supported

**Comment by blikblum** [comment]
You can use `Array.prototype.slice.call(this.el.attributes).forEach(attribute => ...)`
or
`Array.prototype.forEach.call(this.el.attributes, attribute => ...)`
