### ISSUE TITLE
Page is scrolled down issue in ios 9

### ISSUE THREAD

**Issue by scarus** [jquery/jquery-mobile#8369]
Hi,

We are having an issue with pages in ios9. When a page is opened it is scrolled down instead scrolled to the top?

**Comment by arschmitz** [comment]
Thank you for submitting this issue however without more information we are unable to investigate this. Please create a simple test page reproducing the issue using out jsbin template http://jsbin.com/ofuhaw/1/edit

If you are going back to this page or refreshing this is the correct behavior and what the browser does natively

Closing as incomplete if you provide a test case we will re open
