### ISSUE TITLE
Loading progress when external href

### ISSUE THREAD

**Issue by jrahma** [jquery/jquery-mobile#8371]
Can't use Loading progress when using external href.

Hope it will be be fixed / updated in future releases..

**Comment by arschmitz** [comment]
@jrahma please see our contributing guidelines. https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and create a jsbin test page using our template http://jsbin.com/ofuhaw/1/edit which reproduces the issue.

**Comment by apsdehal** [comment]
Closing as of now, kindly reopen with fiddle.
