### ISSUE TITLE
No Theme Editor

### ISSUE THREAD

**Issue by jrahma** [jquery/jquery-mobile#8372]
The current [theme roller](https://themeroller.jquerymobile.com) doesn't allow you to pick existing theme by url and change so everytime you have to create a new theme from scratch or copy paste to import.

I suggest to add Import options (by theme URL) to allow changing existing theme..

**Comment by arschmitz** [comment]
you can import any theme you have previously downloaded with the import button at the top and use it as a starting place

**Comment by jrahma** [comment]
but that does not import from URL...
