### ISSUE TITLE
Theme Gallery

### ISSUE THREAD

**Issue by jrahma** [jquery/jquery-mobile#8373]
In [theme roller](https://themeroller.jquerymobile.com/), I suggest you add Theme gallery for users to use from existing gallery by jquery team or by other users contribution.

**Comment by arschmitz** [comment]
@jrahma this is a great idea and something we are planning though in a bit of a round about way. We are planning on switching to the Chassis css framework once its ready and will use its themeroller. This has already been planned to support this type of functionality.

**Comment by jrahma** [comment]
Great. Thanks.
