### ISSUE TITLE
Jquery Mobile Datepicker

### ISSUE THREAD

**Issue by jrahma** [jquery/jquery-mobile#8374]
I suggest you add a new datepicker for jquery mobile instead of using the jquery datepicker sp users will feel it's a mobile datepicker similar to the native datepicker in iOS and Android.

**Comment by arschmitz** [comment]
We will not duplicate widget existing in jQuery ui quite the opposite we are attempting to share as much as possible. You can change the look and feel of any jQuery ui or mobile widget by adjusting the theme and css. We make this even easier in 1.5 / 1.12 of the libraries by adding the classes option for custom theming. http://stage.api.jqueryui.com/1.12/jQuery.widget/#option-classes

**Comment by jrahma** [comment]
but what I was talking about is something like this:

[https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/Art/uidatepicker_intro_2x.png](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/Art/uidatepicker_intro_2x.png)

**Comment by arschmitz** [comment]
Thats just a regular input with a type of date on iOS
