### ISSUE TITLE
Duplicate Swatch in Theme Roller

### ISSUE THREAD

**Issue by jrahma** [jquery/jquery-mobile#8380]
Please add an option to duplicate the swatch in theme roller because some users wants the same swatch but with minor modification so currently they have to do it all from scratch..

**Comment by arschmitz** [comment]
This option already exists. click the swatch tab you want and there are delete and duplicate options right at the top. This is also not the right repo for theme roller issue please use https://github.com/jquery/themeroller.jquerymobile.com

**Comment by jrahma** [comment]
Thanks :)
