### ISSUE TITLE
Anchors in collapsible headings should be buttons; need aria attributes

### ISSUE THREAD

**Issue by plweil** [jquery/jquery-mobile#8382]
The use of anchors here seems wrong. These elements are functioning as buttons; so why would you use an anchor instead of a button tag?

In addition, I suggest applying the aria-expanded and aria-collapsible attributes to this button. Right now all you have is aria-hidden="true" on the expandable content. This is fine, but is not enough to establish a relationship between the button and the content it controls (expands, collapses).

See http://heydonworks.com/practical_aria_examples/#progressive-collapsibles

**Comment by marti1125** [comment]
Hi @plweil why should be buttons insteand of `<a></a>` ?
I can use tab to focus and enter to expand
https://github.com/jquery/jquery-mobile/blob/master/js/widgets/collapsible.js#L153

**Comment by plweil** [comment]
Anchors are for links. Using them as buttons is bad semantics. Why confuse people using screenreaders with the wrong tags/semantics? If someone thinks that the anchor is a button (e.g., a keyboard user) and presses the spacebar, nothing will happen. That's unexpected behavior, because pressing the spacebar on a button will "click" it. Let's say someone isn't running javascript. They come across an anchor that doesn't actually link to anything; it just activates something via js. Nothing will happen if they click on it. Buttons are part of the tab order by default. There's a boatload of articles about this. Accessibility experts have written about it. Long story short: it's better to use the correct tags and semantics. It's a better way to code, and it's better for users.

**Comment by arschmitz** [comment]
@plweil you are correct about the accessibility issue we don't necessarily need to use buttons but if we use links we need to use proper aria attributes and handlers to make them work as expected.

That said the collapsible widget has been deprecated in 1.5 and we are using the jQuery UI accordion widget instead which is properly accessible in all of our testing. However if you do find any problems with it please let us know.

**Comment by plweil** [comment]
> On Mar 3, 2016, at 8:27 PM, Alexander Schmitz <notifications@github.com> wrote:
> 
> @plweil you are correct about the accessibility issue we don't necessarily need to use buttons but if we use links we need to use proper aria attributes and handlers to make them work as expected.

Yes, one could apply role="button" to anchors (or even to divs or spans, for that matter), but why bother with that? Why not use something with the correct native semantics already there?

> 
> That said the collapsible widget has been deprecated in 1.5 and we are using the jQuery UI accordion widget instead which is properly accessible in all of our testing. However if you do find any problems with it please let us know.

Thanks, I will take a look at 1.5 and the JQ UI accordion, since I am using the collapsible widget extensively.

**Comment by plweil** [comment]
I'm wondering: precisely what sort of accessibility testing the  jQuery UI accordion widget has been subjected to?

At first glance, at least, the code and approach seem dubious. Header tags using role="tab"? Is this an accordian or tabs?

This widget got a particularly poor writeup by the SSB Bart Group in 2013. Has anything changed substantially since then?

http://www.ssbbartgroup.com/blog/jquery-ui-accessibility-analysis/


As an alternative, the best "progressive" collapsible/accordian approach that I have seen can be viewed here:

http://heydonworks.com/practical_aria_examples/#progressive-collapsibles

As the example shows, you can put a button within an h3 and gain the advantages of both without altering semantics.

"a good-looking tabbed interface does not a good tabbed interface make — not on its own. Is the underlying structure properly semantic and accessible? The JavaScript shows one panel and hides the others, but is this action really communicated to everyone? Can everyone perform that action in the first place?"

Unless there have been significant improvements since 2013, I think JQuery Mobile can do better than what I've seen of the Jquery UI accordian widget.

Peter

**Comment by scottgonzalez** [comment]
> I'm wondering: precisely what sort of accessibility testing the  jQuery UI accordion widget has been subjected to?

A fair amount.

> At first glance, at least, the code and approach seem dubious. Header tags using role="tab"? Is this an accordian or tabs?

Accordions *are* tablists. See https://www.w3.org/TR/wai-aria-practices/#accordion

> Unless there have been significant improvements since 2013, I think JQuery Mobile can do better than what I've seen of the Jquery UI accordian widget.

Instead of assuming that nothing has changed in three years, perhaps you should only provide actual testing results showing accessibility problems rather than spreading FUD.

**Comment by plweil** [comment]
> Accordions are tablists. See https://www.w3.org/TR/wai-aria-practices/#accordion

They *can* be tablists, but they don't have to be. The best practices docs are working drafts, and the accordion section is undergoing a review. There is no official accordion "role", and accordions can be done differently. I gave you one example, and there are others that don't use tab-releated roles., eg., 

https://labs.ssbbartgroup.com/index.php/ARIA_Accordion

I am not affiliated with SSB Bart, but they have a lot of expertise in accessibillity.

This version uses buttons and adds the aria-controls attribute, which can enhance the experience for screenreader users.

This kind of combination of aria attributes, leaving out tab roles, and using buttons just might produce a better, more accessible and easier-to-use accordion widget, and as such merits consideration.

> Instead of assuming that nothing has changed in three years, perhaps you should only provide actual testing results showing accessibility problems rather than spreading FUD.

That was not my intent; I'm very sorry if it came off that way. No offense intended.

Thanks for your work in providing making this terrific tool available.

**Comment by scottgonzalez** [comment]
> This kind of combination of aria attributes, leaving out tab roles, and using buttons just might produce a better, more accessible and easier-to-use accordion widget, and as such merits consideration.

To be honest, a phrase like "just might" doesn't warrant the team trying out a different approach. If you can point to actual accessibility issues with the existing implementation, then we can talk about that. But accessibility is so difficult and there are multiple way to handle most widgets that constantly trying new things without explicit issues that need to be addressed just creates a LOT of work with little to no benefit. As much as we want to follow ARIA guidelines, we do deviate when it makes sense. But we only do so based on actual issues.

We even disagree on what an accordion is. ARIA says that accordions allow multiple tabs to be open, but we don't allow that. It's honestly a silly thing to define because if the panels have no relation to each other, then they're really just independent toggle boxes. So our accordion is actually much closer to a tablist than most accordions.

**Comment by apsdehal** [comment]
Closing as not relevant anymore. Use accordion and file any issues with ui.
