### ISSUE TITLE
Problem with loading jQuery mobile iframe inside hidden div.

### ISSUE THREAD

**Issue by jodator** [jquery/jquery-mobile#8383]
Loading a jQuery mobile App from an iframe that is located inside hidden div yelds errors in Firefox.

Test setup:
1. Top page that loads jQuery mobile app inside iframe.
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>App loader</title>
</head>
<body>
<div id="myApp" style="display: none;"></div>

<script>
	var myDiv = document.getElementById( 'myApp' );
	myDiv.innerHTML = '<iframe src="app.html">';
	// Show the "app" after some time
	setTimeout( function() {
		myDiv.style.display = '';
	}, 500 );
</script>
</body>
</html>
```
Page with jQuery mobile app (`app.html`):
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>App</title>

	<script src="http://code.jquery.com/jquery-1.12.0.min.js"></script>
	<script src="http://code.jquery.com/mobile/git/jquery.mobile-git.js"></script>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/git/jquery.mobile-git.css" class="css">
</head>
<body>
<div>This is me</div>
<script>
	jQuery( function() {
		console.log( jQuery.event.special.swipe );
	} );
</script>
</body>
</html>
```
Result: 
Errors are logged in console and the jQuery mobile doesn't start.
![selection_104](https://cloud.githubusercontent.com/assets/247363/13074072/9ddc8308-d4a2-11e5-8856-bff9b6111860.png)

Expected:
It should load jQuery mobile app.

Platforms:
This happens only on Firefox (tested on 44.0.2/Linux Mint LMDE).

**Comment by gibbok** [comment]
I confirm the same issue on FireFox 44.0.2 and on FireFox 46.0a2 (2016-02-15) (tested on Window 8.1 and Ubuntu 15.10)

**Comment by arschmitz** [comment]
this is a firefox bug but it should be pretty easy to work around https://bugzilla.mozilla.org/show_bug.cgi?id=548397

**Comment by apsdehal** [comment]
Closing as issue with firefox and not with jqm.
