### ISSUE TITLE
Multiple popups

### ISSUE THREAD

**Issue by Jahrenski** [jquery/jquery-mobile#8384]
I use popups for all kind of reasons. One of them being showing page content from another page.
This part works great except when I need a popup to ask the user for some stuff like confirming stuff deletion. The second popup will not open while the content popup is still opened.

I'm trying to do something as simple as: http://output.jsbin.com/qapizadino/1/

Any workaround to get this concept to work?

**Comment by jaspermdegroot** [comment]
@Jahrenski 

Chaining popups is currently not possible. This is a known/documented limitation of the popup widget. See "Note: Chaining of popups not allowed" here: http://api.jquerymobile.com/popup/. It also shows a workaround.
