### ISSUE TITLE
Dynamic page theme

### ISSUE THREAD

**Issue by Palestinian** [jquery/jquery-mobile#8385]
Changing theme dynamically does add correct class - e.g. `ui-page-theme-b` - but doesn't remove previous class - e.g. `ui-page-theme-a`.

    .page( "option", "theme", "swatch" );

The fix is within `_setOptions`; remove previous class using `.match()` inside `.removeClass()`.

    _setOptions: function(o) {
      if (o.theme !== undefined) {
        this.element
          .removeClass(function(i, c) {
            return (c.match(/\bui-page-theme-\w/g) || []).join(' ');
          })
          .addClass("ui-page-theme-" + o.theme);
      }
    }

Demo: https://jsfiddle.net/Palestinian/L6d9wxb2/

**Comment by marti1125** [comment]
:+1:

**Comment by Palestinian** [comment]
@marti1125 the fix isn't passing the test. You may try it yourself, if you feel like it :)

**Comment by apsdehal** [comment]
This should be working in 1.5, as we use `_themeElements` function now to get and apply themes. And method of changing themes would not be like this anymore. Refer widget.theme.js for more info.
