### ISSUE TITLE
[Web - Form Section] space between 2 sections

### ISSUE THREAD

**Issue by marti1125** [jquery/jquery-mobile#8392]
http://demos.jquerymobile.com/1.4.5/forms/

<img width="901" alt="captura de pantalla 2016-03-02 a las 02 24 19" src="https://cloud.githubusercontent.com/assets/223240/13495375/4cc07f92-e118-11e5-9cad-5ca11edf94d6.png">

**Comment by agcolom** [comment]
@marti1125 Do you mean the track being over the input field? If this is the case, there is a ticket for it with all the details https://github.com/jquery/jquery-mobile/issues/7991 and I believe this is fixed in master.

**Comment by marti1125** [comment]
ups sry is fixed https://github.com/jquery/jquery-mobile/pull/7999 =D
