### ISSUE TITLE
Textarea autogrow causes layout jumps

### ISSUE THREAD

**Issue by danatemple** [jquery/jquery-mobile#8393]
When typing in an autogrow textarea, every keypress causes a momentary setting of the height to zero. (code in _updateHeight()).

This can result in permanent change to the rest of the page layout, for example if a container scrolls. See example here:
http://jsbin.com/kineca/5/edit?html,css,output

The jump is clear, just type a key into the textarea. It even happens if no "grow" would have taken place.
The effect on a real web-app can be to move the users insert point off-screen!

jQuery Mobile 1.4.5, jQuery 1.11.1

Demonstrated here on Windows 7 / Chrome, but also seen on mobile platforms by other users.

**Comment by marti1125** [comment]
I think you don't need
```
.bigdiv {
  //height: 400px;
}
```

**Comment by danatemple** [comment]
No, probably not, as long as the textarea is long enough so you have scrolled.

**Comment by marti1125** [comment]
Hi @danatemple Could tell me what do you expect? what is the final design. please
I test in chrome and firefox

![textarea](https://cloud.githubusercontent.com/assets/223240/13795046/059035b8-eacd-11e5-9c30-f0cbeb55bdb1.png)

**Comment by danatemple** [comment]
What I expect is the scroll_container div not to suddenly jump back to the top, just because I typed a char in the textfield.

To reproduce, scroll down to the bottom of the textfield, type a char in it, and it will jump back to the top. 

Happens in every browser I've tried, including mobile.

You can see why if you look in the _updateHeight() call (in JSM source) - it momentarily sets the textfield height to zero, as part of its calculations. The browser does this, but the side effect is that the scroll is no longer necessary so scroll_container goes back to the top. Then, when the textarea is re-grown, you are no longer looking at where your cursor was.

regards, Dan

**Comment by marti1125** [comment]
thanks for the answer!! :D yes I saw that effect when I copy data in textarea the scroll go to top =/
I will try again later

**Comment by marti1125** [comment]
Hi @danatemple I am trying this http://jsfiddle.net/losnir/nnkeH/1/ from http://stackoverflow.com/questions/18262729/how-to-stop-window-jumping-when-typing-in-autoresizing-textarea I think is a bug with textarea

**Comment by apsdehal** [comment]
Closing as not fixable for now!
