### ISSUE TITLE
does not change page when submit button (IOS 9.2)

### ISSUE THREAD

**Issue by brody182** [jquery/jquery-mobile#8398]
`<button type="submit" id="submitBtn" onClick="storeLocalContent(document.querySelector('#firstName').value)" class="Button ctct-button Button--block Button-secondary" style="background-color:#3598DB; color:#ffffff; width: 260px; margin: 0 auto; position: relative;" data-enabled="enabled">Get Access2</button>`

form javascript code

```
$( "form" ).validate({
          messages: {
              name: "Name is required.",
              email: {
                  required: "Email is required.",
                  email: "You must provide a valid email address."
              }
          },
          errorPlacement: function (error, element) {
              error.appendTo(element.parent().prev());
          },
          submitHandler: function (form) {
              $(':mobile-pagecontainer').pagecontainer('change', '#benefits-facts', {
                  reload: false
              });
           return false;
          focusInvalid: false;
      }
      });
```

**Comment by brody182** [comment]
is anybody else having this problem?  When I submit the button it does not take me to the next page

```
$(':mobile-pagecontainer').pagecontainer('change', '#benefits-facts', {
                  reload: false
              });
```

**Comment by Palestinian** [comment]
submitHandler: function(form) {
      /* preventDefault here */
      $(':mobile-pagecontainer').pagecontainer('change', '#benefits-facts');
      /* reload is false be default */
      focusInvalid: false;
    }

**Comment by brody182** [comment]
it works in safari but not in the ios simulator

**Comment by apsdehal** [comment]
Kindly provide a jsbin and reopen the issue. See CONTRIBUTING.md
