### ISSUE TITLE
The demo page is missing

### ISSUE THREAD

**Issue by dotku** [jquery/jquery-mobile#8400]
Demo page: http://api.jquerymobile.com/jquery.mobile.loadpage/
And the demo won't work due the missing page: http://api.jquerymobile.com/resources/results.php

**Comment by jaspermdegroot** [comment]
@dotku - Thanks for reporting the issue! The API documentation has its own repo. I opened a ticket there https://github.com/jquery/api.jquerymobile.com/issues/387
