### ISSUE TITLE
jQuery Mobile Load failed?!

### ISSUE THREAD

**Issue by dotku** [jquery/jquery-mobile#8401]
I create a example over here: http://dotku.github.io/tech/jquery-mobile/jquery.mobile.loadPage-so.html
but it doesn't work :(

**Comment by happyhj** [comment]
error message is this 

> jquery.min.js:1 Uncaught Error: cannot call methods on pagecontainer prior to initialization; attempted to call method 'load'

```
    $('#clickButton').on("click",function(){
      $.mobile.loadPage("page.html",{pageContainer: $('#container')})
    });
```

You should initialise page container widget to **$('#container')** before using as pageContainer option value.

```
// Initialise before use
$( ".selector" ).pagecontainer({
  defaults: true
});

    $('#clickButton').on("click",function(){
      $.mobile.loadPage("page.html",{pageContainer: $('#container')})
    });
```

**Comment by Palestinian** [comment]
You can't have `pageConatiner` inside a page div. All pages should be children of `pageContainer`.

**Comment by apsdehal** [comment]
Closing as fixed @dotku kindly use #jqueryui on freenode for further help with implementation.
