### ISSUE TITLE
Demos: Submit in search is not working

### ISSUE THREAD

**Issue by apsdehal** [jquery/jquery-mobile#8407]
Works on tab + enter, since it focuses on button and then submits. Working on this one through keydown event on input.

**Comment by apsdehal** [comment]
@jaspermdegroot What is the expected response? As of now in #8406, I have shifted the `enter` key action to take user to the link which is highlighted through navigation. 

What I think of:
- When nothing is highlighted, take to search results
- Otherwise to the highlighted link.

**Comment by jaspermdegroot** [comment]
@apsdehal - Your last comment sounds right to me.
