### ISSUE TITLE
Using Hammer.js for touch events

### ISSUE THREAD

**Issue by bkazi** [jquery/jquery-mobile#8414]
I was interested in the GSoC idea of using Hammer.js to support the touch events in JQuery and would like some additional information on this

**Comment by jaspermdegroot** [comment]
@bkazi 

Here is the log of our team meeting from a few weeks ago in which we discussed this: http://irc.jquery.org/%23jquery-meeting/default_%23jquery-meeting_20160225.log.html#t14:16:44

**Comment by marti1125** [comment]
@jaspermdegroot I sent a draft about jQuery Mobile husting bugs but I did not receive any feedback :(

**Comment by arschmitz** [comment]
this is not the place for this closing
