### ISSUE TITLE
filterable widget "table filter" demo doesn't work well

### ISSUE THREAD

**Issue by szollosi** [jquery/jquery-mobile#8416]
1. when i type what is on the table head (rank, movie, title or year , etc.) it doesn't filter anything
2. http://demos.jquerymobile.com/1.4.5/filterable/
3. i just type texts into the search field
4. ?
5. ?
6. i tested chromium 49 and firefox 45 on debian 8.3 x64, another people tested on windows 7, too
7. your demo environment, as i see jquery.js version is 1.10.2, jquery.mobile.min.js version is 1.4.5

**Comment by marti1125** [comment]
demo uses the last version view-source:http://demos.jquerymobile.com/1.4.5/filterable/
I didn't find any bug about this.

**Comment by szollosi** [comment]
how can i switch off that feature, when i type in the search input field of "filter table" demo (second demo on this page) that words what is in the table head (ie. "rank", "movie", "title", "year", etc), it doesn't filter anything? :)

i attach 3 screenshot:
1. when i filter text what is in table title, it doesn't filter anything. i think it must filter out the entire table
2. when i filter text what is in table body, it filters right
3. when i filter text what is not in the table, it filters right

![filter-title-text](https://cloud.githubusercontent.com/assets/16032126/14224037/291df5be-f88e-11e5-9bf4-84c832e1dcb6.png)
![filter-body-text](https://cloud.githubusercontent.com/assets/16032126/14224038/34c7b210-f88e-11e5-817e-b2b8ddb3e99f.png)
![filter-anything-else-text](https://cloud.githubusercontent.com/assets/16032126/14224039/38943116-f88e-11e5-8fb9-564b01d6f788.png)

**Comment by marti1125** [comment]
**data-filter="true" on the table element to generate a filter for table rows. **
you need a new feature for filter columns

**Comment by szollosi** [comment]
as i see the data-filter="true" is on the table element. the "table filter" demo is this:

`<form>
    <input id="filterTable-input" data-type="search">
</form>
<table data-role="table" id="movie-table" data-filter="true" data-input="#filterTable-input" class="ui-responsive">
    <thead>
        <tr>
            <th data-priority="1">Rank</th>
            <th data-priority="persist">Movie Title</th>
            <th data-priority="2">Year</th>
            <th data-priority="3"><abbr title="Rotten Tomato Rating">Rating</abbr></th>
            <th data-priority="4">Reviews</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <th>1</th>
                <td><a href="http://en.wikipedia.org/wiki/Citizen_Kane" data-rel="external">Citizen Kane</a></td>
                <td>1941</td>
                <td>100%</td>
                <td>74</td>
            </tr>
            <tr>
                <th>2</th>
                <td><a href="http://en.wikipedia.org/wiki/Casablanca_(film)" data-rel="external">Casablanca</a></td>
                <td>1942</td>
                <td>97%</td>
                <td>64</td>
            </tr>
            <tr>
                <th>3</th>
                <td><a href="http://en.wikipedia.org/wiki/The_Godfather" data-rel="external">The Godfather</a></td>
                <td>1972</td>
                <td>97%</td>
                <td>87</td>
            </tr>
        </tbody>
    </table>`

no, i don't want to filter columns, i just want to filter rows, but when i type string "rank" into the search filter it doesn't filter anything, but it must filter all rows.

**Comment by marti1125** [comment]
because this behavior is from listview. table Inherited filter from listview
https://github.com/jquery/jquery-mobile/blob/master/js/widgets/filterable.backcompat.js#L193
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.js

https://github.com/jquery/jquery-mobile/blob/master/js/widgets/filterable.js#L29 (use tbody for filter)
I hope it clear for you... =/ or maybe you add Rank in tbody okno =(

**Comment by szollosi** [comment]
not clear for me, why the filter works differently when i type "qq" or "jj" - which is not in tbody - and when i type "ov" or "ws" - which is not in tbody either. one difference what we found is "ov" and "ws" found in thead.

**Comment by marti1125** [comment]
Hi @szollosi  I found an example in stackoverflow. This example uses jqm 1.4.0
 http://stackoverflow.com/questions/21257556/jquery-mobile-how-to-table-search-bar
http://jsfiddle.net/ezanker/fr8Yd/2/
![rank_jqm](https://cloud.githubusercontent.com/assets/223240/14358605/4d18e2a2-fcb3-11e5-9516-5cd49406e6cf.png)
![jqmdemofilter](https://cloud.githubusercontent.com/assets/223240/14358606/4d46f412-fcb3-11e5-86d8-f13e9bd03b5c.png)

Hi @arschmitz could you help with this if it is a issue in demo?

**Comment by szollosi** [comment]
hi, i tested with data-mode="columntoggle". when i set this attribute, the filtering works fine. without it the filtering doesn't work well.

**Comment by apsdehal** [comment]
Kindly use SO or #jqueryui for implementation related questions. Demo as I see is working fine as expected.
