### ISSUE TITLE
JQuery Mobile stuck on loading spinner

### ISSUE THREAD

**Issue by yomasa** [jquery/jquery-mobile#8420]
"<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>"

using chrome on mobile, opening html page locally on phone

**Comment by marti1125** [comment]
Hi @yomasa could you use http://jsbin.com/huvoraba/1/edit?html,css,js,output for a better explanation?

**Comment by agcolom** [comment]
Yes, It seems to be a security issue. When I do this (open a local file with JQM on my machine, I get this error message: 
___
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file://macintosh%20hd/Users/anne-gaellecolom/Documents/jQueryStuff/localJQMTest.html' cannot be created in a document with origin 'null' and URL 'file://macintosh%20hd/Users/anne-gaellecolom/Documents/jQueryStuff/localJQMTest.html'.

**Comment by arschmitz** [comment]
@agcolom jqm cant nor ever could work with the local file protocol

**Comment by apsdehal** [comment]
Closing as not a bug with jqm's implementation.

**Comment by yomasa** [comment]
That's  basically because it works on my cell phone in firefox
