### ISSUE TITLE
Core CSS: There is no space between the button text and the icon, if the icon is floatbeginning/floatend

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#8422]
@jaspermdegroot wrote in #8309:

> > There also seems to be a problem with the arrow icon in the button. Can you tell me what I'm doing wrong?
> 
> I suppose you mean the lack of space between text and icon? Since we make the icon float with class `ui-widget-icon-floatend` we will have to add extra padding to the button. Maybe we should do that in core/button CSS, not in selectmenu CSS. Will look into that.

**Comment by jaspermdegroot** [comment]
Actually we don't have to add padding to the button, but margin to the icon. I had absolute positioning of the icon (like we used to this) in my mind when I wrote that. Will add the margin.

**Comment by jaspermdegroot** [comment]
Landed in 1.5-dev. Closing.
