### ISSUE TITLE
JQuery mobile text field not loosing focus on clicking a radio button.(On Android phone)

### ISSUE THREAD

**Issue by kiranphp** [jquery/jquery-mobile#8423]
`I` am new to JQuery mobile and Cordova.I created a simple Cordova application with JQuery mobile having a form with a simple text-field and a radio input.However I noticed a problem when the application was run as I typed in some text and click on the radio button ,I notices the focus is still on the text input.If JQuery mobile was not used or if data-role is set to none for the input element, the focus will be out from the text input.I know that JQuery mobile adds some default styles to these form elements.I don't want the focus to be in text-field when I choose to select a radio button.Please help me on this.

Reference link for the same problem posted in stackoverflow is given below.
[http://stackoverflow.com/questions/35278521/jquery-mobile-text-field-not-loosing-focus](url)

**Comment by apsdehal** [comment]
jQuery issue system is specifically for bugs which don't match the given description of action. From future, kindly use SO or #jqueryui on IRC for questions related to implementation. Closing as of now.
