### ISSUE TITLE
JQuery mobile problem with scrollTop

### ISSUE THREAD

**Issue by pooyamoha** [jquery/jquery-mobile#8425]
In the following link I have attached a sample of my source code:

http://jsfiddle.net/ezanker/xY7tx/2382/

I have a list of 34 items when you press down the keyboard and you reach the 10th item, it would successfully scrollTop to 11th element. But when you keep pressing down and when you reach 30th item, with my code it supposed to scrollTop to 31th item but it isn't.

To reproduce the bug please keep pressing down on keyboard and pay attention to the 30th ---> 31th item which is not desirable (and compare it with 10th --> 11th item change which is desirable).

If i have done any mistake, my apologies and please show me in the source code what change should I make so that in change of 30th to 31th item, it would scrollTop as well. Thanks!

P.S:  as you can see in jsfiddle url link, I have used Jquery Mobile 1.3.1 (because of hardware compatibility I think I have to use version of 1.3.X)

**Comment by pooyamoha** [comment]
The problem is that i  am setting

var container = $('div'),
but jQuery Mobile automatically creates a page div to wrap around your code if you do not explicitely provide the div. Change it to

var container = $('#listAddr'),


please delete this thread it was my fault. Thanks!

**Comment by apsdehal** [comment]
It is working as expected by your code. It is not able to scrollTop to 31st element because there are no more elements after 34 to scroll down. Kindly use SO or IRC #jqueryui to ask questions regarding implementation. Thanks, closing as of now.
