### ISSUE TITLE
jquery mobile, error with select menu in Android with Chrome version 50

### ISSUE THREAD

**Issue by faabalia** [jquery/jquery-mobile#8429]
I have updated my Chrome browser to last version and I have the following problem:

When I select an option of a select menu it does not appear selected, I repeat the process of the selection and then it is selected OK. If I try to select other option it happens the same, first time bad, second time OK. It is happening since I have update to version 50 of Chrome, with previous version 49 it worked OK.

I am using a Huawei Y5 with Android 5.1.1, it happens the same with a Nexus with Android 6.

The version of jquery mobile that I have is 1.4.5

It seems only happens with Chrome version 50 in Android, in desktop works fine. In the browser that Huawei has, works OK.

To test this problem is easy, just go to the demo of select menu of jquery mobile:

http://demos.jquerymobile.com/1.4.5/selectmenu/

One important thing, in previous versions of jquery mobile works fine, examples:

http://demos.jquerymobile.com/1.3.2/widgets/selects/

Is there any way to resolve this problem? Any help would be appreciated.

Thanks in advance,

Félix.

**Comment by lukebarber** [comment]
We are also having this issue and can replicate it - for us, it's specifically Chrome 50.0.2661.8. 

A video showcasing this issue is here: https://goo.gl/photos/StTKphg79r1ZZKTJ8

Once the dropdown appears and flashes, no selections can be made (the dropdown disappears, but the selection is not kept).

**Comment by arschmitz** [comment]
ping @gabrielschulhof can you check the updated selectmenu against this

**Comment by dannygunawan** [comment]
> When I select an option of a select menu it does not appear selected, I repeat the process of the selection and then it is selected OK. If I try to select other option it happens the same, first time bad, second time 

I am also having this issue but not for all select menu, but only when the select menu is placed inside a panel.
```
<div data-role="page" id="mainmenu" data-theme="b">
    <div data-role="header" data-theme="b" data-position="fixed" data-tap-toggle="false">
        <a href="#nav-panel"><i class='fa fa-bars'></i></a>
        <h1>Header</h1>
    </div> 
    <div data-role="content" id="page1">
    </div>
 <div data-role="panel" id="nav-panel" data-overlay-theme="a" data-display="push">
        <div class="ui-bar ui-bar-b">Menu</div>
        <ul data-role="listview" data-iconpos="left" data-divider-theme="b" data-theme="a">
            <li class="profilepanel">
                <select id="profilepanel1" data-native-menu="true" data-theme="a" class="profilepanel">
                </select>
            </li>
        </ul>
</div>
</div>
```
It works fine with Desktop, Cordova iOS 9.3, but happens with Android.

JQM: 1.4.5 & JQuery: 2.1.3 & Android 6.0.1 & Chrome (Android) 48.0.2564

**Comment by faabalia** [comment]
The issue in my case happens always and we don't have the selectmenu placed inside a panel.

JQM: 1.4.5 JQuery: 2.1.1 Android 5.1.1 & Chrome (Android) 50.0.2661.89

**Comment by clintirving** [comment]
@faabalia - I'm also currently experiencing this same issue.  I believe it has to do with a conflict between JQuery Mobile hiding the data-position="fixed" elements on the page (i.e. the header and footer) and the native android select options menu.

As a workaround if you hide the header and footer earlier than JQuery Mobile normally does, things work correctly.

Here's a simple test page to demo this:

`
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="http://demos.jquerymobile.com/1.4.5/js/jquery.js"></script>
    <script src="http://demos.jquerymobile.com/1.4.5/js/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="http://demos.jquerymobile.com/1.4.5/css/themes/default/jquery.mobile-1.4.5.min.css">
    <script type="text/javascript">
        $(function() {
            $("select").mousedown(function() {
                $(".ui-header").addClass("ui-fixed-hidden");
                $(".ui-footer").addClass("ui-fixed-hidden");
            });
        });
    </script>
</head>
<body>
    <div data-role="page">
        <div data-role="header" data-position="fixed">
            Header
        </div>
        <div role="main" class="ui-content">
            <form>
                <div class="ui-field-contain">
                    <label for="select-native-1">Basic:</label>
                    <select name="select-native-1" id="select-native-1">
                        <option value="1">The 1st Option</option>
                        <option value="2">The 2nd Option</option>
                        <option value="3">The 3rd Option</option>
                        <option value="4">The 4th Option</option>
                    </select>
                </div>
            </form>
        </div>
        <div data-role="footer" data-position="fixed">
            Footer
        </div>
    </div>
</body>
</html>

`

The little bit of added JQuery adds the same classes that would have been added by JQuery Mobile anyway (just a little earlier).  Don't worry, they get removed by JQuery Mobile again when the select loses focus.

**Comment by clintirving** [comment]
Looking further into this...

I have to question the logic behind JQuery Mobile hiding the toolbars on select element focus by default. The native browser select elements overlay the page in their various special ways, and even the non-native select popup (which you get when specify the data attribute data-native-menu="false" in html or nativeMenu: false in the selectmenu options) is absolutely positioned as a dialog. This means that the toolbars really do not intrude on the real-estate given to the selectmenu options as they'll always overlay everything including the toolbars. To me, this makes the code from line 12664 - 12692 commented as: this hides the toolbars on a keyboard pop to give more screen room rather unnecessary for select elements.

Workaround/solution: thankfully jQuery-Mobile does nicely allow you to override this setting in your header/footer with the data-attribute data-hide-during-focus - simply set this to:

data-hide-during-focus="input, textarea"

and it won't try to hide the toolbars anymore when a select element gets focus.

**Comment by faabalia** [comment]
Hi Clint, 
First of all thank you very much for your answers. 
I have tried both of them and the first one works fine in portrait, but in landscape does not work. 
The second solution works in both orientations, but I've found one issue: if I enter data in an input text, close the keyboard and try to select an option of a combo, the issue happens. If instead of close the keyboard, I tap the screen and after that I select one option, then it works fine. I think that the focus out of the input and the focus in of the select do not synchronize very well in that case.

**Comment by clintirving** [comment]
Hi @faabalia 

I'm glad my second solution works for you - it's definitely the better option as it's much closer to addressing the cause than the first option which was a pretty far-fetched workaround.

Interesting observation regarding the text input - don't worry, there's a solution to this which just expands on my previous answer.  By adding **data-hide-during-focus="input, textarea"** jquery-mobile will still attempt to hide the header/footer for input and textarea fields.  As you've observed, this still causes issues for your selectmenu field because it attempts to show the header and footer again when the input text field loses focus.  You can entirely remove the hide header/footer on focus functionality by instead adding

**data-hide-during-focus=""**

to your header and footer.

**Comment by faabalia** [comment]
Hi Clint, 

I have tested your suggestion but if I put input, data-hide-during-focus="" it does not work , I have the same issue as If do not put it. I think that it attempts to show the header and footer again for all the elements (select, input, textarea, ...).

Debugging with Chrome in line 12670 of jquery mobile file the value of o.hideDuringFocus has the value: "input, textarea, select".

**Comment by clintirving** [comment]
Hi @faabalia - check to make sure that you have put data-hide-during-focus="" in both your header AND your footer.  Also check to make sure that Chrome isn't loading a cached page (it often does this).  I reproduced your scenario yesterday and I believe this does fix the issue.  The value "input, textarea, select" for o.hideDuringFocus is just the default value in jQuery mobile of hideDuringFocus - adding the data-attribute overrides this.

**Comment by crs2m5** [comment]
Hi @lukebarber i have exact issue as you. i have tried the solutions of adding data-hide-during-focus="" 
to both header and footer and to no avail. has anyone tried this and not work still?

**Comment by faabalia** [comment]
It works OK, except two case: if I am in an input field entering data and after that I just close the keyboard and then go to a select menu and display the options, the flash happens again and it does not work. The second situation that does not work is when I am in the input entering data with the keyboard shown, if I go directly to a select menu, the flash happens and when I try to select an option it is not selected. Really I don't understand why this happens.

**Comment by SteveUnger** [comment]
Hi, I tried to create a bugfix code but it doesn't work.
`if (Support.browser === "android" && Support.version > 49) {
		$(document).on("pagecreate", function(event) {
			var $pageParts = $(event.target).find("div[data-role='header'], div[data-role='footer']");
            $pageParts.attr("data-hide-during-focus","");
            
		});
	}`

The attribute is inserted to DOM but it doesn't work correct like
`<div data-role="footer" data-theme="b" data-position="fixed" data-hide-during-focus="">`

Any idea?

**Comment by crs2m5** [comment]
So i am able to get part of my drop downs to work now. after adding the 
`data-hide-during-focus=""`

to header and footer at the end of the tags, i can select items . but it still flickers twice  when i touch it on a mobile device

any ideas?

**Comment by zaferlatif** [comment]
Given solutions I've tried, but did not get results. However, I am having the same problem on Facebook. 

https://www.facebook.com/zaferlatif35/videos/vb.599157345/10154124374237346/

**Comment by faabalia** [comment]
Testing with the beta version of Google Chrome and Android WebView System (51.0.2704.36) works fine.

**Comment by dconversa** [comment]
I have the same problem on Samsung Tab A, Android 5.0.2, WebView 50.0.2661.86, Chrome 50.0.2661.89.
I have added the attributes as in the example, but still doesn't work.
<div data-role="header" data-position="fixed" data-tap-toggle="false" data-hide-during-focus="input, textarea">
<div data-role="footer" data-position="fixed" data-tap-toggle="false" data-hide-during-focus="input, textarea">

**Comment by nthapakiTransplant** [comment]
I'm still facing same issue with Android version 6.0.1. Not able to select item from the dropdown. Any idea? I tried everything written in above comments, Didn't work out.

We have our mobile version site where we use JqueryMobile for all control whereas on the same site we have one button which redirects user to desktop version of the site. After redirecting to that page , dropdown doesn't work. This is happening only in Android device specially in latest version. Any help much appreciated. Thanks

**Comment by arschmitz** [comment]
@nthapakiTransplant are you saying the dropdown on your desktop page which does not use jQuery Mobile does not work after redirecting to it from the jQuery Mobile site?

**Comment by nthapakiTransplant** [comment]
Yes. You are correct.

**Comment by nthapakiTransplant** [comment]
It works fine in all other mobile devices, same page but only doesn't work in Android device version 6.0.1 and with Chrome version 50.0.2661.89.

**Comment by arschmitz** [comment]
@nthapakiTransplant that can't possibly be jQuery Mobile if jQuery mobile is not on the page your having the issue with.

**Comment by redbeed** [comment]
I have the same problem with Bootstrap (Version 3.3.6) and when i set the css prop. **transition** to **none** it works fine.

**Comment by jdecastroc** [comment]
As @redbeed said changing transition to none works like a charm. I had a select form were I couldn't pick any option but after adding style: "transition: none" it worked perfectly. Thanks!

**Comment by vecmezoni** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=613885

**Comment by CrimsonLabs** [comment]
Just experienced this issue as well. Installed Chrome Beta from android app store, and disabled Google Chrome, and the problem is no longer there. Definitely looks like a Google Issue.

**Comment by ankush86** [comment]
Experienced this issue on my application as well. It really frustrating. Works fine with older version of chrome but not for update Chrome version 50+.

Any idea when get this issue resolved  ? Or Suggestion to fix this issue.

Thanks

**Comment by CrimsonLabs** [comment]
Sadly Google Beta updated this morning, now having the same issue there.

**Comment by SteveUnger** [comment]
Now working with chrome 51.0.2704.77 on android 6.0.1 (Galaxy S6) and the problem is solved.

**Comment by CrimsonLabs** [comment]
For anyone still battling with this, put the following code after your selectmenu has been created

```
        $("select").on('vmousedown', function(e) { $(this).focus().click(); });
        $("select").on('tap', function(e) { $(this).focus().click(); });
```

**Comment by faabalia** [comment]
I have tried this and not worked for me.

**Comment by faabalia** [comment]
The only way work for me is like SteveUnger says.

**Comment by CrimsonLabs** [comment]
This must be called after you have created the select with jQuery Mobile

**Comment by vivekbhushantiwari** [comment]
Hi Clint,

Your answer is working perfectly. We can add below workaround to resolve that keyboard focus issue. Below function can be called from any radio/checkbox/button/ selectbox click
        /**
	*Method name : _setFocus
	*@me : reference object to which focus needs to be assigned (eg. $(this))
	**/
	function _setFocus(me){
		try{
			me.focus();
			console.log($(":focus"));
		}catch(e){
		}
	}

**Comment by apsdehal** [comment]
I have tested on Chrome version 50.0.2661.89 using 1.5-dev http://view.jquerymobile.com/1.5-dev/demos/selectmenu/ and can confirm it is fixed.
