### ISSUE TITLE
Javascript alert() not working on my jQuery Mobile app after pressing back button on Safari 9

### ISSUE THREAD

**Issue by Tormand** [jquery/jquery-mobile#8444]
I created this app for a class and noticed some strange behavior when I tested it on my iPhone, which uses Safari 9. On Firefox(desktop), Chrome(desktop), and Safari 8(mobile), this problem doesn't happen.

Here is the jsbin, using the predefined template: Edit: Here's a persistent jsbin; didn't realize they disappeared: http://jsbin.com/tahepi/edit?html,js,output

As you can see, giving incorrect output creates an alert message. However, on Safari 9, if I click to go to page 2, then click the back button to go back to the first page, the alert no longer functions when incorrect input is given and the button is pressed. The rest of the Javascript does work, including what happens when correct input is given.

I suspect this is a jQuery Mobile issue because it doesn't happen using plain jQuery.

What's causing this and how would I go about fixing it?

**Comment by apsdehal** [comment]
@Tormand I tried your Bin on Safari 9, but I am not able to reproduce your issue. Alert seems to working fine for me when I follow the steps you wrote. It would be good if you can check again.

**Comment by Tormand** [comment]
I just tried it on my iPad which is running iOS 9.3.2. On entering the page, if I leave the input field blank and press "convert," I get an alert for incorrect input. But if I click Page 2, then click the browser's back arrow, and once again press "convert," with the field still empty, I do not get an alert. Nor do I get an alert if I enter a negative number of a letter. However, if I do put a positive number in the field, the currency is converted as usual, which means that the alert portion of the convert() function is the only part malfunctioning.

**Comment by Tormand** [comment]
Here is an exceedingly simple example. Just a few lines of code: http://jsbin.com/yebado

I just tried it on my iPhone, with iOS 9.3.2.

1. Click button, see alert.
2. Click "Page Two" to go to second page.
3. Click the back button on the mobile browser.
4. Press the button again. No alert.

Let me know if you can replicate this issue. Again, I assume it's a Jquery Mobile Issue but I could be wrong. Any ideas would be appreciated.

**Comment by Tormand** [comment]
I have discovered that this behavior occurs on the site regardless of whether jQuery mobile is included in the header. But it only happens when "data-role: page" is used.
