### ISSUE TITLE
Custom download builder shoud include a comment listing the included components

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery-mobile#8478]
Use case: 
- I downloaded a custom build of jquery.mobile years ago using http://jquerymobile.com/download-builder/ including only some of the components.
- now I want to update it to the latest version

=> now I have no easy way of knowing which components I had included in the original download.

The download builder should add a comment at the beginning of the generated file listing the components that were included. 

jQueryUI does that.

**Comment by arschmitz** [comment]
We are in the process of switching to share the UI builder. This is also not the repo for the download builder see https://github.com/gseguin/node-amd-builder for the current builder.

**Comment by arschmitz** [comment]
FWIW i agree with you which is a part of why we are switching
