### ISSUE TITLE
migration to jQuery 3.1.0 using jquery mobile Version 1.4.5

### ISSUE THREAD

**Issue by devshisiyani** [jquery/jquery-mobile#8484]
Will jquery mobile Version 1.4.5 work with the latest jQuery 3.1.0.
Has anyone done the migration yet.

**Comment by arschmitz** [comment]
1.4.5 should work with jQuery Migrate

**Comment by jaspermdegroot** [comment]
Closing since it's a question, not a bug, and it has been answered.
