### ISSUE TITLE
Duplicate id in slider tooltip demo

### ISSUE THREAD

**Issue by karenbennett** [jquery/jquery-mobile#8499]
There are 4 sliders demonstrated in http://demos.jquerymobile.com/1.4.5/slider-tooltip/

The fourth, mini version, has the same id, slider-3, as the third.

Could be fixed by changing slider-3 to slider-4 in lines 36 and 37 in jquery-mobile/demos/slider-tooltip/index.php

**Comment by jaspermdegroot** [comment]
@karenbennett - Thanks for reporting this. I added a fix for this to PR https://github.com/jquery/jquery-mobile/pull/8494.
