### ISSUE TITLE
Dialogs are in the backstack

### ISSUE THREAD

**Issue by ceblanda** [jquery/jquery-mobile#8504]
Prior to JQM 1.4, I created dialogues using data-role="dialog" and those pages were not added to the back stack, so navigating off one and then pressing back would bring you to the page before the dialog.

Now with 1.4.5, dialogues are defined as data-role="page" with data-dialog="true". Using this method, the dialog is added to the back stack, so if I navigate off the dialog and then tap back I am returned to the dialog.

**Comment by arschmitz** [comment]
That is correct and not a bug the dialog widget which provided this functionality was deprecated your simply making a dialog styled as a page with data-dialog=true

**Comment by ceblanda** [comment]
But it is inappropriate to go 'back' to a dialog.  There needs to be a way to stop the behavior.
