### ISSUE TITLE
The dialog background changes with the overlay.

### ISSUE THREAD

**Issue by vrbvillor** [jquery/jquery-mobile#8509]
I use the `data-overlay-theme="b"` but the content of the dialog changes to theme-b too, and can't modified to theme-a.

```
<a href="#DialogId" data-transition="slidedown">弹出对话框</a>

<div data-role="page" data-dialog="true" id="DialogId" data-close-btn="right" data-overlay-theme="b">
    <div data-role="header">
        <h1>我是一个对话框！</h1>
    </div>

    <div data-role="main" class="ui-content">
        <p>对话框与普通页面不同，它显示在当期页面上, 但又不会填充完整的页面，顶部图标 "X" 用于关闭对话框。</p>
        <a href="#pageone" data-rel="back">跳转到第一个页面</a>
    </div>

    <div data-role="footer">
        <h1>对话框底部文本</h1>
    </div>
</div>
```

![qq 20160831113649](https://cloud.githubusercontent.com/assets/8016761/18121004/00415a86-6f95-11e6-99f5-b083894d72eb.png)

**Comment by jaspermdegroot** [comment]
Thanks for reporting the issue. We will look into it.

Test page: http://jsbin.com/qoqesimenu/edit?html,output

**Comment by apsdehal** [comment]
This is happening because `ui-content` has default transparent background and thus final rendered background for `ui-content` is black.

**Comment by arschmitz** [comment]
It should be transparent the real problem is when its a dialog we should set the `ui-page-theme-*` class on the `ui-dialog-contain` element not `ui-dialog`

**Comment by jaspermdegroot** [comment]
@arschmitz is right.

**Comment by apsdehal** [comment]
Yeah, we discussed this and I will open up a PR soon

**Comment by jaspermdegroot** [comment]
Also, `.ui-dialog { background: none !important; }` looks a bit ugly to me. I am sure we can do that without the `!important`.

**Comment by arschmitz** [comment]
@jaspermdegroot we should be able to totally drop that rule now we should never define a background on ui-dialog

**Comment by apsdehal** [comment]
Closing as this is no longer a problem with current master, for which cdn hasn't been updated. We are applying `ui-body-a` class to `dialog-contain` which solves the issue. Bin with latest master used and corrected markup: http://jsbin.com/yejoqirono/1/
