### ISSUE TITLE
Is there a table or a list to tell the changing?

### ISSUE THREAD

**Issue by vrbvillor** [jquery/jquery-mobile#8510]
The documentation says that most of `data-attr` will be replaced with class `ui-xxx`. Is there a table or a list to tell which `data-attr` will be replaced with which class ?

**Comment by jaspermdegroot** [comment]
@vrbvillor 

Each new version comes with an upgrade guide and changelog. These can be found on the website [jquerymobile.com](http://jquerymobile.com).
Please note that this issue tracker is meant for bug reports. For questions you can use the (forum)[https://forum.jquery.com/jquery-mobile].
