### ISSUE TITLE
The page is there , but the console shows error.

### ISSUE THREAD

**Issue by vrbvillor** [jquery/jquery-mobile#8514]
```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///G:/PHP/WWW/newsite/jqmobile-1.4.5/news.html' cannot be created in a document with origin 'null'.$.extend.squash @ jquery.mobile-1.4.5.js:2954$.extend.initializePage @ jquery.mobile-1.4.5.js:15383(anonymous function) @ jquery.mobile-1.4.5.js:15427x.Callbacks.c @ jq1.10.2.js:4x.Callbacks.p.fireWith @ jq1.10.2.js:4x.extend.ready @ jq1.10.2.js:4q @ jq1.10.2.js:4
```

It was ok just now. But doesn't work now. It only matters in Chrome.

**Comment by Eccenux** [comment]
See here: http://stackoverflow.com/questions/32453806/uncaught-securityerror-failed-to-execute-replacestate-on-history-cannot-be

**Comment by apsdehal** [comment]
Closing as this is something related to chrome not jqm. `pushState` only works on a Web Server. You can check for more details at https://bugs.chromium.org/p/chromium/issues/detail?id=301210
