### ISSUE TITLE
selectmenu black box in Chrome

### ISSUE THREAD

**Issue by Jahrenski** [jquery/jquery-mobile#8518]
I have a weird behavior with JQM's selectmenu's on Chrome with mobile emulation mode activated. (It happens on Both Chrome 52 and Canary 55)

When you click the selectmenu to open it, it opens a black empty offscreen window instead as shown in the attached screenshot.

![blackbox](https://cloud.githubusercontent.com/assets/3932920/18277781/ad2b1c00-741d-11e6-922d-1742a405a5e8.png)

This occurs on your demo page as well located at : http://demos.jquerymobile.com/1.4.5/selectmenu/#ui-page-top

- Expected outcome would be for the selectmenu to show the options in a list.
- Actual outcome is that weird black window.
- Tested on Chrome 52 and Canary 55 both with Mobile emulation activated.
- Tested with JQM 1.4.5

**Comment by apsdehal** [comment]
I tried but not happening for me
![image](https://cloud.githubusercontent.com/assets/3616806/18278228/4e62ba96-741f-11e6-8e6c-66500949cdca.png)

**Comment by Jahrenski** [comment]
Wow, I have no idea why this happens on my machine. I tried resetting Chrome/Canary settings - dev tools settings and even reinstalling but it keeps giving me that black thing. I guess we can close this ticket as this seems to be some voodoo with Chrome itself.
