### ISSUE TITLE
scrollable popup - can't select checkboxes

### ISSUE THREAD

**Issue by asdfrog** [jquery/jquery-mobile#8529]
As per my question in the jQuery forum, with jQuery mobile 1.4.5 you can't select a checkbox in a scrollable popup.  This works in 1.4.4

I'm not sure what best practise is for adding code directly or providing a link sorry.  Link to the issue with example code follows

https://forum.jquery.com/topic/popup-with-scrollbars-can-t-select-checkbox-at-bottom-of-popup

**Comment by apsdehal** [comment]
@asdfrog Please review repo's Contributing guidelines https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md and create a JSBin for the issue.

**Comment by asdfrog** [comment]
@apsdehal I created a JSBin (http://jsbin.com/juvizupofu/edit?html,output) and the issue appears solved.

Can I clarify though that https://code.jquery.com/mobile/git/jquery.mobile-git.js is V1.4.5?

To be clearer about the issue, I am opening the popup via the 'Open the Dialog' link and trying to select the 'Test Checkbox' at the bottom of the popup. In V1.4.4 this worked fine, but in V1.4.5 it doesn't

**Comment by apsdehal** [comment]
This is 1.4.5 https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.js , the one you used is 1.5-pre. Try replicating with that.

**Comment by asdfrog** [comment]
OK, thanks @apsdehal I've updated the JSBin (http://jsbin.com/wevekayaji/1/edit?html,output) to use jQuery mobile 1.4.5, and the issue does exist in this example.

**Comment by HoussemRomdhani** [comment]
How can I fix this issue whithout changing the version of jQuery mobile (1.4.5) ?
