### ISSUE TITLE
anchor tag href="javascript:myMethod()" does not work

### ISSUE THREAD

**Issue by marioja** [jquery/jquery-mobile#8533]
I know that adding a click event handler can achieve the same purpose but I am generating the markup for a listview using anchor tag and I would like to add the binding to the javascript method in the markup.  I tried setting the data-ajax="false" but it did not work either.  Here is my javascript code:

``` javascript
    var cl=''
    cl+='<ul data-role="listview" data-inset="true" data-shadow="false">'
    cl+='<li data-role="collapsible" data-iconpos="right" data-inset="false">'
    cl+='<h2>clef</h2><ul data-role="listview">'
    cl+='<li><a data-ajax="false" href="javascript:renderInitial(clefs.treble)"><img src="images/treble.png"></a></li>'
    cl+='<li><a data-ajax="false" href="javascript:renderInitial(clefs.base)"><img src="images/bass.png"></a></li>'
    cl+='</ul></li>'
    cl+='</ul>'
    gummydiv.append(cl)
```

**Comment by apsdehal** [comment]
@marioja Can you generate a js bin example using your code based on contribution guidelines? Please reopen this one when you do.
