### ISSUE TITLE
When is this thing going to be released ????????

### ISSUE THREAD

**Issue by Chez** [jquery/jquery-mobile#8541]
If it is not a viable solution anymore, in other words if you have given up on it then perhaps someone would be kind enough to tell us developers who need to urgently update our apps and sites. It seems very unfair the way this dev team have maintained deadly silence and a clear lack of concern for those out there using the legacy platforms. We can't update jquery to the latest version either. So what to do, rewrite the apps with another framework, causing considerable overheads and loads more dev time or just sit and pray that someone with some courtesy  will put us out of our misery one way or the other.

**Comment by iArnoldo** [comment]
I am also wating for for a new version so bad...

**Comment by chdh** [comment]
In my application, jQuery Mobile 1.4.5 works with the latest jQuery version (3.1.1) after I installed the JQuery Migrate plugin (jquery-migrate-3.0.0.min.js).

**Comment by caique02** [comment]
Unfortunately dev team is dead quite. The framework is really good and it will be a pain to re-write using another framework but if this is the case dev team should give an update so we can start the re-work.

**Comment by apsdehal** [comment]
1.5-alpha is ready and we are reviewing changelog and docs right now. Here is a PR if you wanna take look: https://github.com/jquery/jquerymobile.com/pull/133 

You can use the master anyway, as 1.5 branch has been merged into it.
