### ISSUE TITLE
Can not center "Controlgroup" with 1.5.0-alpha.1

### ISSUE THREAD

**Issue by coordinate** [jquery/jquery-mobile#8550]
Can not center 'Controlgroup' with 1.5.0-alpha.1 by add 'align="center"' to content 
[demo](http://output.jsbin.com/somoyac)
<a class="jsbin-embed" href="http://jsbin.com/somoyac/1/embed?html">JS Bin on jsbin.com</a><script src="http://static.jsbin.com/js/embed.min.js?3.40.3"></script>

**Comment by apsdehal** [comment]
`align="center"` is not valid html anymore. You specifically need to set styles to the elements.

**Comment by arschmitz** [comment]
@coordinate despite this not being valid it is actually working as intended. Controlgroups are display block by default and therefor 100% width if you would like to center using the align attribute you cant use block elements and will need to set the controlgroup to be `inline-block`
