### ISSUE TITLE
New Component - spinner

### ISSUE THREAD

**Issue by djmj** [jquery/jquery-mobile#8561]
A mobile optimized spinner component would be great to enhance usability.

**Comment by arschmitz** [comment]
Its coming we will be working to incorporate the jQuery ui one along with the other ui widgets. 1.5 include from UI button, controlgroup, checkboxradio, tabs, and accordion.

**Comment by djmj** [comment]
That sounds good. If available i will try to write a component for PrimeFaces mobile based on it.

**Comment by apsdehal** [comment]
Closing this for now.

**Comment by djmj** [comment]
Please reevalute to open this issue. 5.0 alpha demo does not seems to have a mobile equivalent of https://jqueryui.com/spinner/ component.

When user needs to input a small amount of integer (like the quantity of a item in shopping cart), it is much more convenient to just press a + or - icon to edit the value instead of clicking inside a text-input.
