### ISSUE TITLE
DOM XSS JQuery Mobile basetagtest Function

### ISSUE THREAD

**Issue by Ajay88** [jquery/jquery-mobile#8567]
Hello All,

Recently ran into a potential DOM XSS vulnerability with the basetagtest function of JQuery Mobile 1.3.1 as reported by a vulnerability scan that was run using Burp Suite Professional Edition. I'm very much a beginner in security as well as programming and would like someone to explain whether this is an actual issue or not as well as why it is or isn't an issue. The function in its entirety I'm concerned with is below:

```
function baseTagTest() {
	var fauxBase = location.protocol + "//" + location.host + location.pathname + "ui-dir/",
		base = $( "head base" ),
		fauxEle = null,
		href = "",
		link, rebase;

	if ( !base.length ) {
		base = fauxEle = $( "<base>", { "href": fauxBase }).appendTo( "head" );
	} else {
		href = base.attr( "href" );
	}

	link = $( "<a href='testurl' />" ).prependTo( fakeBody );
	rebase = link[ 0 ].href;
	base[ 0 ].href = href || location.pathname;

	if ( fauxEle ) {
		fauxEle.remove();
	}
	return rebase.indexOf( fauxBase ) === 0;
}
```

I believe the part I should be concerned with is the href to location.pathname, though I'm not sure if it was this tid-bit that Burp Suite was alerted by. It's very possible that this is a false positive and is certainly reinforced by the fact that the most current stable version on JQuery Mobile (1.4.5) still has the exact same function written into it, since it seems somewhat unlikely that this was overlooked. Can someone weigh in on this?

**Comment by apsdehal** [comment]
Search on what a base tag is supposed to do.
