### ISSUE TITLE
Conform to strict mode

### ISSUE THREAD

**Issue by ravijayaramappa** [jquery/jquery-mobile#8569]
This request is to make jquery-mobile strict mode compliant. The use of 'this' to refer to window violates strict mode rules. The following pattern is being used to pass window as a parameter to functions.
(function( $, **window**, undefined ) {
 .... 
})( jQuery, **this** );

For some context, there were two PR's posted back in 2012 to fix this issue: https://github.com/jquery/jquery-mobile/pull/3607
https://github.com/jquery/jquery-mobile/pull/4318

**Comment by apsdehal** [comment]
This is no longer an issue with latest master.
