### ISSUE TITLE
Filterble widget handles the enter key incorrectly

### ISSUE THREAD

**Issue by pstanton** [jquery/jquery-mobile#8571]
if you are typing into the text field, then press enter nothing happens, but then your next key press has no effect. eg:

1. focus on text field
2. press a ('a' appears in field)
3. press enter (no change)
4. ***press a (no change)***
5. press a ('aa' appears in field)

this can be easily reproduced on the [demo page](https://api.jquerymobile.com/filterable/)

**Comment by Palestinian** [comment]
It looks like remove `event.preventDefault()` in `_onKeyPress` solves it.

    _onKeyPress: function(event) {
      if (this._preventKeyPress) {
        //event.preventDefault();
        this._preventKeyPress = false;
      }
    },

http://jsfiddle.net/Palestinian/myzqtx6f/

**Comment by apsdehal** [comment]
No longer an issue with latest master, closing for now. I will reopen if I find it after more testing.
