### ISSUE TITLE
Listing default properties for jqm widgets in documentation.

### ISSUE THREAD

**Issue by ryantheleach** [jquery/jquery-mobile#8573]
https://stackoverflow.com/questions/44298075/how-do-i-find-the-default-properties-to-set-on-jquery-mobile

I'm not sure if this is user error, or if there is an issue with the tool. Any help would be appreciated.

**Comment by ryantheleach** [comment]
Ok, ended up finding it after some url exploration.

But it didn't help my original question like I thought it was going to.

JQM docs state that defaults should be set using mobileinit event, before jqm is loaded.

$.mobile.page.prototype.options.contentTheme = "z"; for example.

I've been looking for a way to dump all the potential default properties that can be set.

It would be handy, if in the next version there was a page in the documentation detailing all the default properties in one handy location for each of the widgets.

**Comment by arschmitz** [comment]
http://api.jquerymobile.com/global-config/ has everything already

**Comment by ryantheleach** [comment]
So I take it that answers like https://stackoverflow.com/questions/4891906/jquery-mobile-default-data-theme are either not intentional, or supposed to be set?

or 

 $.fn.buttonMarkup.defaults.corners=false;

**Comment by apsdehal** [comment]
See the link arschmitz mentioned for the options that you can set.
