### ISSUE TITLE
1.5 Release date

### ISSUE THREAD

**Issue by groodt** [jquery/jquery-mobile#8587]
Hi

Is there likely to be a release date available for the stable version of 1.5? I am aware the alpha is available, I'm just wondering if the 1.5 release has lost momentum.

Thanks
Greg

**Comment by mindchasers** [comment]
On 09/05/2017 05:09 AM, Greg Roodt wrote:
>
> Hi
>
> Is there likely to be a release date available for the stable version 
> of 1.5? I am aware the alpha is available, I'm just wondering if the 
> 1.5 release has lost momentum.
>

I have been wondering the same thing.    There hasn't been a commit on 
master since Jan 2, 2017: 
https://github.com/jquery/jquery-mobile/commits/master

An IRC jquery-mobile meeting is scheduled for tomorrow (Thursday 9/6) at 
2:00 PM (Eastern Time).  Can someone from the jquery-mobile development 
team please join in and provide an update?

https://meetings.jquery.org/

Bob

**Comment by arschmitz** [comment]
Yes there will be a new release very soon. There will also be a significant announcement about jQuery Mobile and its team either this week or next look out on both the mobile and UI blogs for more info

**Comment by groodt** [comment]
> Yes there will be a new release very soon

Glad to hear things are still moving. I'll keep an eye out for an update in the coming week.

**Comment by groodt** [comment]
Was there any announcement?

**Comment by arschmitz** [comment]
Sorry we are still working on the blog post and some details that were discussed in meeting yesterday will be within next few days

**Comment by CharLiPPS** [comment]
>  will also be a significant announcement about jQuery Mobile 

Excellent news!. Thanks Alex. Everyone is waiting to c the news!

**Comment by groodt** [comment]
I'm eagerly waiting too. I've not seen anything. Did I miss it?

**Comment by slavap** [comment]
@arschmitz Few days are passed, and still we have no announcement :-( How guys are you going to compete with other frameworks? Just look at Bootstrap, Polymer, ... - they have daily commits and active community.

**Comment by frankie-loves-jesus** [comment]
@slavap as much as I love jQM my personal belief is that this project is on life support. It's simply not needed anymore, and I believe most devs know that. Say if you develop with Ruby on Rails, you already have turbolinks to replace the pagecontainer. Most other things in jQM you can easily do yourself with a little bit of JS/CSS, plus then you don't have to do custom builds to get rid of the endless list of widgets and stuff you'll never need. The todo-list has also gotten so big that.. well, to some devs I guess it's just tempting to start fresh on something new instead. Again just my personal belief, jQM has been my girlfriend for years and will always have a special place in my heart. Thanks!

**Comment by slavap** [comment]
@frankie-loves-jesus For me situation is quite different, I'm using almost all widgets from jqm and that is not enough, so I have additional ones, like jquery datatables. And for example filterable selecmenu should be provided not as example, but core widget. What is really bothers me, that jqm has some "hacks" for ancient mobile browsers, like iOS5 Safari, and they have nothing to do with iOS10/11.

**Comment by mxkeke** [comment]
When will available the blog post? ... just to understand what is happening

**Comment by sdondley** [comment]
I started rewriting a project I did a couple of years ago and I was surprised to see jQuery Mobile hasn't been updated since. Now I'm wondering if I should move to something different. Ugh. I was at least familiar with jQuery Mobile and I'm not looking forward to learning a new framework.

**Comment by mxkeke** [comment]
Should we consider the delay of one month from the blog post announcement in a positive or negative way? What has happened in the meantime in the organisation of the project?

**Comment by socklint** [comment]
<bump>I have an old project that I would prefer to update rather than moving to a new framework.
 Any word on this? The use of earlier versions of jQuery increases this project’s attack surface.</bump>

**Comment by pandric0** [comment]
Hi there,
just wondering if very soon in weeks is relative to month or year :D (just kidding) when will it likely to release and what about "significant announcement" I know that it's a free framework and efforts are and have been made but can we please have some news even if it's bad, because other dev-teams depend on it ? 
thanks.

**Comment by tyrex1975** [comment]
Such a shame to see JQM dying like this. We have an app based on it, and everyone who uses it loves it, but we're finding it really hard to keep it relevant when all the other frameworks are moving on so quickly. Non-native form inputs (like dropdowns/radios etc.) is where it really excels for us - it keeps the look and feel consistent across all devices - nothing comes close. We'd love to get it migrated to 1.5 but with very little documentation, no ongoing announcements and no questions being answered, it's a fruitless exercise.

An honest question; how can we (the developer community) help get it moving again?

**Comment by apsdehal** [comment]
Hi,
We are in process of revamping the structure, first we are moving to slack (join [here](https://join.slack.com/t/jqueryui-dev/shared_invite/enQtMjU4MzcwMDYyMDAwLTllMTc3Njg5ZjQxMjVjY2RmNzU0YWQyYjUwOTcwOTBiMjRhMzdhY2U0MmRlNWNkNzQ1NGYzNTczY2ZlYjBiYmM)). Further, we have 1.5 ready, you can consider it to be in beta version. I have been working on updating documentation [here](https://github.com/jquery/api.jquerymobile.com) which is mostly complete. 

You can help us by opening up the issues by testing the 1.5 and opening up PR with fixes if possible. I believe that through slack it would easier to connect, discuss and fix issues that come up in testing of PR. 

About blog post, @arschmitz had it ready, so he should post it soon (he is probably busy with lot of other work). It would be great if community can help us in maintaining the project by fixing existing bugs or implementing new features.

**Comment by amin007** [comment]
i wait the new version sooooooooooooooooooooooooooooooooooooooooo
loooooooooooooooooooooooooooooooooooooooooooooooooooooooooog

**Comment by KrunchMuffin** [comment]
Sneh

**Comment by cheehow** [comment]
Hi, does anyone have any news on this? I have a JQM 1.45 web app that needs to be upgraded to jQuery 3.3.1.

Noticed the 1.5.0-rc1 was released in Sept, does it mean the stable 1.5.0 is impending?

**Comment by sachinya** [comment]
@slavap this dint work for me. I am also using jquery 3.3.1 and jqm 1.4.5 even after applying your changes it is giving the "e.preventDefault is not a function " error but the screen is not hanging now

**Comment by sachinya** [comment]
> Hi, does anyone have any news on this? I have a JQM 1.45 web app that needs to be upgraded to jQuery 3.3.1.
> 
> Noticed the 1.5.0-rc1 was released in Sept, does it mean the stable 1.5.0 is impending?

Did you get a solution ?

**Comment by Bachstelze** [comment]
The 1.5.0-rc1 didn't change the operating source code. So it is still the alpha version.

**Comment by amin007** [comment]
"amin007 commented on Nov 24, 2017"
i wait for two year ...

**Comment by amin007** [comment]
> The 1.5.0-rc1 didn't change the operating source code. So it is still the alpha version.

mmm

**Comment by ecadius** [comment]
In the meantime there were several security fixes, but if you want to use then you have to build from source since the [download builder](https://jquerymobile.com/download-builder/) isn't working. Adventitious, there isn't an update guide and @arschmitz doesn't want contributors to help with this.

**Comment by amin007** [comment]
> In the meantime there were several security fixes, but if you want to use then you have to build from source since the [download builder](https://jquerymobile.com/download-builder/) isn't working. Adventitious, there isn't an update guide and @arschmitz doesn't want contributors to help with this.

are they losing interest in continuing?
