### ISSUE TITLE
 Cannot read property 'concat' of undefined 

### ISSUE THREAD

**Issue by Dhanasekaranjones** [jquery/jquery-mobile#8589]
I'm using jquery mobile latest version and using jquery.min.js latest version.
but i see the error  
Uncaught TypeError: Cannot read property 'concat' of undefined at jquery.mobile-1.4.5.js 
![jquery](https://user-images.githubusercontent.com/31949378/30466631-e19ea9f6-99fc-11e7-8087-455360e28f71.PNG)

**Comment by Dhanasekaranjones** [comment]
Uncaught ReferenceError: chartvar is not defined


I m using latest framework7 template.but i saw the error for Uncaught ReferenceError: chartvar is not defined.
Tell me what's the error and solve solution.

![vital](https://user-images.githubusercontent.com/31949378/30511084-4604d1d4-9aef-11e7-96e3-cffe37ffd40c.PNG)

**Comment by crazy-geek94** [comment]
It seems jquery mobile is not compatible with jquery version 3.X and that's the error reason.

**Comment by SivakumarTNS** [comment]
@Dhanasekaranjones How did you solve the **cannot read property 'concat' of undefined**?

**Comment by FritzTheBlitz** [comment]
@SivakumarTNS   [https://stackoverflow.com/questions/38497347/jquery-mobile-1-4-5-uncaught-typeerror-cannot-read-property-concat-of-undefin](https://stackoverflow.com/questions/38497347/jquery-mobile-1-4-5-uncaught-typeerror-cannot-read-property-concat-of-undefin)

**Comment by SivakumarTNS** [comment]
@FritzTheBlitz Thanks for your suggestion.
