### ISSUE TITLE
Uncaught ReferenceError: chartvar is not defined

### ISSUE THREAD

**Issue by Dhanasekaranjones** [jquery/jquery-mobile#8590]
I have used for older Framework7 1.4.0 version earlier.
Now i have updated the latest Framework7 1.6.4 version. But older version methods does not working on 1.6.4.
I saw the error for **Uncaught ReferenceError: chartvar is not defined**.
Pls check and reply the issue solution.

![framework7](https://user-images.githubusercontent.com/31949378/30536547-e0150308-9c83-11e7-8174-363d63f3dc0b.PNG)

**Comment by apsdehal** [comment]
This is repo for jQuery Mobile not Framework 7.
