### ISSUE TITLE
$.event.props is undefined

### ISSUE THREAD

**Issue by sixtyfive** [jquery/jquery-mobile#8595]
A couple of months back I had commented on #8546 about a problem with both 1.4 as well as the latest (at the time) 1.5 code, where `TypeError: $.event.props is undefined` would show up in console. FWIW, that problem does not occur anymore with the lastest (at this time) git code. I would have posted in #8546 had it not been limited to collaborator comments. Posting the information here instead for Google.

**Comment by VishwaJay** [comment]
In FF on Windows, with no additional documentation on the error:

```
TypeError: $.event.props is undefined jquery.mobile-1.4.5.js:3337:20
    jQuery 4
        <anonymous>
        <anonymous>
        <anonymous>
        <anonymous>
```

It's baaaack....

I can't tell if it's clashing with something, it just kinda randomly showed up (no page edits). Hopefully, it reproduces.

**Comment by terremoth** [comment]
Reporting: 2020 using jquery 3.5, jquery mobile 1.4.5 and still showing this error.

**Comment by adrianalin89** [comment]
I'm facing the same deam error. I've updated the jquery code, mobile, and migration libs to the latest version and the issue went away but then the admin will be broken. So I had to revert the libs and find a better solution.
