### ISSUE TITLE
iPhone X and JQM 1.4

### ISSUE THREAD

**Issue by nhinze** [jquery/jquery-mobile#8598]
This article is quite helpful to help fix the iPhone X issues with JQM 1.4 and WebViews.

http://ayogo.com/blog/ios11-viewport/

However, I can't figure out the CSS needed to move the top left menu button and to adjust for the left panel menu.

![iphonex](https://user-images.githubusercontent.com/1156143/32023862-9f79d00c-b9a8-11e7-9c53-56367df91fca.jpg)

**Comment by dems54** [comment]
Hello @nhinze,

Why did you close this issue ? Do you have a solution ?

**Comment by nhinze** [comment]
I fixed it this way:
/* iPhone X fix */
.ui-header-fixed, .ui-header-fixed .ui-btn-left, .ui-header-fixed .ui-btn-right, .panelmenu .ui-panel-inner .ui-listview {
    /* Status bar height on iOS 10 */
    padding-top: 20px !important;

    /* Status bar height on iOS 11.0 */
    padding-top: constant(safe-area-inset-top) !important;

    /* Status bar height on iOS 11+ */
    padding-top: env(safe-area-inset-top) !important;
}

**Comment by X901** [comment]
@nhinze Thank you it fixed my issue

> I fixed it this way:
> 
> ```
> /* iPhone X fix */
> .ui-header-fixed, .ui-header-fixed .ui-btn-left, .ui-header-fixed .ui-btn-right, .panelmenu .ui-panel-inner .ui-listview {
>     /* Status bar height on iOS 10 */
>     padding-top: 20px !important;
> 
>     /* Status bar height on iOS 11.0 */
>     padding-top: constant(safe-area-inset-top) !important;
> 
>     /* Status bar height on iOS 11+ */
>     padding-top: env(safe-area-inset-top) !important;
> }
> ```
