### ISSUE TITLE
Is it possible to restrict the smileys and emojis  in android?

### ISSUE THREAD

**Issue by Maheshwbc** [jquery/jquery-mobile#8616]
I need to restrict smileys and emojis in username/password field .

If the username/password field contains smileys or emojis.
The validation should to "Enter valid username and password".

Otherwise disable to user android input type smileys and emojis options.

$("#u_name").val();
$("#p_word").val();

My app **cordova** 
Need javasctipt or jquery to restrict it

**Comment by apsdehal** [comment]
This isn't a feature that is supported--or will be supported--by jQuery Mobile. This needs to implemented by the developer himself (too specific a request).

**Comment by Maheshwbc** [comment]
Thanks for your feedback.

And i can use this code for validating and its working for me.

function isEmoji(str) {
    var ranges = [
        '\ud83c[\udf00-\udfff]', // U+1F300 to U+1F3FF
        '\ud83d[\udc00-\ude4f]', // U+1F400 to U+1F64F
        '\ud83d[\ude80-\udeff]' // U+1F680 to U+1F6FF
    ];
    if (str.match(ranges.join('|'))) {
        return true;
    } else {
        return false;
    }
}
