### ISSUE TITLE
 Jquery-mobile does not suppport jquery 3.3.1

### ISSUE THREAD

**Issue by stccorp** [jquery/jquery-mobile#8635]
Hello,

jq Mobile 1.4.5 does not seem to support the ;latest jquery 3.3.1  Are there plans to support it?

**Comment by apsdehal** [comment]
Version 1.5.0 which is currently in release phase will support 3.x.

**Comment by stccorp** [comment]
Can I use it for production or too early??

**Comment by Bachstelze** [comment]
JQ Mobile 1.5 isn't official stable. I am questioning whether we can use it for production or have to stick to JQ mobile 1.4 (which has also many unresolved issues) and JQuery 1 or 2.
