### ISSUE TITLE
no builds for 1.5.0-rc1

### ISSUE THREAD

**Issue by slr** [jquery/jquery-mobile#8639]
hey there!

sorry if it is a wrong place to post the issue.

almost two months passed since tag release but no builds on https://code.jquery.com/mobile/ are provided

**Comment by arschmitz** [comment]
Indeed the cdn is broken and not updating this is being worked on by others as this is an organization wide issue no updates from any project are showing

**Comment by arschmitz** [comment]
Sorry about how long this took it was outside of my personal control. It is now up and further updates will follow.

**Comment by slr** [comment]
thank you and all the contributors!

**Comment by ecadius** [comment]
Are the failing builds the problem?
They should nonetheless be working now: https://travis-ci.com/ecadius/jquery-mobile/builds/99162130 https://github.com/ecadius/jquery-mobile
